### PR TITLE
Fail proposal on invalid prevGovActionId

### LINKED ISSUE #3655: Validate previous governance action id upon proposal
This is a nice to have extra safety check that would check that the previous governance action of a specific type is either the very last action that has been enacted or is already in the current proposals set.

This would allow us to:
* filter out invalid proposals right from the start. 
* reconstruct a full chain of how proposals would be enacted, if they would be all enacted that is.
* fully predict the expected updates
* prevent circular dependencies within proposals

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Closes #3655 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs [hunk 1]
```diff
@@ -243,12 +254,49 @@ actionWellFormed ga = failureUnless isWellFormed $ MalformedProposal ga
...
+      isValidMember prev snapshotCond prevActionAccessor =
+        all
+          (== Just True) -- lookup has to succeed _and_ purpose of lookedup action has to match condition
+          ( fmap (snapshotCond . gasAction)
+              . (flip Map.lookup . snapshotGovActionStates $ snapshots ^. curGovSnapshotsL @era)
+              . unPrevGovActionId
+              <$> prev
+          )
+          || prev == prevActionAccessor prevGovActionIds
+      isValid proposal = case proposal ^. pProcGovActionL of
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs]: You can reuse this function here: 
https://github.com/input-output-hk/cardano-ledger/blob/b8c6c136657dc7282dc6fc899b790c28f6393a58/eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs#L340-L351
```suggestion
      isValid proposal = 
        prevActionAsExpected (proposal ^. pProcGovActionL) prevGovActionIds ||
        case proposal ^. pProcGovActionL of
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs [hunk 2]
```diff
@@ -243,12 +254,49 @@ actionWellFormed ga = failureUnless isWellFormed $ MalformedProposal ga
...
+        (PrevGovActionIds era -> StrictMaybe (PrevGovActionId p (EraCrypto era))) ->
+        Bool
+      isValidMember prev snapshotCond prevActionAccessor =
+        all
+          (== Just True) -- lookup has to succeed _and_ purpose of lookedup action has to match condition
+          ( fmap (snapshotCond . gasAction)
+              . (flip Map.lookup . snapshotGovActionStates $ snapshots ^. curGovSnapshotsL @era)
+              . unPrevGovActionId
+              <$> prev
+          )
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs]: This looks correct, but it is written in a very obscure way. I suggest rewriting it with regular pattern matching and clarifying the logic a bit

**Review by lehins — CHANGES_REQUESTED** [review]
Looks right, but I am not 100% sure. Besides addressing the comments could I as you to write a couple of unit test using the DSL that was implemented in #3733

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs [hunk 3]
```diff
@@ -246,12 +258,48 @@ actionWellFormed ga = failureUnless isWellFormed $ MalformedProposal ga
...
+        StrictMaybe (PrevGovActionId p (EraCrypto era)) ->
+        (GovAction era -> Bool) ->
+        Bool
+      isValidMember prev snapshotCond =
+        case prev of
+          SNothing -> True
+          SJust prev' -> case Map.lookup (unPrevGovActionId prev') (snapshotGovActionStates $ snapshots ^. curGovSnapshotsL) of
+            Nothing -> False
+            -- lookup has to succeed _and_ purpose of looked-up action has to match condition
+            Just found -> snapshotCond . gasAction $ found
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs]: This version is much clearer, however there are a few things that need to be changed:

* Whenever previous id is not provided it is invalid, unless it is the very first proposed gov action of that type. Therefore it is only valid for `SNothing` case when `prevActionAsExpected` allows it.
* `isValidMember` is a confusing name, since we have CC members and could easily be confused as related concept. Also it is not just a Map membership test, there is also `snapshotCond` application.
* `foo . bar $ baz` uses two more characters and one more function when compared to `foo $ bar baz`
* There is a specialized function for looking into snapshots: `snapshotLookupId`
```suggestion
      isValidPrevGovActionId prevGovActionId snapshotCond =
        case prevGovActionId of
          SNothing -> False
          SJust (PrevGovActionId govActionId) -> 
            case snapshotLookupId govActionId (snapshots ^. curGovSnapshotsL) of
              Nothing -> False
              -- lookup has to succeed _and_ purpose of looked-up action has to match condition
              Just found -> snapshotCond $ gasAction found
```

File: eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+                    )
+                    SNothing
+                )
+        gaidConstitutionProp <- submitProposal constitutionAction
+        modifyNES $ \nes ->
+          nes
+            & nesEsL . esLStateL . lsUTxOStateL . utxosGovStateL . cgEnactStateL . ensPrevConstitutionL
+              .~ SJust (PrevGovActionId gaidConstitutionProp) -- Add the wrong one to PrevGovActionIds
+            & nesEsL . esLStateL . lsUTxOStateL . utxosGovStateL . cgGovSnapshotsL
+              .~ def -- Remove from snapshots
```
Comment (lehins) [inline eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs]: You should not need to modify the new epoch state for these tests
 ```suggestion
```

File: eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+              NewConstitution
+                (SJust $ PrevGovActionId (gaidConstitutionProp {gaidGovActionIx = GovActionIx 1})) -- make it wrong
+                ( Constitution
+                    ( Anchor
+                        (fromJust $ textToUrl "constitution.1")
+                        constitutionHash
+                    )
+                    SNothing
+                )
+        submitFailingProposal constitutionActionNext
```
Comment (lehins) [inline eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs]:
```suggestion
        let noConfidence = NoConfidence (SJust $ PrevGovActionId gaidConstitutionProp)
        submitFailingProposal noConfidence
```

File: eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs [hunk 6]
```diff
@@ -0,0 +1,128 @@
...
+      itM @Conway "Lookup snapshots" $ do
```
Comment (lehins) [inline eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs]: This test wasn't particularly useful, since it was failing for the same reason as the test above, namely missing govActionId. we could instead make it more interesting and expect it to fail for the reason of mismatched purpose

File: eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+              NewConstitution
+                SNothing
+                ( Constitution
+                    ( Anchor
+                        (fromJust $ textToUrl "constitution.0")
+                        constitutionHash
+                    )
+                    SNothing
+                )
+        gaidConstitutionProp <- submitProposal constitutionAction
```
Comment (lehins) [inline eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs:194]: You should not have it in the proposals if you are testing that the id matches the previously enacted one. In other words in this test you have an impossible state: govActionid is both: the previously enacted one and one of the currently proposed gov actions

You should just generate `gaidConstitutionProp` randomly
```suggestion
```

**Review by lehins — CHANGES_REQUESTED** [review]
There is one important change that is needed and a few other minor improvements

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs [hunk 8]
```diff
@@ -345,17 +346,14 @@ ratifyTransition = do
...
-  prev == pgaConstitution
-prevActionAsExpected _ _ = True -- for the other actions, the previous action is not relevant
+prevActionAsExpected = \case
+  ParameterChange prev _ -> (prev ==) . pgaPParamUpdate
+  HardForkInitiation prev _ -> (prev ==) . pgaHardFork
+  TreasuryWithdrawals _ -> const True
+  NoConfidence prev -> (prev ==) . pgaCommittee
+  UpdateCommittee prev _ _ _ -> (prev ==) . pgaCommittee
+  NewConstitution prev _ -> (prev ==) . pgaConstitution
+  InfoAction -> const True
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs:356]: Nice refactoring :+1:

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs (hunk 3 above)
Comment (aniketd) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs]: I could not agree more. Thanks for the insightful catch on the `SNothing` part too! :+1:

File: eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs (hunk 4 above)
Comment (aniketd) [reply eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs]: The thought process behind this was the following:
1. In the first test, the initial proposal has been only added to the snapshots and hasn't been enacted yet. We propose an invalid proposal, and expect it to fail.
2. In the second test, the initial proposal has also been only added to the snapshots and hasn't been enacted yet. We propose a valid proposal this time, but we want to make sure that if a previous proposal does not appear in the snapshots but has been enacted before, we still want it to pass the validation check, unless I'm completely misunderstanding this.

I also think I named the tests badly in this case. I will make this more explicit if you are okay with this thought process for testing.

1. Reject when id is not present in either snapshot or enacted state
2. Reject when id is present but purpose does not match in either snapshot or enacted state
3. Accept when id and purpose match in snapshots
4. Accept when id and purpose match in enacted state.

File: eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs (hunk 7 above)
Comment (aniketd) [reply eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs:194]: I have updated the tests to be exhaustive in the cases mentioned in a previous comment. Let me know your thoughts on the update. I think the update removes this case.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs (hunk 8 above)
Comment (aniketd) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs:356]: Thank you! :raised_hands:

File: eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs (hunk 4 above)
Comment (aniketd) [reply eras/conway/impl/test/Test/Cardano/Ledger/Conway/GovSpec.hs]: I have also now added the test for "first ever proposal" while all other proposals with same purpose have to fail.

**Review by lehins — APPROVED** [review]
:+1: Very nice.
