### PR TITLE
Sort Proposals when translating to SpecRep

### LINKED ISSUE #4577: Fix the mismatch in proposal ordering
IntersectMBO/formal-ledger-specifications#516 was merged recently and that has caused GOV conformance tests to fail. Investigate why that is happening and fix the problem.

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

The implementation sorts proposals at the epoch boundary, but the spec sorts whenever a new proposal is added. 

This PR changes the `SpecTranslate` instance of `Proposals` so that all the proposals are sorted based on their priority during the translation.

closes #4577

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

### CODE REVIEW

File: libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/SpecTranslate/Conway/Base.hs [hunk 1]
```diff
@@ -881,7 +884,14 @@ instance
...
 
-  toSpecRep = toSpecRep . view pPropsL
+  -- TODO get rid of `prioritySort` once we've changed the implementation so
+  -- that the proposals are always sorted
+  toSpecRep = toSpecRep . prioritySort . view pPropsL
+    where
+      prioritySort ::
+        OMap (GovActionId (EraCrypto era)) (GovActionState era) ->
+        OMap (GovActionId (EraCrypto era)) (GovActionState era)
+      prioritySort = Exts.fromList . sortOn (actionPriority . gasAction) . Exts.toList
```
Comment (TimSheard) [inline libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/SpecTranslate/Conway/Base.hs:894]: How is Ext.toList and Ext.fromList  different from just ordinary lists. Might explain that.

**Review by TimSheard — APPROVED** [review]
Approved

**Review by lehins — APPROVED** [review]
:+1:

File: libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/SpecTranslate/Conway/Base.hs (hunk 1 above)
Comment (lehins) [reply libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/SpecTranslate/Conway/Base.hs:894]: @Soupstraw Tim and I talked about it during the meeting, but if you'd like to elaborate on it further that'll be good too. (Resolving, so I can merge the PR)
