### PR TITLE
Remove delegators field from conway-genesis JSON

### LINKED ISSUE #4782: JSON roundtripping of ConwayGenesis fails on a particular file
Dear ledger team, thank you very much for your hard work!

While working on `create-testnet-data` (the command to generate testnet configurations in cardano-cli), I observed in a test (in [this PR](https://github.com/IntersectMBO/cardano-cli/pull/987)) that decoding a `conway-genesis.json` file was causing some data to be lost: the `delegators` fields in the `initialDReps` list.

Here is how to reproduce it using `cabal repl`:

```shell
> cabal repl cardano-ledger-conway:lib:cardano-ledger-conway
> import Data.Aeson
> import Data.Maybe
> x :: ConwayGenesis StandardCrypto <- fromJust <$> decodeFileStrict "/home/churlin/dev/cardano-ledger-2/conway-genesis.json"
> encodeFile "/home/churlin/dev/cardano-ledger-2/conway-genesis-roundtrip.json" x
```

* The input file `conway-genesis.json` is the following: [conway-genesis.json](https://github.com/user-attachments/files/18011348/conway-genesis.json)
* The obtained file `conway-genesis-roundtrip.json` is the following: [conway-genesis-roundtrip.json](https://github.com/user-attachments/files/18011355/conway-genesis-roundtrip.json)

When comparing the input file `conway-genesis.json` (to the left) with the file obtained after decoding and reencoding (`conway-genesis-roundtrip.json`), the value within the `delegators` fields have been lost: 

image

Let me know if I can be of any help to solve this! Note that the input file is not generated manually, but programmatically, here: https://github.com/IntersectMBO/cardano-cli/blob/5e1e4f2ef30da7ffe02642a89870f990bd2d2216/cardano-cli/src/Cardano/CLI/EraBased/Run/Genesis/CreateTestnetData.hs#L369

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Closes #4782 

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [ ] ~~Tests added or updated when needed.~~
- [x] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] ~~Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).~~
- [ ] ~~Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).~~
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

File: libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs [hunk 1]
```diff
@@ -186,7 +186,9 @@ instance ToJSON DRepState where
           object $
             [ "expiry" .= toJSON drepExpiry
             , "deposit" .= toJSON drepDeposit
-            , "delegators" .= toJSON drepDelegs
+            -- Since the corresponding `FromJSON` instance ignores this field, we omit it from
+            -- the `ToJSON` instance as well. Round-tripping is therefore as expected.
+            -- , "delegators" .= toJSON drepDelegs
```
Comment (teodanciu) [inline libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs]: Just a nitpick, feel free to ignore it - i would mention the name of the field instead of the last line, which looks a bit like dead code we forgot to remove. Maybe something like :
```suggestion
            -- Since the corresponding `FromJSON` instance ignores the `delegators` field,
            -- we omit it from the `ToJSON` instance, ensuring that round-tripping behaves as expected.
```

**Review by teodanciu — APPROVED** [review]
Looks good to me. I was surprised that the golden test is still passing..but then I saw that the this optional field was conveniently left out :laughing:

File: libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs (hunk 1 above)
Comment (aniketd) [reply libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs]: Thanks for the nice suggestion! 🙌
