### PR TITLE
Fix AlonzoPlutusPurpose CBOR instances

### LINKED ISSUE #4110: Issue with `AlonzoUtxowPredFailure` predicate failure serialization
Fix in #4013 revealed a problem. Needs investigation and a backwards compatible fix.

```haskell
    alonzo/AlonzoUtxowPredFailure:                                FAIL
      *** Failed! (after 6 tests):
      Failed to deserialize encoded:
      Encoder Version: Version 2
      Decoder Version: Version 2
      No Decoder error
      No Dropper error
      Conformance error: Despite successful deserialization the produced FlatTerm for the type is not valid
      Original:
      Could not decode as Term: DecoderErrorLeftover "Term" "\EOT\SOH\STX\SOH\SOH"
      OriginalHex:
      0x82078501030300020401020101
      ExtraRedeemers [AlonzoMinting (AsIx {unAsIx = 3}),AlonzoRewarding (AsIx {unAsIx = 0}),AlonzoCertifying (AsIx {unAsIx = 4}),AlonzoMinting (AsIx {unAsIx = 2}),AlonzoMinting (AsIx {unAsIx = 1})]
      Use --quickcheck-replay=75510 to reproduce.
      Use -p '/alonzo\/AlonzoUtxowPredFailure/' to rerun this test only.
```

Related ticket #3866

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Closes #4110

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [x] Tests added or updated when needed.
- [x] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] ~~Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).~~
- [ ] ~~Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).~~
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs [hunk 1]
```diff
@@ -344,15 +344,21 @@ instance Era era => DecCBORGroup (AlonzoPlutusPurpose AsIx era) where
       3 -> AlonzoRewarding . AsIx <$> decCBOR
       n -> fail $ "Unexpected tag for AlonzoPlutusPurpose: " <> show n
 
--- | Incorrect CBOR implementation. Missing length encoding. Must keep it for backwards
--- compatibility
 instance Era era => EncCBOR (AlonzoPlutusPurpose AsIx era) where
```
Comment (teodanciu) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs]: And how about `EncCBORGroup` ?   Is the current implementation correct and just its usage here was wrong?

**Review by lehins — COMMENTED** [review]
Implementation in this PR is correct. However, I'd recommend in order to reduce duplication to utilize `QuantifiedConstraints`. This way we can provide the same instance for all `f` instead of separate, but identical instances for `AsIx` and `AsItem`. Previously those instances where separated, since they were different.
See `ConwayPlutusPurpose` instances for inspiration.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs (hunk 1 above)
Comment (lehins) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs]: > Is the current implementation correct

Yes

>  just its usage here was wrong

Yes

Both `EncCBOR` and `DecCBOR` for `AlonzoPlutusPurpose AsIx` where not used for serialization of redeemers:

https://github.com/IntersectMBO/cardano-ledger/blob/3ae9159f5868a31d393a5029569ff28969d5329d/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs#L618

Those instances where incorrect, since they relied on `CBORGroup`, but those where only used for `ExtraRedeemers` predicate failure, which we can now finally fix

**Review by lehins — APPROVED** [review]
Perfect! Thank you!
