### PR TITLE
Replace NominalDiffTime with a newtype wrapper.

### LINKED ISSUE #3185: CBOR serialization of NominalDiffTime is broken
Current `Decoder`/`Encoding` and consequently `FromCBOR`/`ToCBOR` instances for `NominalDiffTime` assume/round the value down to 1/100000 of precision that the type is capable of representing. It seems that the only reason for this strange behavior is the  `ShelleyGenesis.sgSlotLength` field.

This needs fixing. I do not know for sure the reason for the comment in this instance:
```
-- | For backwards compatibility we round pico precision to micro
instance FromCBOR NominalDiffTime where
  fromCBOR = fromRational . (% 1e6) <$> fromCBOR
```

but from the looks of it the only place `NominalDiffTime` is being used in is the `ShelleyGenesis` type, which we have full control over because the value is always set to 1s (thus encoded as 1000000).

So, this ticket requires some investigation and if it turns out that in fact the only place that the `NominalDiffTime` is being used is in the `ShelleyGenesis`, then it needs to be switched to some newtype that wraps around the `NominalDiffTime` with the rounded instance, while the original type `NominalDiffType` should have its instances fixed (or even better totally removed). There is already a `newtype` like this in roundtrip testing, which could be adopted for this purpose.

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Remove CBOR instances of NominalDiffTime and only keep those for the newtype wrapper. This is because we don't use full precision during serialisation.

Closes #3185 

# Checklist

- [x] Commit sequence broadly makes sense
- [x] Commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] Any changes are noted in the [changelog](../CHANGELOG.md)
- [x] Code is formatted with ormolu (which can be run with `scripts/ormolise.sh`
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 1]
```diff
@@ -129,6 +143,37 @@ emptyGenesisStaking =
       sgsStake = mempty
     }
 
+-- | We do not handle the full precision of NominalDiffTime.
+newtype NominalDiffTimeRounded = NominalDiffTimeRounded NominalDiffTime
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: On a second thought. Let's switch this `newtype` around the [`Micro`](https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Fixed.html#t:Micro) type.
```suggestion
-- Unlike `NominalDiffTime` that supports `Pico` precision, this type only supports `Micro` precision
newtype NominalDiffTimeMicro = NominalDiffTimeMicro Micro
```

Also implementing and exporting these three functions:
```
toNominalDiffTimeMicro :: NominalDiffTime -> Maybe NominalDiffTimeMicro

toNominalDiffTimeMicroWithRounding :: NominalDiffTime -> NominalDiffTimeMicro

fromNominalDiffTimeMicro :: NominalDiffTimeMicro -> NominalDiffTime
```

This way the type will be correct b y construction, instead of it rounding at the time of serialization

**Review by lehins — CHANGES_REQUESTED** [review]
This looks great, but I just realized  we can do even better. Let me know if you  have questions about this

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 1 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: Awesome! :raised_hands:

**Review by JaredCorduan — APPROVED** [review]
looks great to me, thank you @aniketd !

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 1 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: I have updated the PR with these additions! :raised_hands:

Comment (lehins) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: It is still a newtype wrapper around the `NominalDiffTime`. The point is that `NominalDiffTime` is a newtype wrapper around [`Pico`](https://downloads.haskell.org/ghc/9.2.5/docs/html/libraries/base-4.16.4.0/Data-Fixed.html#t:Pico) and we want a type that is a wrapper around [`Micro`](https://downloads.haskell.org/ghc/9.2.5/docs/html/libraries/base-4.16.4.0/Data-Fixed.html#t:Micro)

File: CHANGELOG.md [hunk 2]
```diff
@@ -45,6 +45,7 @@ in the naming of release branches.
 
 ### Changed
 
+- Replace `NominalDiffTime` with a `newtype` wrapper `NominalDiffTimeRounded`. Remove use of `NominalDiffTime`, as we don't use its full precision. #3208
```
Comment (lehins) [inline CHANGELOG.md]:
```suggestion
- Replace `NominalDiffTime` with a `newtype` wrapper `NominalDiffTimeMicro`. Remove use of `NominalDiffTime`, as we don't use its full precision. #3208
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 3]
```diff
@@ -129,6 +146,52 @@ emptyGenesisStaking =
...
+
+-- | For backwards compatibility we round pico precision to micro
+decodeNominalDiffTimeMicro :: Decoder s NominalDiffTimeMicro
+decodeNominalDiffTimeMicro = NominalDiffTimeMicro <$> fromRational . (% 1_000_000) <$> decodeInteger
+
+nominalDiffTimeMicroToSeconds :: NominalDiffTimeMicro -> Pico
+nominalDiffTimeMicroToSeconds (NominalDiffTimeMicro ndtm) = nominalDiffTimeToSeconds ndtm
+
+secondsToNominalDiffTimeMicro :: Pico -> NominalDiffTimeMicro
+secondsToNominalDiffTimeMicro (MkFixed s) =
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: With my suggestion this function would become:
```suggestion
secondsToNominalDiffTimeMicro :: Micro -> NominalDiffTimeMicro
secondsToNominalDiffTimeMicro  = NominalDiffTimeMicro
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 4]
```diff
@@ -129,6 +146,52 @@ emptyGenesisStaking =
...
+  | otherwise = Nothing
+  where
+    ndtm = toNominalDiffTimeMicroWithRounding ndt
+
+toNominalDiffTimeMicroWithRounding :: NominalDiffTime -> NominalDiffTimeMicro
+toNominalDiffTimeMicroWithRounding ndt =
+  secondsToNominalDiffTimeMicro $ nominalDiffTimeToSeconds ndt
+
+fromNominalDiffTimeMicro :: NominalDiffTimeMicro -> NominalDiffTime
+fromNominalDiffTimeMicro (NominalDiffTimeMicro ndt) = ndt
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: This would become
```suggestion
fromNominalDiffTimeMicro (NominalDiffTimeMicro (MkFixed ndt)) = NominalDiffTimeMicro (MkFixed (ndtm * 1_000_000))
```

Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: I get it now! Thanks! :raised_hands:

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 1 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: I don't know how I missed that detail. :face_exhaling:. I have pushed the latest changes now :raised_hands:

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 5]
```diff
@@ -129,6 +149,71 @@ emptyGenesisStaking =
...
+-- | Unlike @'NominalDiffTime'@ that supports @'Pico'@ precision, this type
+-- only supports @'Micro'@ precision.
+newtype NominalDiffTimeMicro = NominalDiffTimeMicro Micro
+  deriving (Show, Eq, Generic)
+  deriving anyclass (NoThunks)
+  deriving newtype (Ord, Num, Fractional, Real, ToJSON, FromJSON)
+
+deriving instance Generic Micro
+
+deriving anyclass instance NoThunks Micro
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: It is better to move this instance into `Cardano.Ledger.Orphans` and leave  a `TODO` that we should upstream instance `HasResolution p => NoThunks (Fixed p)` into `nothunks` package
```suggestion
deriving anyclass instance NoThunks Micro
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 6]
```diff
@@ -129,6 +149,71 @@ emptyGenesisStaking =
...
+
+instance ToCBOR NominalDiffTimeMicro where
+  toCBOR = encodeNominalDiffTimeMicro
+
+encodeNominalDiffTimeMicro :: NominalDiffTimeMicro -> Encoding
+encodeNominalDiffTimeMicro (NominalDiffTimeMicro micro) =
+  encodeInteger . toMicroseconds $ micro
+  where
+    toMicroseconds t =
+      numerator (toRational t * toRational (resolution $ Proxy @E6))
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: This one is much easier ;) 
```suggestion
encodeNominalDiffTimeMicro (NominalDiffTimeMicro (MkFixed micro)) = encodeInteger micro
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 7]
```diff
@@ -129,6 +149,71 @@ emptyGenesisStaking =
...
+
+instance FromCBOR NominalDiffTimeMicro where
+  fromCBOR = decodeNominalDiffTimeMicro
+
+decodeNominalDiffTimeMicro :: Decoder s NominalDiffTimeMicro
+decodeNominalDiffTimeMicro =
+  NominalDiffTimeMicro . fromRational . (% 1_000_000) <$> decodeInteger
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: I think this one is wrong, it should be:
```suggestion
  NominalDiffTimeMicro . MKFixed <$> decodeInteger
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 8]
```diff
@@ -129,6 +149,71 @@ emptyGenesisStaking =
...
+  microsecondsToNominalDiffTimeMicro . picoToMicro . nominalDiffTimeToSeconds
+
+toNominalDiffTimeMicro :: NominalDiffTime -> Maybe NominalDiffTimeMicro
+toNominalDiffTimeMicro ndt
+  | roundedPicoseconds == picoseconds = Just ndtm
+  | otherwise = Nothing
+  where
+    ndtm@(NominalDiffTimeMicro microseconds) = toNominalDiffTimeMicroWithRounding ndt
+    picoseconds = nominalDiffTimeToSeconds ndt
+    roundedPicoseconds = microToPico microseconds
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: This can also be simpler:
```suggestion
  | fromNominalDiffTimeMicro ndtm == ndt = Just ndtm
  | otherwise = Nothing
  where
    ndtm = toNominalDiffTimeMicroWithRounding ndt
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 9]
```diff
@@ -129,6 +149,71 @@ emptyGenesisStaking =
...
+  deriving (Show, Eq, Generic)
+  deriving anyclass (NoThunks)
+  deriving newtype (Ord, Num, Fractional, Real, ToJSON, FromJSON)
+
+deriving instance Generic Micro
+
+deriving anyclass instance NoThunks Micro
+
+instance ToCBOR NominalDiffTimeMicro where
+  toCBOR = encodeNominalDiffTimeMicro
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: In fact the `To/FromCBOR` instances can be derived using GND. All you need is to add these standalone instances to:

`Cardano.Ledger.Binary.Encoding.ToCBOR` and `Cardano.Ledger.Binary.Decoding.FromCBOR`:

```haskell
deriving newtype instance ToCBOR (MkFixed p)
deriving newtype instance FromCBOR (MkFixed p)
```

File: eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Serialisation/EraIndepGenerators.hs [hunk 10]
```diff
@@ -155,6 +155,10 @@ instance (Era era, Mock (EraCrypto era)) => Arbitrary (Update era) where
   arbitrary = genericArbitraryU
   shrink = genericShrink
 
+instance Arbitrary NominalDiffTimeMicro where
+  arbitrary = secondsToNominalDiffTimeMicro <$> arbitrary
+  shrink = fmap secondsToNominalDiffTimeMicro . shrink . nominalDiffTimeMicroToSeconds
```
Comment (lehins) [inline eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Serialisation/EraIndepGenerators.hs]: This is too much work, instead
```suggestion
deriving newtype instance Arbitrary NominalDiffTimeMicro
```

**Review by lehins — CHANGES_REQUESTED** [review]
Looks good. Deserializer is a bit borked, but there is a really easy fix for it

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 5 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: Awesome! Thanks! :bow:

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 9 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: I found instances already present for `Nano`, `Pico`, so I added similar ones directly for `Micro` instead of deriving. Is that okay?

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 6 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: Now that we have the instance for `Micro` the codec was easy to convert to `deriving newtype (ToCBOR, FromCBOR)`

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 7 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: Same here as for the `encode`. This could be changed to `deriving newtype (FromCBOR)` as we added the instance for `Micro` to `Cardano.Ledger.Binary.Decoding.FromCBOR`. :+1:

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 8 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: Awesome! Thanks! :bow:

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 9 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: I have replaced all instances (`Nano`, `Pico`, `Micro`) with `deriving newtype instance Typeable p => {To|From}CBOR (Fixed p)`

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs [hunk 11]
```diff
@@ -129,6 +146,48 @@ emptyGenesisStaking =
...
+  | fromNominalDiffTimeMicro ndtm == ndt = Just ndtm
+  | otherwise = Nothing
+  where
+    ndtm = toNominalDiffTimeMicroWithRounding ndt
+
+microsecondsToNominalDiffTimeMicro :: Micro -> NominalDiffTimeMicro
+microsecondsToNominalDiffTimeMicro = NominalDiffTimeMicro
+
+secondsToNominalDiffTimeMicro :: Pico -> NominalDiffTimeMicro
+secondsToNominalDiffTimeMicro = NominalDiffTimeMicro . picoToMicro
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: Having both of these functions is confusing and unnecessary. Because:
```haskell
> secondsToNominalDiffTimeMicro 15 == microsecondsToNominalDiffTimeMicro 15
True
```

I suggest keep only one of them and rename it:
```haskell
microToNominalDiffTimeMicro :: Micro -> NominalDiffTimeMicro
microToNominalDiffTimeMicro = NominalDiffTimeMicro
```
Alternative name for the above function could also be `secondsToNominalDiffTimeMicro`, which would stay inline with the previous version. Point is that when you call these functions above you don't supply microseconds or picoseconds, but rather seconds with microsecond or picosecond precision respectively. So, feel free to choose whichever name you like better, the important part is not to keep two functions with morally conflicting names.

File: libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs [hunk 12]
```diff
@@ -60,6 +66,12 @@ instance NoThunks WC.XSignature where
 instance SignableRepresentation (Hash.Hash a b) where
   getSignableRepresentation = Hash.hashToBytes
 
+-- | TODO: We should upstream instance
+-- HasResolution p => NoThunks (Fixed p) into the nothunks package.
+deriving anyclass instance NoThunks Micro
+
+deriving instance Generic Micro
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs]: I am worried that it can lead to duplicate instance somewhere down stream. I don't think we need this either

File: libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs [hunk 13]
```diff
@@ -60,6 +66,12 @@ instance NoThunks WC.XSignature where
 instance SignableRepresentation (Hash.Hash a b) where
   getSignableRepresentation = Hash.hashToBytes
 
+-- | TODO: We should upstream instance
+-- HasResolution p => NoThunks (Fixed p) into the nothunks package.
+deriving anyclass instance NoThunks Micro
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs]: `Fixed` is a just a newtype wrapper around Integer, so this way is better
```suggestion
deriving newtype instance NoThunks (Fixed p)
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs [hunk 14]
```diff
@@ -1,7 +1,11 @@
+{-# LANGUAGE DeriveAnyClass #-}
+{-# LANGUAGE DeriveGeneric #-}
 {-# LANGUAGE DerivingStrategies #-}
+{-# LANGUAGE FlexibleInstances #-}
 {-# LANGUAGE GeneralizedNewtypeDeriving #-}
 {-# LANGUAGE ScopedTypeVariables #-}
 {-# LANGUAGE StandaloneDeriving #-}
+{-# LANGUAGE TypeSynonymInstances #-}
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs]: These are no longer needed with my comments below
```suggestion
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StandaloneDeriving #-}
```

**Review by lehins — APPROVED** [review]
Looks great. Just a few final comments.

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs (hunk 11 above)
Comment (aniketd) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Genesis.hs]: > when you call these functions above you don't supply microseconds or picoseconds, but rather seconds

Thanks for that! :100: :bow: I completely failed at understanding this :heart:

File: libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs (hunk 12 above)
Comment (aniketd) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs]: This is necessary due to the `NoThunks` derivation. GHC complains without it. Is there a better place to put it may be? Or some other way?
```haskell
deriving newtype instance NoThunks (Fixed p)
deriving stock instance Generic (Fixed p)
```
...seems to work out.

Comment (aniketd) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Orphans.hs]: Sorry, I'm wrong here, by keeping the `DeriveGeneric`. Removing it and just keeping `newtype` with `GeneralizedNewtypeDeriving` did the trick. Thanks a ton! :bow: :heart_eyes: :spiral_notepad: :man_student: :exploding_head:
