### PR TITLE
Updated spec to fix a conformance failure

### LINKED ISSUE #4754: conformance test failure on CI
First occured: https://github.com/IntersectMBO/cardano-ledger/actions/runs/11830083195/job/32964884060

Reproducer: 

```
  To rerun use: --match "/Conway/Conformance/Blocks transition graph/UTXO/" --seed 1763573222

Randomized with seed 1763573222

Finished in 793.4878 seconds
36 examples, 1 failure, 9 pending
```

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR bumps the spec to a version that calculates refunds properly. I also modified the `extraInfo` method to give access to the final state when creating the debug message.

closes #4754

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

### CODE REVIEW

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs [hunk 1]
```diff
@@ -1444,17 +1445,22 @@ registerRewardAccount = do
   khDelegator <- freshKeyHash
   registerStakeCredential (KeyHashObj khDelegator)
 
+tryLookupReward :: Credential 'Staking (EraCrypto era) -> ImpTestM era (Maybe Coin)
```
Comment (teodanciu) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs:1451]: I find the names of the two functions, `tryLookupReward` and `lookupReward`  a little confusing  relative to their return type-  if anything,  I think switching their names would be more intuitive, since `lookupReward` in my opinion hints to an optional result, while `tryLookup` to something that might fail in certain conditions.  But it might be subjective, so I don't mind too much to leave it like this.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 2]
```diff
@@ -64,6 +67,49 @@ spec =
...
+          & withdrawalsTxBodyL
+            .~ Withdrawals
+              ( Map.fromList
+                  [ (rewardAccount, Coin 0)
+                  , (otherRewardAccount, govActionDeposit)
+                  ]
+              )
+      lookupReward otherStakeCred `shouldReturn` Coin 0
+      expectNotRegisteredRewardAddress rewardAccount
+      pure ()
```
Comment (teodanciu) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: `pure ()` seems unnecessary
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 3]
```diff
@@ -64,6 +67,49 @@ spec =
...
+      khStakePool <- freshKeyHash
+      registerPool khStakePool
+      submitTx_ . mkBasicTx $
+        mkBasicTxBody
+          & certsTxBodyL
+            .~ SSeq.fromList
+              [ DelegTxCert stakeCred (DelegStakeVote khStakePool DRepAlwaysAbstain)
+              , DelegTxCert otherStakeCred (DelegStakeVote khStakePool DRepAlwaysAbstain)
+              ]
+      _ <- tryLookupReward stakeCred
```
Comment (teodanciu) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: What is this line testing? Why not check the expected value?

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 4]
```diff
@@ -64,6 +67,49 @@ spec =
         [fromNativeScript spendingScript, fromNativeScript spendingScript]
           ++ extraScripts
           ++ extraScripts
+
+    it "deregistering returns the deposit" $ do
```
Comment (teodanciu) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: Is this the right place for this test?  I know it's not very precise how we assign tests to specs, especially when not testing for a specific predicate failure, but I find it surprising to see it in `UtxoSpec` . 
`CertSpec`, `DelegSpec` or `EpochSpec` would seem less surprising for me, but perhaps there is a reason that I'm missing. 
If we're leaving it in UtxoSpec, certainly it shouldn't be under `Reference scripts`.

**Review by teodanciu — COMMENTED** [review]
Looks good to me, just some questions and observations.

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs [hunk 5]
```diff
@@ -71,6 +71,7 @@ module Test.Cardano.Ledger.Shelley.ImpTest (
   registerRewardAccount,
   registerStakeCredential,
   getRewardAccountFor,
+  tryLookupReward,
```
Comment (teodanciu) [inline eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs:74]: Could go into shelley CHANGELOG

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs (hunk 1 above)
Comment (Soupstraw) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs:1451]: I guess an alternative naming scheme would be `lookupReward` and `unsafeLookupReward`. But I based this naming on how we have named `submitTx` and `trySubmitTx`

Comment (Soupstraw) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs:1451]: I think since these functions are used for testing then `unsafe` is not the best prefix, because we really want that function to throw an exception, it's a feature rather than "undefined behavior".

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs (hunk 3 above)
Comment (Soupstraw) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: Removed it, there are assertions for the reward addresses on the next two lines anyways

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs (hunk 4 above)
Comment (Soupstraw) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: I moved it to `DelegSpec`

**Review by teodanciu — APPROVED** [review]
Looks good to me

File: eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs (hunk 1 above)
Comment (lehins) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs:1451]: "unsafe" is a bad prefix in such scenario, because unsafe in Haskell usually describes things that violate some invariant and lead to dangerous situations like segfaults or other unpredictable behavior. Functions that throw errors when something goes wrong are called partial instead of unsafe. Considering that these function don't deal with anything unsafe there names should follow the common convention that is used in other libraries: 
* `lookup` to mean a total function that returns a `Maybe`
* `try` to mean a recovery from failure that returns an `Either`
* something like `get` or `partial` to indicate a runtime error. 

So, the names I propose are:
* change `lookup[Reward|KeyPair|...]` to indicate a total function that returns `Maybe`
* make partial functions prefixed with `get[Reward|KeyPair|..]`

I am ok with merging this PR with current naming and fixing all of this in a separate PR

Comment (lehins) [reply eras/shelley/impl/testlib/Test/Cardano/Ledger/Shelley/ImpTest.hs:1451]: Created a ticket for this rename #4760

**Review by lehins — APPROVED** [review]
Needs to run `fourmolu`. Other than that it is good to go.
