### PR TITLE
better collateral predicate failure

### LINKED ISSUE #2408: [BUG] - InsufficientCollateral error doesn't consider collateral percentage
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
Collateral is influenced by the `collateralPercentage` parameter. But if insufficient collateral is provided the error does not take this into account, it always displays using fee value.

**Steps to reproduce**
1. On a network configured with `collateralPercentage` to something other than '100'. e.g. alonzo-white is currently set to '150'
2. Submit transaction to execute non-native (plutus) script using collateral utxo equal to fee amount (not 150% of fee)
3. Observe error
```
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (InsufficientCollateral (Coin 1400000000) (Coin 1400000000))))])
```

**Expected behavior**
The InsufficientCollateral error should consider  `collateralPercentage` so it is clear to the user exactly how much collateral is expected.

**System info (please complete the following information):**
- OS Name: Mint
- OS Version: 20.2 (Uma)
- Node version: cardano-node 1.27.0 - linux-x86_64 - ghc-8.10 git rev acefba14ef54235ab43105b421754065152da165
- CLI version: cardano-cli 1.27.0 - linux-x86_64 - ghc-8.10 git rev acefba14ef54235ab43105b421754065152da165

**Screenshots and attachments**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by JaredCorduan**
The previous `InsufficientCollateral` predicate failure was reporting the given fee, not the required collateral, which is confusing. We now report the required collateral.

The golden/example test changes are a bit noisy since I made it now possible to use different protocol parameters, and I also change the amount in the collateral output.

Additionally, in a separate commit, I added an unrelated test. While debugging a separate issue, I made the test for the API function `evaluateTransactionFee` better and I also now test it in alonzo.

closes #2408

### CODE REVIEW

File: shelley/chain-and-ledger/shelley-spec-ledger-test/test/Test/Shelley/Spec/Ledger/Fees.hs [hunk 1]
```diff
@@ -508,12 +509,19 @@ testEvaluateTransactionFee :: Assertion
 testEvaluateTransactionFee =
   API.evaluateTransactionFee @(ShelleyEra C_Crypto)
     pp
-    (txSimpleUTxO @C_Crypto)
+    txSimpleUTxONoWit
     1
-    @?= Coin 103
+    @?= minfee pp (txSimpleUTxO @C_Crypto)
```
Comment (lehins) [inline shelley/chain-and-ledger/shelley-spec-ledger-test/test/Test/Shelley/Spec/Ledger/Fees.hs:514]: I don't think it is a good idea to switch to `@?= minfee ...` because then this unit test only checks in the end that `evaluateMinFee` indeed calls `minfee`. Hard coding the expected value is better for a unit test like that. 

If it was a property test it would make more sense, but not for a unit test.

~Also,  I might be misunderstanding something, but `evaluateTransactionFee` adds a dummy witnesses, but `minfee`  is getting a different witness, namely `makeWitnessesVKey (hashAnnotated $ txbSimpleUTxO @c) [alicePay]`, so it seem a bit hacky to me.~ Nevermind, it seem like the whole purpose of `evaluateTransactionFee` is to estimate the fee without knowing witness' keys ahead of time.

File: cardano-ledger-test/src/Test/Cardano/Ledger/Examples/TwoPhaseValidation.hs [hunk 2]
```diff
@@ -1889,3 +1929,29 @@ alonzoBBODYexamples =
...
   where
     pf = Alonzo Mock
+
+testEvaluateTransactionFee :: Assertion
+testEvaluateTransactionFee =
+  evaluateTransactionFee @A
+    pparams
+    validatingTxNoWits
+    1
+    @?= minfee pparams (validatingTx pf)
```
Comment (lehins) [inline cardano-ledger-test/src/Test/Cardano/Ledger/Examples/TwoPhaseValidation.hs:1939]: Same here, without providing expected value we aren't testing the implementation of `minfee`, because `evaluateTransactionFee` itself calls `minfee`. In other words if `minfee` has a bug, we won't catch it. Hard coding expected values in tests is better.

**Review by lehins — APPROVED** [review]
Minor comments on the test cases, but the rest looks good.

File: shelley/chain-and-ledger/shelley-spec-ledger-test/test/Test/Shelley/Spec/Ledger/Fees.hs (hunk 1 above)
Comment (JaredCorduan) [reply shelley/chain-and-ledger/shelley-spec-ledger-test/test/Test/Shelley/Spec/Ledger/Fees.hs:514]: exactly, `evaluateTransactionFee` is really just hoping to get `minfee` correct without having all the key witnesses yet.

File: cardano-ledger-test/src/Test/Cardano/Ledger/Examples/TwoPhaseValidation.hs (hunk 2 above)
Comment (JaredCorduan) [reply cardano-ledger-test/src/Test/Cardano/Ledger/Examples/TwoPhaseValidation.hs:1939]: maybe I should just have both tests?

Comment (lehins) [reply cardano-ledger-test/src/Test/Cardano/Ledger/Examples/TwoPhaseValidation.hs:1939]: I can add a property test just like that in the work that I am doing. So I can change this test to a hard coded value in a later PR, if that works for you.

Comment (JaredCorduan) [reply cardano-ledger-test/src/Test/Cardano/Ledger/Examples/TwoPhaseValidation.hs:1939]: that would be great, thank you!

**Review by nc6 — APPROVED** [review]
