### PR TITLE
PParamsUpdate enactment fix

### LINKED ISSUE #3835: parameter change enacted with only 1 DREP abstain vote
A governance action that attempts to change keyDeposit gets enacted with only one DREP abstain vote. Aparently the pre-condition is that this is the first governance action of this type and there are NO cc member yet on the system 

```
cardano-cli conway governance vote create --abstain --governance-action-tx-id 9b86469bf8f7cd78a1bf74ffa768e494e768f7ef8d466211a86c8612f699c5c6 --governance-action-index 0 --drep-verification-key-file example/dreps/drep1.vkey --out-file example/transactions/pparams-drep1.vote`
```

```
+ cardano-cli conway transaction build --testnet-magic 42 --tx-in 9b86469bf8f7cd78a1bf74ffa768e494e768f7ef8d466211a86c8612f699c5c6#0 --change-address addr_test1qzdzkxlp8pa44w9lc7ehqe4xtq3zghz7evllm2z38pw2axs0yw2mdz2ka5h0luedjtj8nc22aymdguhk4cgx5puqqscsgx4dry --vote-file example/transactions/pparams-drep1.vote --witness-override 2 --out-file example/transactions/pparams-dreps-vote-tx.raw
Estimated transaction fee: Lovelace 172849
+ cardano-cli conway transaction sign --testnet-magic 42 --tx-body-file example/transactions/pparams-dreps-vote-tx.raw --signing-key-file example/utxo-keys/payment1.skey --signing-key-file example/dreps/drep1.skey --out-file example/transactions/pparams-dreps-vote-tx.signed
+ cardano-cli conway transaction submit --testnet-magic 42 --tx-file example/transactions/pparams-dreps-vote-tx.signed
Transaction successfully submitted.
```

```
+ cardano-cli conway query gov-state --testnet-magic 42
+ jq -r .proposals.psGovActionStates
{
  "9b86469bf8f7cd78a1bf74ffa768e494e768f7ef8d466211a86c8612f699c5c6#0": {
    "action": {
      "contents": [
        null,
        {
          "keyDeposit": 5000000
        }
      ],
      "tag": "ParameterChange"
    },
    "actionId": {
      "govActionIx": 0,
      "txId": "9b86469bf8f7cd78a1bf74ffa768e494e768f7ef8d466211a86c8612f699c5c6"
    },
    "committeeVotes": {},
    "dRepVotes": {
      "keyHash-9b3f30d0b9714f58c1904050c96f16dcb9b56a9d6f9ddc9b044f2616": "Abstain"
    },
    "deposit": 1000000000,
    "expiresAfter": 3,
    "proposedIn": 2,
    "returnAddr": {
      "credential": {
        "keyHash": "0f2395b68956ed2efff32d92e479e14ae936d472f6ae106a07800431"
      },
      "network": "Testnet"
    },
    "stakePoolVotes": {}
  }
}
```

```
+ cardano-cli conway query gov-state --testnet-magic 42
+ jq -r .enactState.curPParams.keyDeposit
5000000
```
```
cardano-cli query protocol-parameters --testnet-magic 42 | jq .stakeAddressDeposit
5000000
```

The same issue occurs with other pparams: 

```
cardano-cli conway query gov-state --testnet-magic 42 | jq -r .proposals
{
  "psGovActionStates": {
    "9c4fb59734cac7559cf1b0a7aa96cd0025db3e6e5e43e4db98a5f60e97ef968c#0": {
      "action": {
        "contents": [
          null,
          {
            "nOpt": 50
          }
        ],
        "tag": "ParameterChange"
      },
      "actionId": {
        "govActionIx": 0,
        "txId": "9c4fb59734cac7559cf1b0a7aa96cd0025db3e6e5e43e4db98a5f60e97ef968c"
      },
      "committeeVotes": {},
      "dRepVotes": {
        "keyHash-e519f14318eaa2607c5a4dbd65e4dda63a1b5f52430aeed0234d5987": "Abstain"
      },
      "deposit": 1000000000,
      "expiresAfter": 5,
      "proposedIn": 4,
      "returnAddr": {
        "credential": {
          "keyHash": "d241ef58562fbf1a4ae9412cc4012b88705b4aa9b0dbcf61f696ead8"
        },
        "network": "Testnet"
      },
      "stakePoolVotes": {}
    }
  },
  "psProposalOrder": [
    {
      "govActionIx": 0,
      "txId": "9c4fb59734cac7559cf1b0a7aa96cd0025db3e6e5e43e4db98a5f60e97ef968c"
    }
  ]
}
cardano-cli conway query gov-state --testnet-magic 42 | jq -r .proposals
{
  "psGovActionStates": {},
  "psProposalOrder": []
}
cardano-cli conway query gov-state --testnet-magic 42 | jq -r .enactState.curPParams.nOpt
50
```

cardano-node --version
cardano-node 8.6.0 - linux-x86_64 - ghc-9.2
git rev 379e4d7c95e7f9b01166922232fb39e0d10f0811

### PR DESCRIPTION
**Pull request by lehins**
# Description

Fixes #3835 

Original implementation was buggy and did not produced any groups for PParam groups, which resulted in DRep thresholds to be set to zero for PParamUpdates, yielding all PParam proposals be enacted, regardless on what DReps though about them :smile: 

One more fix included is a PParamUpdate wellformdness check that ensures empty PParams can't be proposed.  

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs [hunk 1]
```diff
@@ -493,155 +538,160 @@ conwayPParamsPairs pp =
...
-    , cppMaxTxSize = 2048
-    , cppMaxBHSize = 0
-    , cppKeyDeposit = Coin 0
-    , cppPoolDeposit = Coin 0
-    , cppEMax = EpochNo 0
-    , cppNOpt = 100
-    , cppA0 = minBound
-    , cppRho = minBound
-    , cppTau = minBound
+    { cppMinFeeA = THKD (Coin 0)
```
Comment (Soupstraw) [inline eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs:542]: Lots of redundant parentheses here

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs [hunk 2]
```diff
@@ -196,7 +196,10 @@ instance Updatable (U1 a) (U1 u) where
 instance Updatable (V1 a) (V1 u) where
   applyUpdate x _ = case x of {}
 
-instance (Updatable (a1 a) (u1 u), Updatable (a2 a) (u2 u)) => Updatable ((a1 :*: a2) a) ((u1 :*: u2) u) where
+instance
+  (Updatable (a1 a) (u1 u), Updatable (a2 a) (u2 u)) =>
+  Updatable ((a1 :*: a2) a) ((u1 :*: u2) u)
+  where
   applyUpdate (x1 :*: x2) (u1 :*: u2) = applyUpdate x1 u1 :*: applyUpdate x2 u2
```
Comment (Soupstraw) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs:204]: The Generic updating should work with `THKD` if you add an instance for `Updatable (K1 t x a) (K1 t (THKD f x u))` where the `applyUpdate` just unwraps the `THKD` and calls `applyUpdate` again

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs [hunk 3]
```diff
@@ -94,70 +166,70 @@ import Numeric.Natural (Natural)
 -- * @dRepDeposit@
 -- * @dRepActivity@
 data ConwayPParams f era = ConwayPParams
-  { cppMinFeeA :: !(HKD f Coin)
```
Comment (Soupstraw) [inline eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs:97]: I like this approach

File: libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs (hunk 2 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Core/PParams.hs:204]: I have tried it, but couldn't figure it out. My generics Kung fu isn't strong enough.

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs (hunk 3 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs:97]: Nice! :slightly_smiling_face:

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs (hunk 1 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs:542]: Thank you for pointing it out. Result of search and replace. I'll fix it

Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs:542]: Removed

File: eras/conway/impl/CHANGELOG.md [hunk 4]
```diff
@@ -1,9 +1,14 @@
...
-## 1.10.1.0
+## 1.11.0.0
 
 * Switch to using `OMap` for `ProposalsSnapshot` #3791
 * Add `VotingOnExpiredGovAction` predicate failure in `GOV` #3825
+* Rename `modifiedGroups` -> `modifiedPPGroups` and move into `ConwayEraPParams`
+* Expose `pparamsUpdateThreshold`
+* Fix [#3835](https://github.com/input-output-hk/cardano-ledger/issues/3835)
+* Rename `PParamGroup` to `PPGroup` and `GovernanceGroup` to `GovGroup`
+* Intorduce `THKD` and use it for `ConwayPParams`
```
Comment (teodanciu) [inline eras/conway/impl/CHANGELOG.md]: Little typo here, "Introduce"

File: libs/cardano-ledger-core/src/Cardano/Ledger/Ap.hs [hunk 5]
```diff
@@ -1,115 +0,0 @@
-{-# LANGUAGE GADTs #-}
```
Comment (teodanciu) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Ap.hs]: Shouldn't this removal be reflected in a version change and changelog of cardano-ledger-core, since we were exposing it from the library?

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs [hunk 6]
```diff
@@ -380,6 +416,7 @@ instance Crypto c => ConwayEraPParams (ConwayEra c) where
         isValid (/= zero) ppuPoolDepositL
       , isValid (/= zero) ppuGovActionDepositL
       , isValid (/= zero) ppuDRepDepositL
+      , ppu /= emptyPParamsUpdate
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs:420]: but I would put this in a different commit or maybe at least mention it in the commit message, in case we have to track  it down (for example for changelogs).  But it's up to you of course

File: libs/cardano-ledger-core/src/Cardano/Ledger/Ap.hs (hunk 5 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Ap.hs]: Yeah, you are right. Thank you. I'll fix that.

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs [hunk 7]
```diff
@@ -868,26 +895,158 @@ ppDRepDepositL = ppLens . hkdDRepDepositL @era @Identity
...
+    SJust p -> pp & ppL .~ p
+
+ppUpdateCostModels ::
+  AlonzoEraPParams era =>
+  PParamsUpdate era ->
+  PParams era ->
+  PParams era
+ppUpdateCostModels ppu pp =
+  case ppu ^. ppuCostModelsL of
+    SNothing -> pp
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs]: How come this pparam gets special treatment if it's empty, as opposed to other ppu lenses of type StrictMaybe?

**Review by teodanciu — APPROVED** [review]
Left a few comments and questions.  
Looks good to me.

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs (hunk 7 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs]: Good question. Here is why: #3631 and the fix #3771

File: eras/conway/impl/CHANGELOG.md (hunk 4 above)
Comment (lehins) [reply eras/conway/impl/CHANGELOG.md]: Fixed

File: libs/cardano-ledger-core/src/Cardano/Ledger/Ap.hs (hunk 5 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/Ap.hs]: I decided to instead deprecate the module and will remove it once we have bunch of other breaking changes :slightly_smiling_face:

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs (hunk 7 above)
Comment (teodanciu) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs]: Great, I see now the connection, thanks :+1:

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs (hunk 6 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs:420]: Very good point. I've put it into a separate commit
