### PR TITLE
Disallow duplicate VRF keys for pool registration

### LINKED ISSUE #5159: Disallow different pools to use the same VRF key.
This does not constitute a security risk. However, our reasoning assumes that the events of being elected in a slot are independent for different stake pools, and this is broken by duplicate VRF keys.

As explained [in this comment](https://github.com/IntersectMBO/ouroboros-consensus/issues/1075#issuecomment-3035911537), two stake pools having the same VRF key break the transitivity of the relation consensus uses to sort candidate chains (`Ord SelectView`). 

If fixed, this change should happen at a hard-fork boundary.

### PR DESCRIPTION
**Pull request by teodanciu**
# Description

Whenever we register or re-register a pool,  starting with version 11, we check that the provided VRF key is not in use by another pool. 
When we reap the pools, we also forget their VRF keys, so they become free to be used again. 
Resolves https://github.com/IntersectMBO/cardano-ledger/issues/5159

# Checklist

- [ ] Commits in meaningful sequence and with useful messages.
- [ ] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [ ] Self-reviewed the diff.

### CODE REVIEW

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs [hunk 1]
```diff
@@ -155,3 +156,8 @@ hardforkAlonzoValidatePoolRewardAccountNetID pv = pvMajor pv > natVersion @4
 -- See the Shelley Ledger Errata 17.2.
 hardforkBabbageForgoRewardPrefilter :: ProtVer -> Bool
 hardforkBabbageForgoRewardPrefilter pv = pvMajor pv > natVersion @6
+
+hardforkConwayDisallowDuplicatedVRFKeys ::
+  ProtVer ->
+  Bool
+hardforkConwayDisallowDuplicatedVRFKeys pv = pv > ProtVer (natVersion @10) 0
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs]: It is always better to reduce the type rather than create a more complex one with values that will make it work.
```suggestion
hardforkConwayDisallowDuplicatedVRFKeys pv = pvMajor pv > natVersion @10 
```
I've had the same discussion with @Soupstraw recently.

I can draw a parallel with a most common product type, namely a tuple:
```haskell
isIxLEQ10 :: (Int, String) -> Bool
isIxLEQ10 (ix, _) = ix <= 10
```
vs
```haskell
isIxLEQ10 :: (Int, String) -> Bool
isIxLEQ10 = (<= (10, ""))
```

The fact that they will always produce the same result is not a good argument in favor of using an empty string in comparison, since not only it adds computational overhead, but it also adds mental overhead when code is being read.

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs [hunk 2]
```diff
@@ -233,15 +249,37 @@ poolDelegationTransition = do
...
-              ps {psStakePools = eval (psStakePools ⨃ singleton ppId (mkStakePoolState poolParams))}
-        else do
+              ps
+                & psStakePoolsL %~ Map.insert ppId (mkStakePoolState poolParams)
+                & psVRFKeyHashesL %~ Set.insert ppVrf
+        Just _ -> do
+          -- re-register Pool
+
+          -- If a pool re-registers with a fresh VRF, we have to add it to the list,
+          -- but also remove th  potential VRF stored in previous re-registration within the same epoch,
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs]:
```suggestion
          -- but also remove the previous VRFKeyHash potentially stored in previous re-registration within the same epoch,
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs [hunk 3]
```diff
@@ -233,15 +249,37 @@ poolDelegationTransition = do
...
+          -- which we can retrieve from futureStakePools. We first delete and then insert the new one,
+          -- so in case they are the same, it will still end up in the set.
+          let updateVRFs
+                | hasMatchingVRF = id
+                | otherwise = psVRFKeyHashesL %~ (Set.insert ppVrf . withoutFutureVrf)
+                where
+                  withoutFutureVrf s = maybe s (`Set.delete` s) futureVrf
+                  futureVrf = (^. spsVrfL) <$> Map.lookup ppId psFutureStakePools
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs]: I think this would be slightly simpler to follow:
```suggestion
          -- which we can retrieve from futureStakePools.
          let updateFutureVRFKeyHash
                | hardforkConwayDisallowDuplicatedVRFKeys pv =
                  case Map.lookup ppId psFutureStakePools of
                    Nothing -> Set.insert ppVrf
                    Just futureStakePoolState
                      | spsVrf futureStakePoolState /= ppVrf ->
                          Set.insert ppVrf . Set.delete (spsVrf futureStakePoolState)
                      | otherwise -> id
                | otherwise = id
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs [hunk 4]
```diff
@@ -254,12 +292,11 @@ poolDelegationTransition = do
...
             ps
-              { psFutureStakePools =
-                  eval (psFutureStakePools ⨃ singleton ppId (mkStakePoolState poolParams))
-              , psRetiring = eval (setSingleton ppId ⋪ psRetiring)
-              }
-    RetirePool hk e -> do
-      eval (hk ∈ dom psStakePools) ?! StakePoolNotRegisteredOnKeyPOOL hk
+              & psFutureStakePoolsL %~ Map.insert ppId (mkStakePoolState poolParams)
+              & psRetiringL %~ Map.delete ppId
+              & updateVRFs
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs]: Due to my comment above
```suggestion
              & psVRFKeyHashesL %~ updateFutureVRFKeyHash
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/PoolReap.hs [hunk 5]
```diff
@@ -126,23 +126,54 @@ instance
 
 poolReapTransition :: forall era. EraCertState era => TransitionRule (ShelleyPOOLREAP era)
 poolReapTransition = do
-  TRC (_, PoolreapState us a cs, e) <- judgmentContext
-
+  TRC (_, PoolreapState us a cs0, e) <- judgmentContext
   let
-    ps = cs ^. certPStateL
+    ps0 = cs0 ^. certPStateL
+    -- find the set of VRF keys that are no longer relevant, since they have been overwritten
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/PoolReap.hs]:
```suggestion
    -- find the set of VRF key hashes that are no longer relevant, since they have been overwritten
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/PoolReap.hs [hunk 6]
```diff
@@ -126,23 +126,54 @@ instance
...
+    -- via pool re-registration
+    danglingVrfs =
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/PoolReap.hs]:
```suggestion
    danglingVrfKeyHashes =
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/PoolReap.hs [hunk 7]
```diff
@@ -183,10 +214,11 @@ poolReapTransition = do
...
           & certDStateL . accountsL
             %~ removeStakePoolDelegations retired . addToBalanceAccounts refunds
-          & certPStateL . psStakePoolsL %~ (eval . (retired ⋪))
-          & certPStateL . psFutureStakePoolsL %~ (eval . (retired ⋪))
-          & certPStateL . psRetiringL %~ (eval . (retired ⋪))
+          & certPStateL . psStakePoolsL %~ (`Map.withoutKeys` retired)
+          & certPStateL . psRetiringL %~ (`Map.withoutKeys` retired)
           & certPStateL . psDepositsCompactL .~ remainingDeposits
+          & certPStateL . psVRFKeyHashesL
+            %~ (\s -> (s `Set.difference` retiredVRFs) `Set.difference` danglingVrfs)
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/PoolReap.hs]:
```suggestion
            %~ ((`Set.difference` retiredVRFs) . (`Set.difference` danglingVrfs))
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs [hunk 8]
```diff
@@ -237,6 +239,8 @@ data PState era = PState
   -- ^ A map of retiring stake pools to the epoch when they retire.
   , psDeposits :: !(Map (KeyHash 'StakePool) (CompactForm Coin))
   -- ^ A map of the deposits for each pool
+  , psVRFKeyHashes :: !(Set (VRFVerKeyHash 'StakePoolVRF))
+  -- ^ VRF key hashes that have been registered via PoolParams
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs]: It will be better to add this field to the beginning of the type, since then we will be able to use it for interning VRFKeyHashes and their duplication in memory when decoding.

File: libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs [hunk 9]
```diff
@@ -246,17 +250,18 @@ instance NoThunks (PState era)
...
 instance DecShareCBOR (PState era) where
   type Share (PState era) = Interns (KeyHash 'StakePool)
-  decSharePlusCBOR = decodeRecordNamedT "PState" (const 4) $ do
+  decSharePlusCBOR = decodeRecordNamedT "PState" (const 5) $ do
     psStakePools <- decSharePlusLensCBOR (toMemptyLens _1 id)
     psFutureStakePools <- decSharePlusLensCBOR (toMemptyLens _1 id)
     psRetiring <- decSharePlusLensCBOR (toMemptyLens _1 id)
     psDeposits <- decSharePlusLensCBOR (toMemptyLens _1 id)
-    pure PState {psStakePools, psFutureStakePools, psRetiring, psDeposits}
+    psVRFKeyHashes <- lift decCBOR
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs]: As mentioned in my other comment, it will be better to make this field to be the first one that gets decoded. Also, could you please create a ticket that tracks implementation of sharing VRFKeyHashe. This part we don't have to do in this PR.

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs [hunk 10]
```diff
@@ -233,15 +249,37 @@ poolDelegationTransition = do
...
+        Nothing -> do
           -- register new, Pool-Reg
           tellEvent $ RegisterPool ppId
           pure $
             payPoolDeposit ppId pp $
-              ps {psStakePools = eval (psStakePools ⨃ singleton ppId (mkStakePoolState poolParams))}
-        else do
+              ps
+                & psStakePoolsL %~ Map.insert ppId (mkStakePoolState poolParams)
+                & psVRFKeyHashesL %~ Set.insert ppVrf
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs]: We need to avoid adding anything to `psVRFKeyHashes` until the next hard fork
```suggestion
                & psVRFKeyHashesL %~ 
                  if hardforkConwayDisallowDuplicatedVRFKeys pv 
                  then Set.insert ppVrf
                  else id
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs [hunk 11]
```diff
@@ -233,15 +249,37 @@ poolDelegationTransition = do
...
-        then do
+      let mbStakePoolState = Map.lookup ppId psStakePools
+      let hasMatchingVRF = ((^. spsVrfL) <$> mbStakePoolState) == Just ppVrf
+      when (hardforkConwayDisallowDuplicatedVRFKeys pv) $ do
+        -- if the VRF key is not associated with this pool (either because the pool is not registered
+        -- or because the VRF key is different from the one registered for this pool),
+        -- then we check that this VRF key is not already in use
+        hasMatchingVRF
+          || Set.notMember ppVrf psVRFKeyHashes
+            ?! VRFKeyHashAlreadyRegistered ppId ppVrf
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs]: As we've talked during the meeting, it will be cleaner if this can be split into two cases:
1. register new pool
2. update existing pool

**Review by lehins — CHANGES_REQUESTED** [review]
This is an awesome PR. I love all the additions to the test suite.

However, it is missing one critical part. Once we hard fork into protocol version 11, the contents of `psVRFKeyHashes` will be empty, which will totally screw up the whole logic in this PR.
We need to also adjust the `HARDFORK` rule to populate that field with data from all of the `psStakePools` and `psFutureStakePools` on the hard fork boundary.

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs (hunk 1 above)
Comment (Soupstraw) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs]: @lehins I get the argument about performance, but not the argument about "making up" the minor version. 

For example, would you also say that `truncate x > 1` is more readable than `x > 1.0` and that I'm "making up" the zero in the decimal part?

File: libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs (hunk 8 above)
Comment (teodanciu) [reply libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs]: Thanks, didn't think of this aspect!

File: libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs (hunk 9 above)
Comment (teodanciu) [reply libs/cardano-ledger-core/src/Cardano/Ledger/State/CertState.hs]: Done: https://github.com/IntersectMBO/cardano-ledger/issues/5239

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs [hunk 12]
```diff
@@ -67,31 +67,43 @@ hardforkTransition = do
...
+        & certDStateL . accountsL . accountsMapL .~ accountsWithoutUnknownDRepDelegations
+        -- Populate DRep delegations with delegatees
+        & certVStateL . vsDRepsL .~ dRepsWithDelegations
+
+populateVRFKeyHashes :: PState era -> PState era
+populateVRFKeyHashes pState =
+  let allVRFKeyHashes =
+        (^. spsVrfL)
+          <$> Map.elems (pState ^. psStakePoolsL)
+            <> Map.elems (pState ^. psFutureStakePoolsL)
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs:108]: I think it's not strictly necessary to also add the `psFutureStakePoolsL` , since this rule is called after PoolReap, which empties these future pools. But maybe better to still have it here, just in case anything changes with that order or logic.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs [hunk 13]
```diff
@@ -67,31 +67,43 @@ hardforkTransition = do
...
-             in certState
-                  -- Remove dangling delegations to non-existent DReps:
-                  & certDStateL . accountsL . accountsMapL .~ accountsWithoutUnknownDRepDelegations
-                  -- Populate DRep delegations with delegatees
-                  & certVStateL . vsDRepsL .~ dRepsWithDelegations
-    else pure epochState
+  let update
+        | pvMajor newPv == natVersion @10 =
+            esLStateL . lsCertStateL %~ updateDRepDelegations
+        | pvMajor newPv == natVersion @11 =
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs:73]: If this doesn't go in for the node 11 release, then I suppose this will have to change!

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs (hunk 1 above)
Comment (lehins) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs]: `truncate x > 1` is actually more accurate, since then you are working on integral type instead of floating point. But without type annotation I don't even know if it is a rational of Float or Double.
In any case, the particular argument I had was related specifically to product types, which might not necessarily apply to numeric type, which would need to be assessed on a specific example.

This is my general suggestion in software engineering, which is applicable to many things in life: unless necessary, it is usually better to reduce a problem as much as possible, instead of making it more complicated, which is what this approach does: `pv > ProtVer (natVersion @10) 0`. By reducing complexity you not only making the solution  easier for others to understand, but also you also make it easier to maintain.
If you needed to buy a door handle, you wound't also go into another store to buy the same kind of door you have at home, just to check whether it fits or not, right? Pretty dumb analogy, but hopefully it will convey my point.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs (hunk 13 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs:73]: node 11 release has not even been discussed yet. We are still working on 10.x releases.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs [hunk 14]
```diff
@@ -67,31 +67,43 @@ hardforkTransition = do
...
+   in certState
+        -- Remove dangling delegations to non-existent DReps:
+        & certDStateL . accountsL . accountsMapL .~ accountsWithoutUnknownDRepDelegations
+        -- Populate DRep delegations with delegatees
+        & certVStateL . vsDRepsL .~ dRepsWithDelegations
+
+populateVRFKeyHashes :: PState era -> PState era
+populateVRFKeyHashes pState =
+  let allVRFKeyHashes =
+        (^. spsVrfL)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs]: Any reason why you choosing to use lenses in favor of regular field accessor functions?
```suggestion
        spsVrf
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs (hunk 12 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs:108]: :100: agree!

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/HardForkSpec.hs [hunk 15]
```diff
@@ -0,0 +1,78 @@
...
+import Test.Cardano.Ledger.Imp.Common
+
+spec ::
+  forall era.
+  ConwayEraImp era => SpecWith (ImpInit (LedgerSpec era))
+spec = do
+  it "VRF Keyhashes get populated at v11 HardFork" $ do
+    pv <- getProtVer
+    -- Since we're testing the HardFork to 11, the test only makes sense for protocol version 10
+    when (pvMajor pv == natVersion @10) $ do
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/HardForkSpec.hs]: :wink: 
```suggestion
    -- Since we're testing the HardFork to 11, the test only makes sense for protocol version 10
    whenMajorVersion @10 $ do
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/HardForkSpec.hs [hunk 16]
```diff
@@ -0,0 +1,78 @@
...
+        mkBasicTx mkBasicTxBody
+          & bodyTxL . certsTxBodyL .~ [RegPoolTxCert $ pps & ppVrfL .~ vrf]
+    retireStakePool kh retirementInterval = do
+      curEpochNo <- getsNES nesELL
+      let retirement = addEpochInterval curEpochNo retirementInterval
+      submitTx_ $
+        mkBasicTx mkBasicTxBody
+          & bodyTxL . certsTxBodyL .~ [RetirePoolTxCert kh retirement]
+    expectVRFs vrfs =
+      (^. psVRFKeyHashesL) <$> getPState `shouldReturn` Set.fromList vrfs
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/HardForkSpec.hs]: Ditto
```suggestion
      psVRFKeyHashes <$> getPState `shouldReturn` Set.fromList vrfs
```

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs [hunk 17]
```diff
@@ -232,15 +249,38 @@ poolDelegationTransition = do
               { mismatchSupplied = ppCost
               , mismatchExpected = minPoolCost
               }
-
-      if not (Map.member ppId psStakePools)
-        then do
-          -- register new, Pool-Reg
+      let mbStakePoolState = Map.lookup ppId psStakePools
+      case mbStakePoolState of
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Pool.hs]: let binding is superfluous
```suggestion
      case Map.lookup ppId psStakePools of
```

**Review by lehins — APPROVED** [review]
This is a beautiful piece of work!
Thank you!

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs (hunk 13 above)
Comment (teodanciu) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs:73]: Oh! 🙈  Thanks!

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs (hunk 14 above)
Comment (teodanciu) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs]: Good point, no reason! Thank you

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs (hunk 1 above)
Comment (teodanciu) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/Era.hs]: Thanks both for the interesting discussion, I will resolve the comment so i can merge the PR - we can discuss it further on Friday if we want!
