### PR TITLE
Conway:DELEG: Predfailures for deposits & refunds

### LINKED ISSUE #4655: Improve `DELEG` predicate failures
DELEG rule contains a predicate failure `IncorrectDepositDELEG` that doesn't report enough information and is overused. We need to add two new predicate failures that will not only report the expected value using the `Mismatch` type from #4649, but will also report different predicate for mismatched deposit vs refund. This has to be done only at protocol version ~10~ ``, so branching on `bootstrapPhase`, in order not to break Node-To-Client protocol.

### PR DESCRIPTION
**Pull request by aniketd**
# Description

- Add `hardforkConwayDELEGIncorrectDepositsAndRefunds` for protocol 11 onwards, to `Conway.Era`.
- Add `DepositIncorrectDELEG` and `RefundIncorrectDELEG` to `ConwayDelegPredFailure`.

Closes #4655 

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [x] Tests added or updated when needed.
- [x] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] ~~Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).~~
- [ ] ~~Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).~~
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs [hunk 1]
```diff
@@ -20,12 +20,22 @@ module Cardano.Ledger.Conway.Rules.Deleg (
   ConwayDelegPredFailure (..),
   ConwayDelegEnv (..),
   processDelegation,
+  -- For testing only
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs]: I find this comment confusing - these functions are actually used in this rule and it's ok to use them in another era, for example, no?

File: eras/conway/impl/src/Cardano/Ledger/Conway/Era.hs [hunk 2]
```diff
@@ -182,3 +183,7 @@ hardforkConwayBootstrapPhase pv = pvMajor pv == natVersion @9
 -- members to submit votes.
 hardforkConwayDisallowUnelectedCommitteeFromVoting :: ProtVer -> Bool
 hardforkConwayDisallowUnelectedCommitteeFromVoting pv = pvMajor pv > natVersion @10
+
+-- | Starting with protocol version 11, we report incorrect deposit and refunds better
+hardforkConwayDELEGIncorrectDepositsAndRefunds :: ProtVer -> Bool
+hardforkConwayDELEGIncorrectDepositsAndRefunds pv = pvMajor pv > natVersion @10
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Era.hs:189]: From what I see in the ticket, this change should be done for version 10 (so the branching would be done on the bootstrap phase?), unless I'm misunderstanding

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/DelegSpec.hs [hunk 3]
```diff
@@ -108,7 +109,7 @@ spec = do
               & bodyTxL . certsTxBodyL
                 .~ [RegDepositTxCert (KeyHashObj kh) wrongDeposit]
           )
-          [injectFailure $ IncorrectDepositDELEG wrongDeposit]
+          [injectFailure $ incorrectDeposit pv wrongDeposit expectedDeposit]
```
Comment (teodanciu) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/DelegSpec.hs]: In my opinion, it would be better to check the protocol explicitly here instead of reusing the function from test, so that any (perhaps accidental) change is reflected in a test failure. If you need to use v10 switch, then there is also `whenPostBootstrap`  function you could use. But that's just a preference, it probably doesn't make much difference.

**Review by teodanciu — COMMENTED** [review]
Not sure if the protocol version check is correct, seems like it might need to be >= 10 instead of > 10 ?

File: eras/conway/impl/src/Cardano/Ledger/Conway/Era.hs (hunk 2 above)
Comment (teodanciu) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Era.hs:189]: My mistake, the ticket was outdated, closing this comment.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs (hunk 1 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs]: @aniketd I totally get that you want to reduce duplication, however this is a wrong place to do this. These functions should not exist at all and they should be inlined where they are used.
If you don't do this, you are testing the logic with the same functions. In other words if any of these two function have a bug, tests will pass too, because the bug will also be present in the test. Try to stick to the same patterns that we already use in imp tests.

**Review by lehins — CHANGES_REQUESTED** [review]
Before reading @teodanciu's comment I ended up writing a very similar comment, which serves as a good indicator that the approach you took with helper functions is an antipattern.
Other than that PR looks good.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs [hunk 4]
```diff
@@ -123,6 +140,10 @@ instance Era era => EncCBOR (ConwayDelegPredFailure era) where
         Sum (DelegateeDRepNotRegisteredDELEG @era) 5 !> To delegatee
       DelegateeStakePoolNotRegisteredDELEG delegatee ->
         Sum (DelegateeStakePoolNotRegisteredDELEG @era) 6 !> To delegatee
+      DepositIncorrectDELEG mm ->
+        Sum (DepositIncorrectDELEG @era) 7 !> ToGroup mm
+      RefundIncorrectDELEG mm ->
+        Sum (RefundIncorrectDELEG @era) 8 !> ToGroup mm
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs]: After submitting my review I noticed one more problem. We only used group encoding for backwards compatibility. These are new predicate failures that do not have such problem and should not be using group encoding
```suggestion
        Sum (DepositIncorrectDELEG @era) 7 !> To mm
      RefundIncorrectDELEG mm ->
        Sum (RefundIncorrectDELEG @era) 8 !> To mm
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs [hunk 5]
```diff
@@ -132,6 +153,8 @@ instance Era era => DecCBOR (ConwayDelegPredFailure era) where
     4 -> SumD StakeKeyHasNonZeroRewardAccountBalanceDELEG <! From
     5 -> SumD DelegateeDRepNotRegisteredDELEG <! From
     6 -> SumD DelegateeStakePoolNotRegisteredDELEG <! From
+    7 -> SumD DepositIncorrectDELEG <! FromGroup
+    8 -> SumD RefundIncorrectDELEG <! FromGroup
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs]:
```suggestion
    7 -> SumD DepositIncorrectDELEG <! From
    8 -> SumD RefundIncorrectDELEG <! From
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs (hunk 1 above)
Comment (aniketd) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs]: I have removed these definitions entirely :+1: Thanks!

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/DelegSpec.hs (hunk 3 above)
Comment (aniketd) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/DelegSpec.hs]: Yes! Thanks!

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs (hunk 4 above)
Comment (aniketd) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs]: Yes! I had completely forgotten about it! Thank you!

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs (hunk 5 above)
Comment (aniketd) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs]: Thanks! :sweat_smile:

**Review by lehins — APPROVED** [review]
Beautiful! Thank you!
