### PR TITLE
Fix Drep stake distribution

### LINKED ISSUE #4107: DRep stake distribution should also include rewards
In #4097 , there is a pending test that demonstrates that rewards are not being considered for DRep stake distribution. We need to make the `active voting stake` for DReps also consider rewards, just like it is done for Stake Pools.

### Note

In a preliminary look-around, it was found that `Conway.Governance.accumDRepDistr` is the function that could also add the rewards from the available `UMap`, though it didn't seem to received the updated `UMap` within 2 epochs. This needs to be investigated further.

Please feel free to use these patches as necessary. [1](https://github.com/IntersectMBO/cardano-ledger/blob/d48f5e05efb61fde7d0b96009e4598f8b04b616c/eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs#L902), [2](https://github.com/IntersectMBO/cardano-ledger/blob/d48f5e05efb61fde7d0b96009e4598f8b04b616c/eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs#L927), [3](https://github.com/IntersectMBO/cardano-ledger/blob/d48f5e05efb61fde7d0b96009e4598f8b04b616c/eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs#L982), [4](https://github.com/IntersectMBO/cardano-ledger/blob/d48f5e05efb61fde7d0b96009e4598f8b04b616c/eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs#L1059). They also refactor the use of `accumDRepDistr` to use `computeDrepDistr` at multiple call sites.

### PR DESCRIPTION
**Pull request by lehins**
# Description

Fixes #4107 

Adds rewards to stake delegated to DReps

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs [hunk 1]
```diff
@@ -888,7 +889,8 @@ computeDrepDistr ::
   Map (Credential 'DRepRole c) (DRepState c) ->
   Map (Credential 'Staking c) (CompactForm Coin) ->
   Map (DRep c) (CompactForm Coin)
-computeDrepDistr um regDreps stakeDistr = Map.foldlWithKey' (accumDRepDistr um regDreps) Map.empty stakeDistr
+computeDrepDistr um regDreps stakeDistr =
+  Map.foldlWithKey' (accumDRepDistr um regDreps) Map.empty stakeDistr
```
Comment (aniketd) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs:902]: I was wondering if other call sites in the same module that use `Map.foldlWithKey' (accumDRepDistr um regDreps) Map.empty stakeDistr` could also just call `computeDrepDistr`, whether that will be to our benefit.

**Review by aniketd — APPROVED** [review]
Awesome! :raised_hands:

File: eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs (hunk 1 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs:902]: There are no other callsites in the module that use :wink: 
```haskell
Map.foldlWithKey' (accumDRepDistr um regDreps) Map.empty stakeDistr
```
