### PR TITLE
Remove `EnactState` from `ConwayGovState`

### LINKED ISSUE #3998: Stop storing EnactState in the ledger state
We are wrongfully storing temporary variables from `EnactState` in the ledger state: `ensTreasury`, `ensWithdrawals`, `ensPrevGovActionIds`.

They have confused people on multiple occasions and I am afraid can lead to bugs in the future. We need to retain only the relevant values from the enact state. This will require proper initialization of the EnactState during DRep pulser initialization and restoring the fields from the Enactstate once the pulser is done

This is the change that is needed to the `ConwayGovState`:
```diff
-  , cgEnactState :: !(EnactState era)
+  , cgCommittee :: !(StrictMaybe (Committee era))
+  , cgConstitution :: !(Constitution era)
+  , cgCurPParams :: !(PParams era)
+  , cgPrevPParams :: !(PParams era)
```

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR removes the `EnactState` field from `ConwayGovState`. The fields that have to be stored in the state are copied over to the `ConwayGovState`.

Since we're not storing the whole enact state in the ledger state any more, we don't have to check the invariants in the `EPOCH` rule.

resolves #3998

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs [hunk 1]
```diff
@@ -501,39 +509,68 @@ toRatifyStatePairs cg@(RatifyState _ _ _ _) =
...
+  , cgsDRepPulsingState :: !(DRepPulsingState era)
+  -- ^ The 'cgsDRepPulsingState' field is a pulser that incrementally computes the stake distribution of the DReps
   --   over the Epoch following the close of voting at end of the previous Epoch. It assembles this with some of
   --   its other internal components into a (RatifyEnv era) when it completes, and then calls the RATIFY rule
   --   and eventually returns the updated RatifyState. The pulser is created at the Epoch boundary, but does
   --   no work until it is pulsed in the 'NEWEPOCH' rule, whenever the system is NOT at the epoch boundary.
+  , cgsCommittee :: !(StrictMaybe (Committee era))
+  , cgsConstitution :: !(Constitution era)
+  , cgsCurPParams :: !(PParams era)
+  , cgsPrevPParams :: !(PParams era)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs]: Could you please put these four fields before the `cgsDRepPulsingState`? Make sure to adjust the `EncCBOR` instance too.

This will help later with implementing sharing of committee credentials when deserializing.

I know it is a bit pedantic, but, it is a very unique field, I'd like to keep it separated at least a little bit from others, so keeping it last will help with that.

I can make this change at some point later if you'd rather not deal with it now.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs [hunk 2]
```diff
@@ -308,10 +289,14 @@ epochTransition = do
...
+    -- Apply the values from the computed EnactState to the GovState
     govState1 =
       govState0
-        & cgProposalsL .~ newProposals
-        & cgEnactStateL .~ (newEnactState & ensPrevPParamsL .~ curPParams)
+        & cgsProposalsL .~ newProposals
+        & cgsPrevPParamsL .~ curPParams
+        & cgsCommitteeL .~ ensCommittee
+        & cgsConstitutionL .~ ensConstitution
+        & cgsCurPParamsL .~ ensCurPParams
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs]: Just so it is easier to see how pparams rotation happens
```suggestion
        & cgsCommitteeL .~ ensCommittee
        & cgsConstitutionL .~ ensConstitution
        & cgsCurPParamsL .~ ensCurPParams
        & cgsPrevPParamsL .~ curPParams
```

**Review by lehins — APPROVED** [review]
This is great. Exactly what we needed

Thank you.

**Review by aniketd — APPROVED** [review]
Grand! :raised_hands:
