### PR TITLE
Fix `ToJSON` instance of `BoundedRatio` to avoid precision loss

### LINKED ISSUE #4026: Fix `ToJSON` instance for `BoundedRatio` to not loose precision
Current problem is that rational numbers like `2/3` are encoded into json with loss of precision like so: `0.6666666666666666666`. So, natural fix would be to encode `BoundedRatio` as:
```json
{ "numerator": 2
, "denominator": 3
}
```
However, we can't do this blindly due to backwards compatibility. The best course of action is to support both formats: decimal and rational. Especially considering that `FromJSON` already supports that.

So, the fix should involve detecting loss of precision with the help of [`fromRationalRepetendLimited`](https://hackage.haskell.org/package/scientific-0.3.7.0/docs/Data-Scientific.html#v:fromRationalRepetendLimited)
and falling back to `ToJSON` instance for `Rational`, when encoding in decimal form is not possible without loss of precision.

Property tests for this change should go into: `Test.Cardano.Ledger.BaseTypesSpec`

### PR DESCRIPTION
**Pull request by Lucsanszky**
# Description
Resolves #4026 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: libs/cardano-ledger-core/test/Test/Cardano/Ledger/BaseTypesSpec.hs [hunk 1]
```diff
@@ -56,29 +55,16 @@ boundedRationalTests badJSONValues = do
...
-      prop "ToJSON/FromJSON roundtrip up to an epsilon" $
+      prop "ToJSON/FromJSON roundtrip" $
         forAll genValid $ \(br :: a) ->
           within 500000 $
-            case eitherDecode (encode br) of
+            case boundedFromJSON (encode br) of
               Left err -> error err
-              Right (br' :: a) ->
-                epsilonMaybeEq 1e-18 (unboundRational br) (unboundRational br')
-      prop "Roundtrip to Scientific and back up to an epsilon" $
```
Comment (Lucsanszky) [inline libs/cardano-ledger-core/test/Test/Cardano/Ledger/BaseTypesSpec.hs:66]: I removed these tests since I believe my changes make them obsolete.

File: libs/cardano-ledger-core/test/Test/Cardano/Ledger/BaseTypesSpec.hs [hunk 2]
```diff
@@ -17,7 +17,6 @@ import Data.Typeable
 import Test.Cardano.Ledger.Binary.RoundTrip (roundTripCborExpectation)
 import Test.Cardano.Ledger.Common
 import Test.Cardano.Ledger.Core.Arbitrary ()
-import Test.Cardano.Ledger.Core.Utils (epsilonMaybeEq)
```
Comment (Lucsanszky) [inline libs/cardano-ledger-core/test/Test/Cardano/Ledger/BaseTypesSpec.hs:20]: `epsilonMaybeEq` was only used here, so we might want to remove the function itself as well. Unless we think that it might be useful again at some point.

File: libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs [hunk 3]
```diff
@@ -328,53 +335,42 @@ instance
...
 fromScientificBoundedRatioWord64 (normalize -> sci)
-  | coeff < 0 = failWith "negative"
+  | coeff < 0 = failWith "negative" sci
   | exp10 <= 0 = do
-      when (exp10 < -19) $ failWith "too precise"
+      when (exp10 < -19) $ failWith "too precise" sci
       fromRationalEither (coeff % (10 ^ negate exp10))
   | otherwise = do
-      when (19 < exp10) $ failWith "too big"
+      when (19 < exp10) $ failWith "too big" sci
```
Comment (Lucsanszky) [inline libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: `19` is the number of decimal digits for 64 bit values. I think it might be a good idea to consider removing this magic number by introducing a constant. Something along the lines of `numberOfDecimals64 = 19`. Would that be desirable? If so, I can do it here and now or later as part of some refactoring.

**Review by Lucsanszky — COMMENTED** [review]
This is now ready for review. Added some comments to consider.

File: libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs [hunk 4]
```diff
@@ -244,6 +245,12 @@ instance Integral a => Ord (BoundedRatio b a) where
 promoteRatio :: Integral a => Ratio a -> Rational
 promoteRatio r = toInteger (numerator r) % toInteger (denominator r)
 
+toRationalJSON :: Rational -> Value
+toRationalJSON r =
+  case fromRationalRepetendLimited 20 r of
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: I believe we need to use `19` here as well, otherwise there could be issues with roundtripping
```suggestion
  case fromRationalRepetendLimited 19 r of
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs (hunk 3 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: I totally agree with you. Let's create a top level binding with a bit of explanation what this number means. I think doing it in this PR will be good.

File: libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs [hunk 5]
```diff
@@ -328,53 +335,42 @@ instance
...
-    failWith :: String -> Either String a
-    failWith msg = Left $ "Value is " ++ msg ++ ": " ++ show sci
-    fromRationalEither =
-      maybe (failWith "outside of bounds") Right . fromRationalBoundedRatio
+
+fromRationalEither :: Bounded (BoundedRatio b Word64) => Rational -> Either String (BoundedRatio b Word64)
+fromRationalEither r = maybe (failWith "outside of bounds" r) Right $ boundRational r
+
+failWith :: Show a => String -> a -> Either String b
+failWith msg (show -> val) = Left $ "Value is " <> msg <> ": " <> val
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: I'd suggest using `ViewPatterns` only in places where they are really useful. Some people get triggered about their usage. (none on our team, from what I know, but it does happen in Haskell community)
```suggestion
failWith msg val = Left $ "Value is " <> msg <> ": " <> show val
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/Plutus/ExUnits.hs [hunk 6]
```diff
@@ -32,6 +32,7 @@ import Cardano.Ledger.BaseTypes (
   BoundedRational (unboundRational),
   NonNegativeInterval,
   boundRational,
+  toRationalJSON,
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Plutus/ExUnits.hs]: We no longer need to import it here, because this comment is no longer true:
https://github.com/IntersectMBO/cardano-ledger/blob/21871e9651d8d3fad3383647b4f157f1612ae685/libs/cardano-ledger-core/src/Cardano/Ledger/Plutus/ExUnits.hs#L172

So, we can fix the ToJSON/FromJSON instances for `Prices`, by relying on the underlying instance of `NonNegativeInterval`
```suggestion
```

File: libs/cardano-ledger-core/test/Test/Cardano/Ledger/BaseTypesSpec.hs (hunk 2 above)
Comment (lehins) [reply libs/cardano-ledger-core/test/Test/Cardano/Ledger/BaseTypesSpec.hs:20]: I think we can remove it. If we ever need it again, we can always bring it back. I have a variant of it in a couple of projects of mine.
I doubt though that we will need it, since it is usually only useful for testing floating point numbers and other computation related to rounding, which is unlikely to be useful in ledger again.

**Review by lehins — CHANGES_REQUESTED** [review]
Very nice!

I left one suggestion that I didn't even think of until reviewing this PR. We can now simplify JSON instances for `Prices`.

Once that's done we can merge the PR

File: libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs [hunk 7]
```diff
@@ -176,6 +177,9 @@ import NoThunks.Class (NoThunks (..))
 import Numeric.Natural (Natural)
 import Quiet (Quiet (Quiet))
 
+maxScale :: Int
+maxScale = 19
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: We should not export this biding from the module and it should have a better name, along the line of:
(Edit: tests can define their own binding like that)
```suggestion
numFullDigitsWord64 :: Int
numFullDigitsWord64 = 19
```

Comment (Lucsanszky) [reply libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: Renamed it. The "full digits" part sounds strange to me but including `Word64` in the name is good. `maxScale` could indeed be a bit misleading without context.

Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: `maxBound` for `Word64` has 20 digits:
```haskell
ghci> length (show (maxBound :: Word))
20
```

But with regards to representing decimal numbers it has only 19 digits available:
```
ghci> (2 * 10 ^ 19) > toInteger (maxBound :: Word)
True
ghci> (1 * 10 ^ 19) > toInteger (maxBound :: Word)
False
```
For example, the smallest decimal number you can represent with `Ratio Word64` is this number that has 19 decimal places (despite that numerator has 20 digits :grin:):
```
ghci> 0.0000000000000000001 :: Ratio Word
1 % 10000000000000000000
ghci> 0.00000000000000000001 :: Ratio Word
1 % 7766279631452241920
```

With all this information at your disposal, if you have a better name for the binding, please go for it.

Comment (Lucsanszky) [reply libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: Yes, this is what I added to the commit body here: be55cbc14d2fc61970b711d77eb857b70e8c896b . Although not in such detail. :grin:  This is why I picked `maxScale` since you refer to that parameter as scale too in `safe-decimal`: https://hackage.haskell.org/package/safe-decimal-0.2.1.0/docs/Numeric-Decimal.html

How about `maxScaleWord64`? Or `maxDecimalsWord64` since mathematics sometimes refer to the decimal places after the decimal point as decimals? I think this latter one is more well-known.

Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs]: `maxDecimalsWord64` sounds ideal!

**Review by lehins — APPROVED** [review]
Perfect!
