### PR TITLE
Set `maxTxSize` relative to generated tx in Utxo conformance tests

### LINKED ISSUE #4685: Conformance test failure on CI
Failure comes from this run: https://github.com/IntersectMBO/cardano-ledger/actions/runs/11333975035/job/31521695424?pr=4684
Here is some of the output necessary to reproduce the failure.
```
4-10-14T21:11:33.7993470Z        [0;93m[[0m[0;94mTest.Cardano.Ledger.Conformance.ExecSpecRule.Conway.Base[0m[0;93m:[0m[0;95m199[0m[0;93m][0m
2024-10-14T21:11:33.7994018Z         └[0;93m[[0m[0;94mTest.Cardano.Ledger.Conformance.ExecSpecRule.Core[0m[0;93m:[0m[0;95m429[0m[0;93m][0m
2024-10-14T21:11:33.7994469Z           └[0;93m[[0m[0;94mTest.Cardano.Ledger.Conformance.Spec.Conway[0m[0;93m:[0m[0;95m35[0m[0;93m][0m
2024-10-14T21:11:33.7994614Z          Impl:
2024-10-14T21:11:33.7994703Z          Consumed:   	
2024-10-14T21:11:33.7994814Z          	Inputs:     	Coin 1785759
2024-10-14T21:11:33.7994911Z          	Withdrawals 	Coin 0
2024-10-14T21:11:33.7995012Z          	Total:      	Coin 1785759
2024-10-14T21:11:33.7995092Z        
2024-10-14T21:11:33.7995181Z          Produced:  	
2024-10-14T21:11:33.7995282Z          	Outputs:   	Coin 101
2024-10-14T21:11:33.7995377Z          	Donations: 	Coin 0
2024-10-14T21:11:33.7995474Z          	Deposits:  	Coin 5
2024-10-14T21:11:33.7995570Z          	Fees:      	Coin 1785653
2024-10-14T21:11:33.7995722Z          	Total:     	Coin 1785759
2024-10-14T21:11:33.7995807Z        
2024-10-14T21:11:33.7995887Z        
2024-10-14T21:11:33.7995974Z          Spec:
2024-10-14T21:11:33.7996056Z          Consumed:
2024-10-14T21:11:33.7996151Z          	Inputs:      	1785759
2024-10-14T21:11:33.7996244Z          	Mint:        	0
2024-10-14T21:11:33.7996338Z          	Refunds:     	0
2024-10-14T21:11:33.7996434Z          	Withdrawals: 	0
2024-10-14T21:11:33.7996525Z          	Total:       	1785759
2024-10-14T21:11:33.7996609Z          Produced:
2024-10-14T21:11:33.7996708Z          	Outputs:     	101
2024-10-14T21:11:33.7996915Z          	Donations:   	0
2024-10-14T21:11:33.7997011Z          	Deposits:    	5
2024-10-14T21:11:33.7997100Z          	Fees:        	1785653
2024-10-14T21:11:33.7997189Z          	Total:       	1785759
2024-10-14T21:11:33.7997684Z        [0;93m[[0m[0;94mTest.Cardano.Ledger.Conformance.ExecSpecRule.Core[0m[0;93m:[0m[0;95m285[0m[0;93m][0m
2024-10-14T21:11:33.7998208Z         └[0;93m[[0m[0;94mTest.Cardano.Ledger.Conformance.ExecSpecRule.Conway.Base[0m[0;93m:[0m[0;95m205[0m[0;93m][0m
2024-10-14T21:11:33.7998697Z           └[0;93m[[0m[0;94mTest.Cardano.Ledger.Conformance.ExecSpecRule.Core[0m[0;93m:[0m[0;95m429[0m[0;93m][0m
2024-10-14T21:11:33.7999137Z             └[0;93m[[0m[0;94mTest.Cardano.Ledger.Conformance.Spec.Conway[0m[0;93m:[0m[0;95m35[0m[0;93m][0m
2024-10-14T21:11:33.7999577Z          Run the test again with CONFORMANCE_CBOR_DUMP_PATH=<path> to get a CBOR dump of the test data
2024-10-14T21:11:33.7999656Z        
2024-10-14T21:11:33.7999797Z        [0;91m[0;93m===== DIFF =====
2024-10-14T21:11:33.7999877Z        Left
2024-10-14T21:11:33.7999965Z          (NE.fromList
2024-10-14T21:11:33.8000050Z            [
2024-10-14T21:11:33.8000354Z              [0;91m(Impl: `App "MaxTxSizeUTxO" [App "3065" [],App "3000" []]`)[0;93m,
2024-10-14T21:11:33.8001371Z              [0;91m(Impl: `App "BabbageNonDisjointRefInputs" [App "NE.fromList" [Lst [App "TxIn" [App "TxId" [App "SafeHash" [App "\\"a31ecfff49c768f4036cc95cd2d99bae45852ba12c9f7bcd62dc4494decb82cf\\"" []]],App "TxIx" [App "98" []]]]]]`)[0;93m,
2024-10-14T21:11:33.8003392Z              [0;95m(Agda: `¬\xa;(.Axiom.Set.Theoryᵈ.th List-Modelᵈ Axiom.Set.Theory.Intersection.∩\xa; .Axiom.Set.Theoryᵈ.∈-sp List-Modelᵈ)\xa;(.TransactionStructure.TxBody.txins\xa; (.TransactionStructure.Tx.body tx))\xa;(.TransactionStructure.TxBody.refInputs\xa; (.TransactionStructure.Tx.body tx))\xa;≡\xa;.HasEmptySet.∅\xa;(Interface.HasEmptySet.Instances.HasEmptySet-Set\xa; (.Axiom.Set.Theoryᵈ.th List-Modelᵈ))`)[0;93m])
2024-10-14T21:11:33.8003560Z        
2024-10-14T21:11:33.8003641Z        Legend:
2024-10-14T21:11:33.8003791Z          [0;91m-Implementation[0;93m
2024-10-14T21:11:33.8003952Z          [0;95m+Specification[0;93m[0m[0m
2024-10-14T21:11:33.8003960Z 
2024-10-14T21:11:33.8004352Z   To rerun use: --match "/Conway/Conformance/Blocks transition graph/UTXO/" --seed 203954034
2024-10-14T21:11:33.8004362Z 
2024-10-14T21:11:33.8004469Z Randomized with seed 203954034
2024-10-14T21:11:33.8004474Z 
2024-10-14T21:11:33.8004642Z Finished in 905.8218 seconds
2024-10-14T21:11:33.8004814Z [31m31 examples, 1 failure, 6 pending[0m
```

### PR DESCRIPTION
**Pull request by teodanciu**
# Description

Fixes https://github.com/IntersectMBO/cardano-ledger/issues/4685
in order to avoid UTXO conformance test failure

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

### CODE REVIEW

File: libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/ExecSpecRule/Conway/Base.hs [hunk 1]
```diff
@@ -162,10 +162,11 @@ instance
       runGenRS proof genSize $
         genAlonzoTx proof ueSlot
     ueCertState <- arbitrary
+    let txSize = uecTx ^. sizeTxF
     let
       uePParams =
         gePParams (gsGenEnv gs)
-          & ppMaxTxSizeL .~ 3000
+          & ppMaxTxSizeL .~ fromIntegral txSize
```
Comment (teodanciu) [inline libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/ExecSpecRule/Conway/Base.hs:169]: This is not safe, but assuming that the generated transaction is smaller than 4GB.. sounds like a reasonable assumption, no?

Comment (lehins) [reply libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/ExecSpecRule/Conway/Base.hs:169]: Yes, it is safe to assume generated transactions are smaller than 4Gb.

**Review by lehins — APPROVED** [review]
I am not sure how I feel about setting the protocol parameter from information about transaction. This will always artificially make it pass. But, I don't have a better suggestion except setting it to a very large value to begin with.

It does look like there is no matching check in the spec, otherwise conformance test would not have failed. It is worth investigating it and then when it is fixed on the spec side we can  set `maxTxSize` to a sensible value instead of inferring it from a transaction.

I am fine with merging this now, so we unbreak CI on master. Could you please create a ticket about it, so we don't forget about fixing it properly.
