### PR TITLE
Fixed a bug in GOV rule

### LINKED ISSUE #3980: CommitteeMember can vote on UpdateCommitteeProposal
A transaction that contains CommiteeMember vote on UpdateCommiteProposal can be successfully submitted and accepted on chain without resulting in DisallowedVoters failure.

```json
  "proposals": [
    {
      "action": {
        "contents": [
          null,
          [],
          {
            "keyHash-db34410e3234ef221cdb5a0361197707845168fab6cf7e6eff19d9b7": 28
          },
          0.6
        ],
        "tag": "UpdateCommittee"
      },
      "actionId": {
        "govActionIx": 0,
        "txId": "4963f82f7e3d652b06c69f1ee13f1c2df600a47605777891b72c6f27776f189b"
      },
      "committeeVotes": {
        "keyHash-70735b325f5084b23d5f52603642e8f0de61dc8067390a23481b5571": "VoteNo",
        "keyHash-99ee64dd3c5eb4b4d7b77c3f405337cb79f8f7ca0294db294afadf42": "VoteNo",
        "keyHash-f9da4a0db77c27245dbf98202285d6581e1ac383e13d89f233ccd183": "VoteNo"
      },
      "dRepVotes": {
        "keyHash-3cbb0d943e555ad34594ffeddae4703fe39c3e0acc23a5070a4e1bbc": "VoteYes",
        "keyHash-4d7c8d097e0cfb9c279e8e2d3d42668ccddfe55254e930a5c59be6dd": "VoteYes",
        "keyHash-a6ed79d34d7fc61fa7417d7e69446919afa6610d5b4af2b5787f8eda": "VoteYes",
        "keyHash-f679b984fd1b2e87e583fc3f2f4198dbdb999744033b2eb8d534003f": "VoteYes"
      },
      "deposit": 100000000,
      "expiresAfter": 26,
      "proposedIn": 24,
      "returnAddr": {
        "credential": {
          "keyHash": "4567e58c2966eb77fb951f063b2d3d466d5f6675884562597c7db563"
        },
        "network": "Testnet"
      },
      "stakePoolVotes": {
        "c0875e300838c796d14afd125a281d8a05f710c3dedc2e3e00b88c88": "VoteYes",
        "cc6095a014a7d4e31d4149841e427b754efd0233f830d32128fe892e": "VoteYes",
        "f0ae80ac376a5f0fb43ce843e1188c0e33f1867c7afe76f7f0c100e0": "VoteYes"
      }
    }
  ]
```

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

Fixes a bug where it was possible to vote for a proposal even if the voter's role shouldn't allow it. 

resolves #3980

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs [hunk 1]
```diff
@@ -393,14 +395,16 @@ govTransition = do
...
       govActionIdVotes =
-        Map.foldlWithKey'
-          (\acc voter gaIds -> Map.union (voter <$ gaIds) acc)
-          Map.empty
-          (unVotingProcedures votingProcedures)
-  runTest $ checkVotesAreForValidActions currentEpoch proposals govActionIdVotes
-  runTest $ checkVotersAreValid proposals govActionIdVotes
+        foldMap
+          (\(voter, gaIds) -> (,voter) <$> Map.keys gaIds)
+          (Map.toList $ unVotingProcedures votingProcedures)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs]: There is a `foldrVotingProcedures` function that can be useful specifically for such task. Also we can do the partitioning in the same run, there is no need for a whole new function.
I believe "valid" and "invalid" aren't really good names, since otherwise the "valid" vote can be rejected by `checkVotesAreNotForExpiredActions` and `checkVotersAreValid`, which kind of makes it invalid :grin::
```suggestion
      (unknownGovActionIds, knownVotes) =
        foldrVotingProcedures
          -- strictness is not needed for `unknown`
          (\voter gaId _ (unknown, !known) -> 
            case Map.lookup gaId curGovActionIds of
              Just gas -> (unknown, (voter, gas) : known)
              Nothing -> (gaId : unknown, known))
          ([], [])
          votingProcedures
      curGovActionIds = proposalsActionsMap proposals
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs [hunk 2]
```diff
@@ -785,12 +828,123 @@ secondHardForkCantFollow = do
...
+        { pProcReturnAddr = rewardAccount
+        , pProcGovAction =
+            UpdateCommittee
+              prevGovActionId
+              mempty
+              (Map.singleton khCommittee $ EpochNo 28)
+              (3 %! 5)
+        , pProcDeposit = govActionDeposit
+        , pProcAnchor = def
+        }
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs]: Slight simplification
```suggestion
  khCommittee <- KeyHashObj <$> freshKeyHash
  prevGovActionId <-
    getsNES $
      nesEsL
        . esLStateL
        . lsUTxOStateL
        . utxosGovStateL
        . cgEnactStateL
        . ensPrevGovActionIdsL
        . prevGovActionIdsL
        . pfCommitteeL
  committeeUpdateId <-
    submitGovAction $
            UpdateCommittee
              prevGovActionId
              mempty
              (Map.singleton khCommittee $ EpochNo 28)
              (3 %! 5)
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs [hunk 3]
```diff
@@ -785,12 +828,123 @@ secondHardForkCantFollow = do
...
+
+committeeMemberVotingOnCommitteeChange ::
+  forall era.
+  ( ConwayEraImp era
+  , GovState era ~ ConwayGovState era
+  , Inject (ConwayGovPredFailure era) (PredicateFailure (EraRule "LEDGER" era))
+  ) =>
+  ImpTestM era ()
+committeeMemberVotingOnCommitteeChange = do
+  (_, ccHot) <- electBasicCommittee
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs]: I think it would make sense for `electBasicCommittee` to also return `prevGovActionId`, so we don't have to look it up in the state. I can do this change at some later point, if you'd rather not deal with it.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs [hunk 4]
```diff
@@ -85,7 +86,49 @@ spec =
...
+                { pProcReturnAddr = rewardAccount
+                , pProcGovAction =
+                    UpdateCommittee
+                      prevGovActionId
+                      mempty
+                      (Map.singleton credCandidate $ EpochNo 28)
+                      (3 %! 5)
+                , pProcDeposit = govActionDeposit
+                , pProcAnchor = def
+                }
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs]: Ditto
```suggestion
          committeeUpdateId <-
            submitGovAction
             $      UpdateCommittee
                      prevGovActionId
                      mempty
                      (Map.singleton credCandidate $ EpochNo 28)
                      (3 %! 5)
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs [hunk 5]
```diff
@@ -133,15 +136,15 @@ data ConwayGovPredFailure era
   | -- | Some governance actions are not allowed to be voted on by certain types of
     -- Voters. This failure lists all governance action ids with their respective voters
     -- that are not allowed to vote on those governance actions.
-    DisallowedVoters !(Map.Map (GovActionId (EraCrypto era)) (Voter (EraCrypto era)))
+    DisallowedVoters !(NonEmpty (GovActionId (EraCrypto era), Voter (EraCrypto era)))
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs]: I now this is not important, but I think voter should come first, since voter is the offender.
```suggestion
    DisallowedVoters !(NonEmpty (Voter (EraCrypto era), GovActionId (EraCrypto era)))
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs [hunk 6]
```diff
@@ -133,15 +136,15 @@ data ConwayGovPredFailure era
...
   | ConflictingCommitteeUpdate
       -- | Credentials that are mentioned as members to be both removed and added
       (Set.Set (Credential 'ColdCommitteeRole (EraCrypto era)))
   | ExpirationEpochTooSmall
       -- | Members for which the expiration epoch has already been reached
       (Map.Map (Credential 'ColdCommitteeRole (EraCrypto era)) EpochNo)
   | InvalidPrevGovActionId (ProposalProcedure era)
-  | VotingOnExpiredGovAction (Map.Map (GovActionId (EraCrypto era)) (Voter (EraCrypto era)))
+  | VotingOnExpiredGovAction (NonEmpty (GovActionId (EraCrypto era), Voter (EraCrypto era)))
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs]: Ditto
```suggestion
  | VotingOnExpiredGovAction (Voter (EraCrypto era)), NonEmpty (GovActionId (EraCrypto era))
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs [hunk 7]
```diff
@@ -785,12 +828,123 @@ secondHardForkCantFollow = do
...
+        { pProcReturnAddr = rewardAddr
+        , pProcGovAction =
+            UpdateCommittee
+              prevCommitteeId
+              mempty
+              (Map.singleton newCommitteeMember $ EpochNo 10)
+              (1 %! 2)
+        , pProcDeposit = propDeposit
+        , pProcAnchor = def
+        }
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs]:
```suggestion
  committeeProposal <-
    submitGovAction $
            UpdateCommittee
              prevCommitteeId
              mempty
              (Map.singleton newCommitteeMember $ EpochNo 10)
              (1 %! 2)
```

**Review by lehins — APPROVED** [review]
Perfect! I love the switch to NonEmpty in predicate failures! I have a few suggestions, but they aren't critical

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs [hunk 8]
```diff
@@ -85,7 +86,31 @@ spec =
           submitFailingVote
             voter
             dummyGaid
-            [inject $ GovActionsDoNotExist @era $ Set.singleton dummyGaid]
+            [inject $ GovActionsDoNotExist @era $ NE.singleton dummyGaid]
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs]: `singleton` isn't available in ghc-8.10
```suggestion
            [inject $ GovActionsDoNotExist @era $ pure dummyGaid]
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs [hunk 9]
```diff
@@ -32,6 +32,7 @@ import Control.Monad (replicateM_)
 import Control.State.Transition.Extended (PredicateFailure)
 import Data.Default.Class (Default (..))
 import Data.Foldable (Foldable (..), traverse_)
+import qualified Data.List.NonEmpty as NE
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs]: Redundant
```suggestion
```
