### PR TITLE
Ensure dreps exist prior to delegation

### LINKED ISSUE #4598: Ensure that dRep ID exists prior to delegation
Delegation to a non-existent or retired stake pool is already blocked by the ledger.

However, it is possible to delegate to a non-existent dRep. This seems to circumvent the `spirit` of CIP-1694 in blocking the withdrawal of rewards given that I can delegate to an impossible to exist dRep that will never take any action in the governance system.

**Expected Behavior:** A user delegating to a non-existent or retired dRep should fail at the ledger level.

Example: https://cardanoscan.io/transaction/cf9ae712270a0b5de6f3f41f8a1b640d7412e8bbba4253eaf8b78bc589a6a094?tab=voteDelegations

### PR DESCRIPTION
**Pull request by lehins**
# Description

Fixes #4598

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

### CODE REVIEW

File: libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs [hunk 1]
```diff
@@ -125,6 +126,7 @@ data DRepState c = DRepState
   { drepExpiry :: !EpochNo
   , drepAnchor :: !(StrictMaybe (Anchor c))
   , drepDeposit :: !Coin
+  , drepDelegs :: !(Set (Credential 'Staking c))
```
Comment (teodanciu) [inline libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs:129]: You could add to  cardano-ledger-core CHANGELOG: 
``Add `drepDelegs` to `DRepState` ``

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs [hunk 2]
```diff
@@ -207,16 +259,15 @@ conwayDelegTransition = do
...
       isJust mUMElem ?! StakeKeyNotRegisteredDELEG stakeCred
       failOnJust checkStakeKeyHasZeroRewardBalance StakeKeyHasNonZeroRewardAccountBalanceDELEG
-      pure $ dState {dsUnified = umap}
+      pure $ processUnDelegation stakeCred mCurDelegatee $ certState & certDStateL . dsUnifiedL .~ umap
     ConwayDelegCert stakeCred delegatee -> do
-      checkStakeKeyIsRegistered stakeCred
+      mCurDelegatee <- checkStakeKeyIsRegistered stakeCred
       checkStakeDelegateeRegistered delegatee
-      pure $ dState {dsUnified = processDelegation stakeCred delegatee dsUnified}
+      pure $ processDelegation stakeCred delegatee $ processUnDelegation stakeCred mCurDelegatee certState
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs:266]: Why this undelegation step here, in  Deleg?   Is it in case it's "redelegation", so we cleanup the old one before delegating to the new?

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/GovCert.hs [hunk 3]
```diff
@@ -264,11 +265,14 @@ conwayGovCertTransition = do
...
-        Just drepState ->
-          let paidDeposit = drepState ^. drepDepositL
-           in refund == paidDeposit ?! ConwayDRepIncorrectRefund refund paidDeposit
+      let mDRepState = Map.lookup cred vsDReps
+          drepRefundMismatch = do
+            drepState <- mDRepState
+            let paidDeposit = drepState ^. drepDepositL
+            guard (refund /= paidDeposit)
+            pure paidDeposit
+      isJust mDRepState ?! ConwayDRepNotRegistered cred
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/GovCert.hs:281]: At least once every two PRs I wonder why we don't have `failOnNothing`.  We can discuss when you're back, if there's anything to discuss!

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs [hunk 4]
```diff
@@ -200,13 +231,20 @@ conwayDelegTransition = do
             DelegStakeVote targetPool targetDRep ->
               checkPoolRegistered targetPool >> checkDRepRegistered targetDRep
             DelegVote targetDRep -> checkDRepRegistered targetDRep
+    umElemToDelegatee (UM.UMElem _ _ mPool mDRep) =
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs:234]: This could probably even in UMap, seems useful and quite generic.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs [hunk 5]
```diff
@@ -173,18 +182,40 @@ conwayDelegTransition = do
...
+    processUnDelegation stakeCred (Just delegatee) cState@(CertState {certVState}) =
+      case delegatee of
+        DelegStake _ -> cState
+        DelegVote dRep -> cState {certVState = unDelegVote stakeCred certVState dRep}
+        DelegStakeVote _sPool dRep -> cState {certVState = unDelegVote stakeCred certVState dRep}
     checkStakeKeyNotRegistered stakeCred =
       UM.notMember stakeCred (UM.RewDepUView dsUnified) ?! StakeKeyRegisteredDELEG stakeCred
-    checkStakeKeyIsRegistered stakeCred =
-      UM.member stakeCred (UM.RewDepUView dsUnified) ?! StakeKeyNotRegisteredDELEG stakeCred
+    checkStakeKeyIsRegistered stakeCred = do
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs:215]: Now the name became a little bit confusing, because it would seem it's only dealing with whether it's registered or not, but actually returning the Delegatee. But I don't have a better idea and it's inferable from the type anyway.. Probably better than `checkStakeKeyIsRegisteredAndReturnDelegattee` :laughing:

File: libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs [hunk 6]
```diff
@@ -164,6 +169,9 @@ instance Crypto c => FromJSON (DRepState c) where
       <$> o .: "expiry"
       <*> o .:? "anchor" .!= SNothing
       <*> o .: "deposit"
+      -- Construction of DRep state with deleagations is intentionally prohibited, since
+      -- there is a requirement to retain the invariant of delegations in the UMap
+      <*> pure mempty
 
 drepExpiryL :: Lens' (DRepState c) EpochNo
 drepExpiryL = lens drepExpiry (\x y -> x {drepExpiry = y})
```
Comment (teodanciu) [inline libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs:177]: A lens would be nice 
```suggestion
drepExpiryL = lens drepExpiry (\x y -> x {drepExpiry = y})

drepDelegsL :: Lens' (DRepState c) (Set (Credential 'Staking c))
drepDelegsL = lens drepDelegs (\x y -> x {drepDelegs = y})

```

File: libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs [hunk 7]
```diff
@@ -8,7 +8,7 @@
 {-# LANGUAGE ViewPatterns #-}
 
 module Cardano.Ledger.DRep (
-  DRep (DRepCredential, DRepAlwaysAbstain, DRepAlwaysNoConfidence),
+  DRep (DRepCredential, DRepKeyHash, DRepScriptHash, DRepAlwaysAbstain, DRepAlwaysNoConfidence),
   DRepState (..),
   drepExpiryL,
   drepAnchorL,
```
Comment (teodanciu) [inline libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs:14]: Just in case you had added the lens:

```suggestion
  drepAnchorL,
  drepDelegsL
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/GovCert.hs [hunk 8]
```diff
@@ -236,57 +240,80 @@ conwayGovCertTransition = do
...
+      pure $
+        case mDRepState of
+          Nothing -> certState'
+          Just dRepState ->
+            certState'
+              { certDState =
+                  certDState
+                    { dsUnified = drepDelegs dRepState UM.⋪ UM.DRepUView (dsUnified certDState)
+                    }
+              }
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/GovCert.hs:295]: Maybe slightly easier to follow using lenses?   But I can see this module is not so "lensified" - it doesn't matter, just an idea. 
```suggestion
           certDStateL . dsUnifiedL %~  ((UM.⋪) (drepDelegs dRepState) . UM.DRepUView)
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs [hunk 9]
```diff
@@ -60,8 +65,30 @@ instance
...
+            let umap = certState ^. certDStateL . dsUnifiedL
+                dReps = certState ^. certVStateL . vsDRepsL
+                (dRepsWithDelegations, elemsWithoutUnknownDRepDelegations) =
+                  Map.mapAccumWithKey adjustDelegations dReps (UM.umElems umap)
+                adjustDelegations ds stakeCred umElem@(UM.UMElem rd ptr stakePool mDrep) =
+                  case mDrep of
+                    SJust (DRepCredential dRep) ->
+                      let addDelegation _ dRepState =
+                            Just $ dRepState {drepDelegs = Set.insert stakeCred (drepDelegs dRepState)}
+                       in case Map.updateLookupWithKey addDelegation dRep ds of
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/HardFork.hs:85]: TIL about both `mapAccumWithKey` and `updateLookupWithKey`, very cool!

**Review by teodanciu — APPROVED** [review]
Looks good to me, just a few questions but nothing important - you can safely ignore them.

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/GovCert.hs [hunk 10]
```diff
@@ -39,10 +39,11 @@ vStateSpec = constrained' $ \ [var|_dreps|] [var|_commstate|] [var|dormantepochs
 govCertSpec ::
   IsConwayUniv fn =>
   ConwayGovCertEnv (ConwayEra StandardCrypto) ->
-  VState (ConwayEra StandardCrypto) ->
+  CertState (ConwayEra StandardCrypto) ->
   Specification fn (ConwayGovCert StandardCrypto)
-govCertSpec ConwayGovCertEnv {..} vs =
-  let reps = lit $ Map.keysSet $ vsDReps vs
+govCertSpec ConwayGovCertEnv {..} certState =
+  let vs = certVState certState
```
Comment (Soupstraw) [inline libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/GovCert.hs:45]: It doesn't seem to make sense to have a `CertState` argument if all we do is use the `VState`

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/LedgerTypes/Specs.hs [hunk 11]
```diff
@@ -434,7 +441,17 @@ certStateSpec acct epoch = constrained $ \ [var|certState|] ->
...
+        pState
+        psStakePoolParams
+        ( \ [var|poolreg|] ->
+            reify
+              vState
+              vsDReps
+              ( \ [var|dreps|] ->
+                  satisfies dState (dstateSpec acct poolreg dreps)
+              )
+        )
```
Comment (Soupstraw) [inline libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/LedgerTypes/Specs.hs:458]: I'm not sure why this didn't use `match` instead of `reify`. This approach makes it impossible to test a value against this spec (but also that's fine for now, because we only care about generation of values for conformance testing)

Comment (Soupstraw) [reply libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/LedgerTypes/Specs.hs:458]: I guess it becomes too long when using `match`, but you can use `sel` instead to pick the field you actually care about

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/GovCert.hs (hunk 10 above)
Comment (Lucsanszky) [reply libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/GovCert.hs:45]: I'll leave it as it is for now, @lehins might had his reasons to do this despite what you point out is true.

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/LedgerTypes/Specs.hs (hunk 11 above)
Comment (Lucsanszky) [reply libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/LedgerTypes/Specs.hs:458]: I'm not sure either and just followed the pattern established by `reify pState...`. Won't address this now, we can clean up later.

**Review by Lucsanszky — COMMENTED** [review]
@teodanciu I marked your remarks as resolved so I can merge. I'll let @lehins to address them.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs (hunk 2 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Deleg.hs:266]: Correct. We need to make sure that old delegation is removed from the DRep's set with delegations

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/GovCert.hs (hunk 3 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/GovCert.hs:281]: Probably because it's implementation would be `failOnNothing x = (isJust x ?!)`

However, just for consistency sake with `failOnJust` we could add it.

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/GovCert.hs (hunk 10 above)
Comment (lehins) [reply libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Conway/GovCert.hs:45]: Yes, I do have my reasons :smile: 

We'll switch to the same approach for SPOs in the near future, so we'll need access to the `PState` as well.

File: libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs (hunk 6 above)
Comment (lehins) [reply libs/cardano-ledger-core/src/Cardano/Ledger/DRep.hs:177]: Added in #4707
