### PR TITLE
Plutusv3 initialization tests

### LINKED ISSUE #4153: Imp test PlutusV3 gov script initialization
We need to test the ability to enable PlutusV3 and running the guardrail script. Here are the three scenarios that should be tested as part of this ticket

## Intentional deadlock

1. start the test **without** the CostModel for PlutusV3 and no governance policy script
2. propose and enact the new CostModel for PlutusV3
3. propose and enact new guardrails script that always fails
4. attempt to propose new CostModel for PlutusV3 and observe it fail

## Unintentional deadlock

1. start the test **without** the CostModel for PlutusV3 and a governance policy script that always succeeds
2. attempt to propose new CostModel for PlutusV3 and observe it fail

## The planned successful approach should also be tested:

For this part this test can be expanded: https://github.com/IntersectMBO/cardano-ledger/blob/3cbce69242ad7e43d24adda4c607792ff5ee6f69/eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs#L546

1. start the test **without** the CostModel for PlutusV3 and no governance policy script
2. attempt submitting a transaction that mints a token with a PlutusV3 script and observe it fail  
3. propose and enact the new CostModel for PlutusV3
4. propose and enact new guardrails script that always succeeds
5. propose and enact proposals that do a TreasuryWithdrawal and a change to PParams

### PR DESCRIPTION
**Pull request by teodanciu**
# Description

Closes https://github.com/IntersectMBO/cardano-ledger/issues/4153

- Adds tests for various initialization scenarios
- Reorganizes UtxosSpec file to make it easier to read

It's easier to review the commits separately, since the second one might make it difficult to see the added tests. 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs [hunk 1]
```diff
@@ -612,7 +536,222 @@ govPolicySpec = do
...
+    )
+    ( pure . injectFailure $
+        CollectErrors [BadTranslation errorField]
+    )
+
+expectPhase2Invalid :: ConwayEraImp era => Tx era -> ImpTestM era ()
+expectPhase2Invalid tx = do
+  res <- trySubmitTx tx
+  -- TODO: find a way to check that this is a PlutusFailure
+  -- without comparing the entire PredicateFailure
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs:726]: This is a ticket that should provide a solution: https://github.com/IntersectMBO/cardano-ledger/issues/4167

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs [hunk 2]
```diff
@@ -612,7 +536,222 @@ govPolicySpec = do
...
+
+      (dRep, committeeMember, _) <- electBasicCommittee
+      anchor <- arbitrary
+      govIdConstitution1 <-
+        enactConstitution SNothing (Constitution anchor SNothing) dRep committeeMember
+
+      let guessTheNumberSh = hashPlutusScript (guessTheNumber3 SPlutusV3)
+
+      impAnn "Minting token fails" $ do
+        tx <- mintingTokenTx @era (mkBasicTx @era mkBasicTxBody) guessTheNumberSh
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs:614]: These type annotations are not necessary. But it is ok to keep them around, so no need to change it, just pointing it out.
```suggestion
        tx <- mintingTokenTx (mkBasicTx mkBasicTxBody) guessTheNumberSh
```

**Review by lehins — APPROVED** [review]
Perfect!!!
Thank you!
