### PR TITLE
Fix COMPLETE pragma for `NativeScript ShelleyEra`

### LINKED ISSUE #4613: Fix `COMPLETE` for all type class based pattern synonyms
We have a few type class based pattern synonyms:
* [x] - `TxCert`s
* [x] - `NativeScript`s

All of these cannot have a `COMPLETE` pragma implemented for them, since ghc-8.10 does not support new syntax with the type. For example that is why we had to reject this RP: https://github.com/IntersectMBO/cardano-ledger/pull/4481/files

Which tried to add an incorrect pattern:
```haskell
{-# COMPLETE
  RequireSignature
  , RequireAllOf
  , RequireAnyOf
  , RequireMOf
  #-}
```
since it would disregard timelock's `RequireTimeStart` and `RequireTimeExpire`.

Therefore, the correct way to solve this is to specify `COMPELTE` pragma for each era:

```haskell
{-# COMPLETE
  RequireSignature
  , RequireAllOf
  , RequireAnyOf
  , RequireMOf :: Shelley
  #-}
```

```haskell
{-# COMPLETE
  RequireSignature
  , RequireAllOf
  , RequireAnyOf
  , RequireMOf
  , RequireTimeStart
  , RequireTimeExpire :: Allegra
  #-}
```

etc.

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Addresses only part of #4613 that can be done without moving Era type definitions

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [ ] ~~Tests added or updated when needed.~~
- [ ] ~~`CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).~~
- [ ] ~~Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).~~
- [ ] ~~Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).~~
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

**Review by lehins — CHANGES_REQUESTED** [review]
The same needs to be applied to **all** eras for both native scripts and certificates.
@aniketd I recommend you do a bit of research and experiment with what exactly you are trying to solve here. If anything is unclear and you have some questions, please send them my way.

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/Scripts.hs [hunk 1]
```diff
@@ -181,6 +181,14 @@ pattern RequireMOf n ms <- (getRequireMOf -> Just (n, ms))
   where
     RequireMOf n ms = mkRequireMOf n ms
 
+{-# COMPLETE
+  RequireSignature
+  , RequireAllOf
+  , RequireAnyOf
+  , RequireMOf ::
+    ShelleyEra
+  #-}
```
Comment (aniketd) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/Scripts.hs:190]: Since `COMPLETE` pragmas are considered "orphan" when none of the constructors used in its definition are defined in the same module, we can currently only make this work for `NativeScript` to differentiate between `Shelley` and `Allegra` onwards. We cannot differentiate between other `eras` since they do not introduce any new patterns. For `TxCert` we will keep the existing pragma as is, since we cannot specialise the `Shelley` `TxCert` with the pragma and have it apply also to the rest of the `eras` upto `Babbage`.

**Review by lehins — APPROVED** [review]
I've created a ticket #5069 that should allow us progress further on  #4613
Until them we can merge this PR, since it is fine by itself.
