### PR TITLE
Fail when conway features are present in transactions that use Plutus v1/v2

### LINKED ISSUE #4101: ImpTest failure of Conway features for PlutusV1/V2
Every new feature that was added in Conway, when present in a transaction, must result in `ContextError` for PlutusV1 and PlutusV2 language versions.

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Resolves #4101 

~~This PR will be followed up by one that implements the tests.~~
Also adds tests :sweat_smile: 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 1]
```diff
@@ -239,36 +245,94 @@ transTxInInfoV1 utxo txIn = do
...
+  -- TODO: @aniketd: Also implement for TxWits
+  let txBody = tx ^. bodyTxL
+      txCerts = txBody ^. certsTxBodyL
+      _txRdmrs = tx ^. witsTxL . rdmrsTxWitsL
+      currentTreasuryValue = txBody ^. currentTreasuryValueTxBodyL
+      votingProcedures = txBody ^. votingProceduresTxBodyL
+      proposalProcedures = txBody ^. proposalProceduresTxBodyL
+      treasuryDonation = txBody ^. treasuryDonationTxBodyL
+      txChecks =
+        if
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: MultiWayIf is totally unnecessary
```suggestion
      txChecks
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 2]
```diff
@@ -239,36 +245,94 @@ transTxInInfoV1 utxo txIn = do
...
+              , PV1.txInfoDCert = txCerts
+              , PV1.txInfoWdrl = Alonzo.transTxBodyWithdrawals txBody
+              , PV1.txInfoValidRange = timeRange
+              , PV1.txInfoSignatories = Alonzo.transTxBodyReqSignerHashes txBody
+              , PV1.txInfoData = Alonzo.transTxWitsDatums (tx ^. witsTxL)
+              , PV1.txInfoId = Alonzo.transTxBodyId txBody
+              }
+          where
+            txBody = tx ^. bodyTxL
+     in translate <=< transTxV3
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: Switch back to do syntax

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 3]
```diff
@@ -177,6 +196,11 @@ instance
       encode $ Sum CertificateNotSupported 9 !> To txCert
     PlutusPurposeNotSupported purpose ->
       encode $ Sum PlutusPurposeNotSupported 10 !> To purpose
+    ExpectedEmptyCurrentTreasuryValueInTxWithPlutusV1V2 scoin ->
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]:
```suggestion
    TreasuryFieldNotSupported scoin ->
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 4]
```diff
@@ -239,12 +263,75 @@ transTxInInfoV1 utxo txIn = do
   plutusTxOut <- transTxOutV1 (TxOutFromInput txIn) txOut
   Right (PV1.TxInInfo (transTxIn txIn) plutusTxOut)
 
+-- TODO: @aniketd: Implement translation for reg_cert and unreg_cert
+guardConwayFeaturesInTxCert ::
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]:
```suggestion
transTxCertV1V2 ::
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 5]
```diff
@@ -239,12 +263,75 @@ transTxInInfoV1 utxo txIn = do
...
+    then Left $ inject $ CertificateNotSupported txCert
+    else Right txCert
+  where
+    isConwayFeatureInTxCert = \case
+      RegPoolTxCert PoolParams {} -> False
+      RetirePoolTxCert _poolId _retireEpochNo -> False
+      RegTxCert _stakeCred -> False
+      UnRegTxCert _stakeCred -> False
+      DelegTxCert _stakeCred _delegatee -> False
+      _ -> True
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]:
```suggestion
      _ -> pure $ Alonozo.transTxCert txCert
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 6]
```diff
@@ -239,12 +263,75 @@ transTxInInfoV1 utxo txIn = do
...
+  , PlutusTxCert l ~ PV2.DCert
+  , ConwayEraTxBody era
+  , AlonzoEraTxWits era
+  , EraPlutusTxInfo l era
+  , Inject (ConwayContextError era) (ContextError era)
+  , PlutusPurpose AsItem era ~ ConwayPlutusPurpose AsItem era
+  ) =>
+  proxy l ->
+  Tx era ->
+  Either (ContextError era) (Tx era)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]:
```suggestion
  Either (ContextError era) ()
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 7]
```diff
@@ -239,12 +291,74 @@ transTxInInfoV1 utxo txIn = do
...
+  , PlutusPurpose AsItem era ~ ConwayPlutusPurpose AsItem era
+  ) =>
+  proxy l ->
+  Tx era ->
+  Either (ContextError era) ()
+guardConwayFeaturesInTx proxy tx = do
+  let txBody = tx ^. bodyTxL
+      txCerts = txBody ^. certsTxBodyL
+  -- Guard TxCerts
+  void $ transTxCertV1V2 `mapM` txCerts
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: This is already checked at the call site where `transTxCertV1V2` is used. Also FYI there is `mapM_` variant that is more efficient than `void . mapM`
```suggestion
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 8]
```diff
@@ -239,12 +291,74 @@ transTxInInfoV1 utxo txIn = do
...
+  -- Guard ScriptPurpose
+  let scriptPurposes =
+        -- Without checking for RedeemerPointerPointsToNothing. QUESTION: Should this be separated for V1 vs V2?
+        mapMaybe
+          (strictMaybeToMaybe . redeemerPointerInverse txBody)
+          $ Map.keys
+          $ unRedeemers
+          $ tx ^. witsTxL . rdmrsTxWitsL
+  void $ (transPlutusPurposeV1V2 proxy . hoistPlutusPurpose toAsItem) `mapM` scriptPurposes
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]:
```suggestion
```
This check is already done for PlutusV2 with this function: https://github.com/IntersectMBO/cardano-ledger/blob/e9e080f0dd855f22ab2fae18eb055a133b7c274e/eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs#L642


Moreover, `VotingProceduresFieldNotSupported` and `ProposalProceduresFieldNotSupported` will prevent those plutus purposes as well.

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 9]
```diff
@@ -131,14 +136,28 @@ data ConwayContextError era
   = BabbageContextError !(BabbageContextError era)
   | CertificateNotSupported !(TxCert era)
   | PlutusPurposeNotSupported !(PlutusPurpose AsItem era)
+  | CurrentTreasuryFieldNotSupported !(StrictMaybe Coin)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: If we are failing with this that means the coin is present so we can provide the exact value
```suggestion
  | CurrentTreasuryFieldNotSupported !Coin
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 10]
```diff
@@ -239,12 +291,74 @@ transTxInInfoV1 utxo txIn = do
...
+          $ tx ^. witsTxL . rdmrsTxWitsL
+  void $ (transPlutusPurposeV1V2 proxy . hoistPlutusPurpose toAsItem) `mapM` scriptPurposes
+  -- Guard Tx
+  let currentTreasuryValue = txBody ^. currentTreasuryValueTxBodyL
+      votingProcedures = txBody ^. votingProceduresTxBodyL
+      proposalProcedures = txBody ^. proposalProceduresTxBodyL
+      treasuryDonation = txBody ^. treasuryDonationTxBodyL
+  if
+    | isSJust currentTreasuryValue ->
+        Left $ inject $ CurrentTreasuryFieldNotSupported @era currentTreasuryValue
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]:
```suggestion
    | SJust treasury <- currentTreasuryValue ->
        Left $ inject $ CurrentTreasuryFieldNotSupported @era treasury
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 11]
```diff
@@ -239,12 +291,74 @@ transTxInInfoV1 utxo txIn = do
...
+          $ Map.keys
+          $ unRedeemers
+          $ tx ^. witsTxL . rdmrsTxWitsL
+  void $ (transPlutusPurposeV1V2 proxy . hoistPlutusPurpose toAsItem) `mapM` scriptPurposes
+  -- Guard Tx
+  let currentTreasuryValue = txBody ^. currentTreasuryValueTxBodyL
+      votingProcedures = txBody ^. votingProceduresTxBodyL
+      proposalProcedures = txBody ^. proposalProceduresTxBodyL
+      treasuryDonation = txBody ^. treasuryDonationTxBodyL
+  if
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]:
```suggestion
```
MultiWayIf is not necessary, just use the regular monadic `do` syntax:
```haskell
guardConwayFeaturesInTx proxy tx = do
  unless (null $ unVotingProcedures votingProcedures) $
    Left $ inject $ VotingProceduresFieldNotSupported @era votingProcedures
  ...
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 12]
```diff
@@ -239,12 +291,74 @@ transTxInInfoV1 utxo txIn = do
...
+transTxCertV1V2 = \case
+  RegDepositTxCert stakeCred _deposit ->
+    Right $ PV1.DCertDelegRegKey (PV1.StakingHash (transCred stakeCred))
+  UnRegDepositTxCert stakeCred _refund ->
+    Right $ PV1.DCertDelegDeRegKey (PV1.StakingHash (transCred stakeCred))
+  txCert ->
+    maybe
+      (Left $ inject $ CertificateNotSupported txCert)
+      Right
+      $ Alonzo.transTxCertCommon txCert
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: This isn't terribly important, but I believe using guard syntax with patter matching makes it a little bit more obvious what is going on.
```suggestion
  txCert
    | Just dCert <- Alonzo.transTxCertCommon txCert -> Right dCert
    | otherwise -> Left $ inject $ CertificateNotSupported txCert
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 13]
```diff
@@ -4,6 +4,7 @@
 {-# LANGUAGE FlexibleInstances #-}
 {-# LANGUAGE LambdaCase #-}
 {-# LANGUAGE MultiParamTypeClasses #-}
+{-# LANGUAGE MultiWayIf #-}
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: Not needed. In the matter of fact it is never needed. It is always possible to write:
```haskell
let foo 
      | check1 = 1
      | check2 = 2
      | otherwise = 3
```
instead of
```haskell
let foo =
      if
      | check1 = 1
      | check2 = 2
      | otherwise = 3
```
```suggestion
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 14]
```diff
@@ -239,12 +291,74 @@ transTxInInfoV1 utxo txIn = do
...
+      Right
+      $ Alonzo.transTxCertCommon txCert
+
 instance Crypto c => EraPlutusTxInfo 'PlutusV1 (ConwayEra c) where
   toPlutusTxCert _ = transTxCertV1V2
 
   toPlutusScriptPurpose proxy = transPlutusPurposeV1V2 proxy . hoistPlutusPurpose toAsItem
 
   toPlutusTxInfo proxy pp epochInfo systemStart utxo tx = do
+    void $ guardConwayFeaturesInTx proxy tx
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: `void` should not be needed, it already returns `()`
```suggestion
    guardConwayFeaturesV1V2 proxy tx
```

Also suffix `InTx` is unnecessary, since `TxInfo` is all about Tx here. It is better to add a suffix for plutus languages that it is relevant to.

**Review by lehins — CHANGES_REQUESTED** [review]
Overall looks good. Some cleanup is still needed

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs (hunk 7 above)
Comment (aniketd) [reply eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: Noted, thanks! :raised_hands:

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs (hunk 8 above)
Comment (aniketd) [reply eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: I'm discovering the correct way to construct those transactions for the tests that will exercise those PlutusPurpose(s)

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp.hs [hunk 15]
```diff
@@ -30,10 +30,12 @@ spec ::
   forall era.
   ( ConwayEraImp era
   , GovState era ~ ConwayGovState era
+  , AlonzoEraTxWits era
   , InjectRuleFailure "LEDGER" ConwayGovPredFailure era
   , Inject (BabbageContextError era) (ContextError era)
   , InjectRuleFailure "LEDGER" BabbageUtxoPredFailure era
   , InjectRuleFailure "LEDGER" AlonzoUtxosPredFailure era
+  , ContextError era ~ ConwayContextError era
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp.hs]: This constraint is wrong, because it would prevent us using this test in the future era. 
It should be replaced by `Inject (... era) (ContextError era)`
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs [hunk 16]
```diff
@@ -0,0 +1,193 @@
...
+            (SJust (Coin 10000))
+            currentTreasuryValueTxBodyL
+          $ CurrentTreasuryFieldNotSupported
+          $ Coin 10000
+        it "V2"
+          $ testPlutusV1V2Failure
+            setupScriptPlutusV2
+            (SJust (Coin 10000))
+            currentTreasuryValueTxBodyL
+          $ CurrentTreasuryFieldNotSupported
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs]: `inject` will solve the issue with `ContextError era ~ ConwayContextError era` constraint
```suggestion
          $ inject $ CurrentTreasuryFieldNotSupported
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs [hunk 17]
```diff
@@ -0,0 +1,193 @@
...
+        & bodyTxL . lenz
+          .~ badField
+    )
+    [injectFailure $ CollectErrors [BadTranslation errorField]]
+
+spec ::
+  forall era.
+  ( ConwayEraImp era
+  , AlonzoEraTxWits era
+  , ContextError era ~ ConwayContextError era
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs]:
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs [hunk 18]
```diff
@@ -0,0 +1,193 @@
+{-# LANGUAGE DataKinds #-}
+{-# LANGUAGE FlexibleContexts #-}
+{-# LANGUAGE GADTs #-}
+{-# LANGUAGE RankNTypes #-}
+{-# LANGUAGE ScopedTypeVariables #-}
+{-# LANGUAGE TypeApplications #-}
+
+module Test.Cardano.Ledger.Conway.Imp.CertSpec where
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs]: All those predicate failures are coming from the UTXOS rule, not CERT. So, let's rename the module 
```suggestion
module Test.Cardano.Ledger.Conway.Imp.UtxosSpec where
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs [hunk 19]
```diff
@@ -0,0 +1,193 @@
...
+          ( mkBasicTxOut
+              (Addr Testnet (ScriptHashObj sh) StakeRefNull)
+              (inject (Coin 100))
+              & dataHashTxOutL .~ SJust (hashData @era $ Data spendDatum)
+          )
+
+testPlutusV1V2Failure ::
+  forall era a.
+  ( ConwayEraImp era
+  , InjectRuleFailure "LEDGER" AlonzoUtxosPredFailure era
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/CertSpec.hs]: All helper functions that can result in a test failure must have `HasCallStack` constraint, otherwise you won't know which occurance is at fault:
```suggestion
  , InjectRuleFailure "LEDGER" AlonzoUtxosPredFailure era
  , HasCallStack
```

**Review by lehins — CHANGES_REQUESTED** [review]
This looks great!

Could you also add a test that checks that `CertificateNotSupported` works as expected and another test that checks that `RegDepositTxCert` and `RegDepositTxCert` do not trigger the failure.

Also it would be nice to have some other script types be tested, not just the spending. but that is not critical.

**Comment by aniketd** [comment]
> Also it would be nice to have some other script types be tested, not just the spending. but that is not critical.

I could not get to this part today. Unless you think this should be merged @lehins, I will replace some tests with minting scripts tomorrow. :pray:

**Review by lehins — APPROVED** [review]
This is great. Don't worry about mint scripts for this PR. We can expand with more scripts later
