### PR TITLE
Fix `COMPLETE` pragmas for `TxCert` and `NativeScript`

### LINKED ISSUE #4613: Fix `COMPLETE` for all type class based pattern synonyms
We have a few type class based pattern synonyms:
* [x] - `TxCert`s
* [x] - `NativeScript`s

All of these cannot have a `COMPLETE` pragma implemented for them, since ghc-8.10 does not support new syntax with the type. For example that is why we had to reject this RP: https://github.com/IntersectMBO/cardano-ledger/pull/4481/files

Which tried to add an incorrect pattern:
```haskell
{-# COMPLETE
  RequireSignature
  , RequireAllOf
  , RequireAnyOf
  , RequireMOf
  #-}
```
since it would disregard timelock's `RequireTimeStart` and `RequireTimeExpire`.

Therefore, the correct way to solve this is to specify `COMPELTE` pragma for each era:

```haskell
{-# COMPLETE
  RequireSignature
  , RequireAllOf
  , RequireAnyOf
  , RequireMOf :: Shelley
  #-}
```

```haskell
{-# COMPLETE
  RequireSignature
  , RequireAllOf
  , RequireAnyOf
  , RequireMOf
  , RequireTimeStart
  , RequireTimeExpire :: Allegra
  #-}
```

etc.

### PR DESCRIPTION
**Pull request by Lucsanszky**
# Description

Resolves #4613 

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [x] Tests added or updated when needed.
- [x] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

**Comment by Lucsanszky** [comment]
I'm a bit on the fence with regards to mentioning these changes in the `CHANGELOG`s. They can generate `incomplete-pattern` warnings but then again, those are warnings. Nonetheless, it might be helpful to downstream users to indicate these adjustments in the `CHANGELOG`s. @lehins, what do you think?

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 1]
```diff
@@ -575,6 +575,7 @@ transTxCert pv = \case
     PV3.TxCertUnRegDRep (transDRepCred drepCred) (transCoinToLovelace refund)
   UpdateDRepTxCert drepCred _anchor ->
     PV3.TxCertUpdateDRep (transDRepCred drepCred)
+  _ -> error "Impossible: All TxCerts should have been accounted for"
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs:579]: In order for this to be truly impossible you need to add `TxCert era ~ ConwayTxCert era` constraint.

File: eras/allegra/impl/src/Cardano/Ledger/Allegra/Scripts.hs [hunk 2]
```diff
@@ -398,6 +455,7 @@ showTimelock (RequireMOf m xs) = "(MOf " ++ show m ++ " " ++ F.foldl' accum ")"
   where
     accum ans x = showTimelock x ++ " " ++ ans
 showTimelock (RequireSignature hash) = "(Signature " ++ show hash ++ ")"
+showTimelock _ = error "Impossible: All NativeScripts should have been accounted for"
```
Comment (lehins) [inline eras/allegra/impl/src/Cardano/Ledger/Allegra/Scripts.hs:449]: In order for this to be truly impossible you need to add `NativeScript era ~ Timelock era` constraint.

File: eras/allegra/impl/src/Cardano/Ledger/Allegra/Scripts.hs [hunk 3]
```diff
@@ -372,6 +428,7 @@ evalTimelock vhks (ValidityInterval txStart txExp) = go
       RequireAllOf xs -> all go xs
       RequireAnyOf xs -> any go xs
       RequireMOf m xs -> isValidMOf m xs
+      _ -> error "Impossible: All NativeScripts should have been accounted for"
```
Comment (lehins) [inline eras/allegra/impl/src/Cardano/Ledger/Allegra/Scripts.hs:422]: In order for this to be truly impossible you need to add `NativeScript era ~ Timelock era` constraint.

File: eras/allegra/impl/testlib/Test/Cardano/Ledger/Allegra/ImpTest.hs [hunk 4]
```diff
@@ -79,4 +79,5 @@ impAllegraSatisfyNativeScript providedVKeyHashes txBody script = do
       lock@(RequireTimeExpire _)
         | evalTimelock mempty vi lock -> Just mempty
         | otherwise -> Nothing
+      _ -> error "Impossible: All NativeScripts should have been accounted for"
```
Comment (lehins) [inline eras/allegra/impl/testlib/Test/Cardano/Ledger/Allegra/ImpTest.hs:84]: In order for this to be truly impossible you need to add `NativeScript era ~ Timelock era` constraint.

**Review by lehins — COMMENTED** [review]
> Nonetheless, it might be helpful to downstream users to indicate these adjustments in the CHANGELOGs. @lehins, what do you think?

Yes, I think it is a good idea to add introduction of COMPLETE pragmas to the changelog. Important to add them to the era that is affected (eg. `:: MaryEra` should go in to `cardano-ledger-mary`) changelog)

File: eras/allegra/impl/src/Cardano/Ledger/Allegra/Scripts.hs (hunk 2 above)
Comment (lehins) [reply eras/allegra/impl/src/Cardano/Ledger/Allegra/Scripts.hs:449]: Looks like you forgot to add the constraint.

File: eras/alonzo/impl/CHANGELOG.md [hunk 5]
```diff
@@ -2,6 +2,8 @@
 
 ## 1.14.0.0
 
+* Added `COMPLETE` pragma for `TxCert`
+* Added `COMPLETE` pragma for `NativeScript`
```
Comment (lehins) [inline eras/alonzo/impl/CHANGELOG.md]:
```suggestion
* Added `COMPLETE` pragma for `NativeScript AlonzoEra`
```

File: eras/babbage/impl/CHANGELOG.md [hunk 6]
```diff
@@ -2,6 +2,8 @@
 
 ## 1.12.0.0
 
+* Added `COMPLETE` pragma for `TxCert`
+* Added `COMPLETE` pragma for `NativeScript`
```
Comment (lehins) [inline eras/babbage/impl/CHANGELOG.md]:
```suggestion
* Added `COMPLETE` pragma for `NativeScript BabbageEra`
```

File: eras/conway/impl/CHANGELOG.md [hunk 7]
```diff
@@ -2,6 +2,7 @@
 
 ## 1.20.0.0
 
+* Added `COMPLETE` pragma for `NativeScript`
```
Comment (lehins) [inline eras/conway/impl/CHANGELOG.md]:
```suggestion
* Added `COMPLETE` pragma for `NativeScript ConwayEra`
```

File: eras/mary/impl/CHANGELOG.md [hunk 8]
```diff
@@ -2,6 +2,8 @@
 
 ## 1.9.0.0
 
+* Added `COMPLETE` pragma for `TxCert`
+* Added `COMPLETE` pragma for `NativeScript`
```
Comment (lehins) [inline eras/mary/impl/CHANGELOG.md]:
```suggestion
* Added `COMPLETE` pragma for `TxCert MaryEra`
* Added `COMPLETE` pragma for `NativeScript MaryEra`
```

File: eras/allegra/impl/CHANGELOG.md [hunk 9]
```diff
@@ -2,6 +2,7 @@
 
 ## 1.8.0.0
 
+* Added `COMPLETE` pragma for `TxCert`
```
Comment (lehins) [inline eras/allegra/impl/CHANGELOG.md]:
```suggestion
* Added `COMPLETE` pragma for `TxCert AllegraEra`
* Added `COMPLETE` pragma for `NativeScript AllegraEra`
```

**Review by lehins — APPROVED** [review]
Looks good. There are a couple minor fixups I recommended and there seems to be compiler build warning, so CI is failing.
Other than that it is good to go.
