### PR TITLE
Separate Procedures

### LINKED ISSUE #3513: Stop combining VotingProcedure and ProposalProcedure
Combining together VotingProcedure and ProposalProcedure in the TALLY rule is wrong because ProposalProcedure affects the GovernanceActionIx, while it should not. GovernanceActions are proposed by ProposalProcedure, not by VotingProcedures. Also relative of VotingProcedure and ProposalProcedure are not relevant for transaction processing.

`GovernanceProcedure` as it is defined right now:

```haskel
data GovernanceProcedure era
  = GovernanceVotingProcedure !(VotingProcedure era)
  | GovernanceProposalProcedure !(ProposalProcedure era)
```

should be turned into a type that contains all if the procedures:

```
data GovernanceProcedures era =
  { gpVotingProcedures :: Seq (VotingProcedure era)
  , gpProposalProcedures :: Seq (ProposalProcedure era)
  }
```

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR replaces the signal of the TALLY rule for a new `GovernanceProcedures` datatype, which stores votes and proposals separately. This new type resides in the new `Cardano.Ledger.Conway.Governance.Procedures` file, which is re-exported by `Cardano.Ledger.Conway.Governance`.

resolve #3513 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs [hunk 1]
```diff
@@ -0,0 +1,332 @@
...
+  Voter (..),
+  GovernanceAction (..),
+  GovernanceActionId (..),
+  GovernanceActionIx (..),
+  govActionIdToText,
+) where
+
+import Cardano.Crypto.Hash (ByteString, hashToTextAsHex)
+import Cardano.Ledger.BaseTypes (ProtVer, Url)
+import Cardano.Ledger.Binary (DecCBOR (..), EncCBOR (..), decodeEnumBounded, decodeNullStrictMaybe, encodeEnum, encodeListLen, encodeNullStrictMaybe, encodeWord8, invalidKey)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs]: Could you please switch this to a multi-line

**Review by aniketd — APPROVED** [review]
Awesome! :raised_hands:

File: eras/conway/impl/CHANGELOG.md [hunk 2]
```diff
@@ -18,6 +18,7 @@
 * Added instance for `Embed (ConwayRATIFY era) (ConwayEPOCH era)`
 * Removed instance for `Embed (ConwayRATIFY era) (ConwayNEWEPOCH era)`
 * Changed superclasses of `STS (ConwayEPOCH era)` and `STS (ConwayNEWEPOCH era)`
+* Removal of `GovernanceProcedure` in favor of `GovernanceProcedures`
```
Comment (lehins) [inline eras/conway/impl/CHANGELOG.md]: Let's start a new section and a bump to the cabal version: `1.6.0.0`

`1.5.0.0` just has been released an hour ago.

**Review by lehins — CHANGES_REQUESTED** [review]
This is perfect. Due to a new release a few more things are needed: 
* Version bump
* Update to deps and version bump in `cardano-ledger-conway-test`

File: libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal
Comment (lehins) [inline libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal:1]: Sorry, a patch version for this package need to be updated too.

Comment (Soupstraw) [reply libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal:1]: The last release seems to be `1.2.0.1` according to `git tag -l`

Comment (Soupstraw) [reply libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal:1]: ok, I see that they released 1.2.1.1

**Review by lehins — APPROVED** [review]
Perfect!
