### PR TITLE
Fail PlutusV4 `TxInfo` translation when `Ptr` is present in the `TxOut`s

### LINKED ISSUE #4832: Fail PlutusV4 TxInfo translation when a Ptr is present in any of the outputs
Pointers have been pretty much deprecated and are unused anymore. That being said the only reason they are still allowed in a TxOut is because a plutus script might rely on it being present in a transaction. So, in order to eliminate this issue for the future plutus versions we need to prevent any PlutusV4 from being used whenever there is a Ptr present in an address in any of the outputs (also applies to collateral return output)

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR makes the PlutusV4 TxInfo translation fail if there is a `Ptr` present in any of the outputs.

close https://github.com/IntersectMBO/cardano-ledger/issues/4832

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [x] Tests added or updated when needed.
- [x] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [x] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

File: eras/dijkstra/impl/src/Cardano/Ledger/Dijkstra/TxInfo.hs [hunk 1]
```diff
@@ -60,19 +69,105 @@ import Cardano.Ledger.Plutus (
...
+import GHC.Generics (Generic)
 import Lens.Micro ((^.))
+import NoThunks.Class (NoThunks)
 import qualified PlutusLedgerApi.V1 as PV1
 import qualified PlutusLedgerApi.V2 as PV2
 import qualified PlutusLedgerApi.V3 as PV3
 
+data DijkstraContextError era
+  = ConwayContextError !(ConwayContextError era)
+  | PointerPresentInOutput !(TxOut era)
```
Comment (lehins) [inline eras/dijkstra/impl/src/Cardano/Ledger/Dijkstra/TxInfo.hs]: We only short circuit on a first failure whenever there is a really good reason for it, otherwise we always report all violations. This one is no different. Let's switch it to `NonEmpty` and report all such issues:
```suggestion
  | PointerPresentInOutput !(NonEmpty (TxOut era))
```

File: eras/dijkstra/impl/src/Cardano/Ledger/Dijkstra/TxInfo.hs [hunk 2]
```diff
@@ -356,13 +451,21 @@ instance EraPlutusTxInfo 'PlutusV4 DijkstraEra where
...
         [minBound ..]
-        (F.toList (txBody ^. outputsTxBodyL))
+        (F.toList ledgerOutputs)
+    let
+      outputHasPtr txOut = case txOut ^. addrTxOutL of
+        Addr _ _ (StakeRefPtr _) -> True
+        _ -> False
+    case F.find outputHasPtr ledgerOutputs of
+      Nothing -> pure ()
+      Just output -> Left $ PointerPresentInOutput output
```
Comment (lehins) [inline eras/dijkstra/impl/src/Cardano/Ledger/Dijkstra/TxInfo.hs]:
```suggestion
    case NE.nonEmpty (filter outputHasPtr ledgerOutputs) of
      Nothing -> pure ()
      Just outputs -> Left $ PointerPresentInOutput outputs
```

**Review by lehins — APPROVED** [review]
Very nice!!! Just one important comment and is good to go
