### PR TITLE
Fix MultiAsset CDDL spec in Mary and Alonzo

### LINKED ISSUE #5077: Incorrrect `value`/`multiasset` for conway CDDL
The Mary CDDL spec for multiasset uses non-empty maps:
https://github.com/IntersectMBO/cardano-ledger/blob/12acadc5bf352d8a5ad3c9b982204207278cdc90/eras/mary/impl/cddl-files/mary.cddl#L121

In Alonzo & Babbage, empty maps are allowed:
https://github.com/IntersectMBO/cardano-ledger/blob/12acadc5bf352d8a5ad3c9b982204207278cdc90/eras/babbage/impl/cddl-files/babbage.cddl#L150

In Conway, `multiasset` is again restricted to non-empty maps, but transactions can still contain outputs with empty `multiasset`s. Strictly speaking, `value` allows for empty `multiassets` while the CDDL spec does not.

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Closes #5077 

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [ ] ~~Tests added or updated when needed.~~
- [ ] ~~`CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).~~
- [ ] ~~Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).~~
- [ ] ~~Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).~~
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

**Review by neilmayhew — CHANGES_REQUESTED** [review]
This seems to me to reflect accurately what the decoder does for pre-Conway eras.

I see that if a `multiasset` is decoded with an empty inner map the outer map entry is pruned during decoding so that we won't have an irregular value in memory. However, there's nothing to stop an irregular value being created in code and then serialized, so irregular `multiasset`s can be both sent and received.

As Tim said, it's important that empty outer maps are allowed, because that's the only way to indicate an empty mint field. Therefore you need to change the `multiasset` definition in Conway's CDDL to reflect that, since currently it uses `+`, `+` and should use `*`, `+`.

**Review by neilmayhew — APPROVED** [review]

File: eras/mary/impl/testlib/Test/Cardano/Ledger/Mary/CDDL.hs [hunk 1]
```diff
@@ -37,7 +37,7 @@ multiasset :: IsType0 a => a -> GRuleCall
 multiasset =
   binding $ \x ->
     "multiasset"
-      =:= mp [1 <+ asKey policy_id ==> mp [1 <+ asKey asset_name ==> x]]
+      =:= mp [0 <+ asKey policy_id ==> mp [0 <+ asKey asset_name ==> x]]
```
Comment (lehins) [inline eras/mary/impl/testlib/Test/Cardano/Ledger/Mary/CDDL.hs]: I do not agree that this reflects the reality accurately. The fact that we prune empty maps in pre-Conway eras was simply an inaccurate approach to solving this problem of nested non-empty maps. The intention is to not have empty inner maps, otherwise outer map will also be removed. This intention should be reflected in the CDDL, not the fact that decoder does not fail.
```suggestion
      =:= mp [0 <+ asKey policy_id ==> mp [1 <+ asKey asset_name ==> x]]
```
Outer map, however, was allowed to be empty, that was another oversight that we fixed in Conway

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/CDDL.hs [hunk 2]
```diff
@@ -824,7 +825,7 @@ invalid_hereafter = "invalid_hereafter" =:~ grp [5, a slot_no]
 multiasset :: IsType0 a => a -> GRuleCall
 multiasset = binding $ \x ->
   "multiasset"
-    =:= mp [1 <+ asKey policy_id ==> mp [1 <+ asKey asset_name ==> x]]
+    =:= mp [0 <+ asKey policy_id ==> mp [1 <+ asKey asset_name ==> x]]
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/CDDL.hs]: This is also not accurate: 
https://github.com/IntersectMBO/cardano-ledger/blob/ca8d451bbce11dde3b68e99782c79f9b4c1dfca5/eras/mary/impl/src/Cardano/Ledger/Mary/Value.hs#L328

It will never happen in Conway that an empty multi asset is decoded.
```suggestion
    =:= mp [1 <+ asKey policy_id ==> mp [1 <+ asKey asset_name ==> x]]
```
See this two:
* Empty outer map is not allowed in mint field: https://github.com/IntersectMBO/cardano-ledger/blob/ca8d451bbce11dde3b68e99782c79f9b4c1dfca5/eras/conway/impl/src/Cardano/Ledger/Conway/TxBody.hs#L188
* In `Value` when multi-asset is present it also will have to be non-empty: https://github.com/IntersectMBO/cardano-ledger/blob/ca8d451bbce11dde3b68e99782c79f9b4c1dfca5/eras/mary/impl/src/Cardano/Ledger/Mary/Value.hs#L294-L298

**Review by lehins — CHANGES_REQUESTED** [review]
This PR makes CDDL even more wrong than it was :sweat_smile: 

@neilmayhew This comment is incorrect:
> As Tim said, it's important that empty outer maps are allowed, because that's the only way to indicate an empty mint field.

Tim is wrong in saying that it is the only way to indicate an empty field. Mint field is optional in the `TxBody`, so that is the way we specify that mint field is empty in Conway era. In pre-conway eras decoders were wrong and there was two ways to specify an empty mint field: 
* not supply the field
* specify the field with an empty Map.

File: eras/mary/impl/testlib/Test/Cardano/Ledger/Mary/CDDL.hs (hunk 1 above)
Comment (neilmayhew) [reply eras/mary/impl/testlib/Test/Cardano/Ledger/Mary/CDDL.hs]: My mistake was thinking only about the `MultiAsset` decoder itself, and having the CDDL reflect what it's capable of encoding and decoding. However, as you point out, the encoders for `AlonzoTxBody` and `MaryValue` override the behaviour by omitting the field when the map is empty, which isn't a property of `MultiAsset` itself but of how its used. We want the CDDL to reflect this, but the only way to do that is to specify it in the definition of `MultiAsset`.

Comment (neilmayhew) [reply eras/mary/impl/testlib/Test/Cardano/Ledger/Mary/CDDL.hs]: I also wasn't thinking about the fact that in CBOR fields can be missing even when the type of the field isn't a `Maybe`

**Review by lehins — APPROVED** [review]
Looks good!
Thank you!
