### PR TITLE
Plutus V2 to fail phase 1 validation on Byron addr

### LINKED ISSUE #2612: fail phase 1 validation on the presence of byron addresses
Byron addresses are current ignored by Plutus, in the sense that they are not a part of the context passed to Plutus. We would prefer to have the transaction fail phase 1 validation in the event that a transaction contains both a plutus script and any byron addresses (both inputs and outputs).

### PR DESCRIPTION
**Pull request by JaredCorduan**
In Plutus V1, we do not pass Byron addresses to the transaction context which is passed to Plutus, they are silently omitted. This includes both transaction inputs and outputs. Starting at major protocol version 7, we want to instead cause a phase 1 validation error instead. This PR does exactly that.

Additionally, this PR introduces a policy change for the `TxInfo` creation code: any time it sees something it can't deal with it forces a phase 1 validation error instead of ignoring it. In particular, two new logic errors are introduced, one for unknown transaction inputs (this is a logic error since the ledger already checks this) and one for unknown redeemer pointers (also something that the ledger already checks).

Note that with the introduction of the babbage, it will probably not make sense for alonzo to have logic for Plutus V2. This is because the Plutus V2 context will probably contain a new field, namely reference inputs (as opposed to just combining them with the usual inputs). We can adapt accordingly when the time comes.

closes #2612

### CODE REVIEW

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs [hunk 1]
```diff
@@ -195,13 +218,13 @@ txInfoIn ::
...
 txInfoIn (UTxO mp) txin =
   case SplitMap.lookup txin mp of
-    Nothing -> Nothing
-    Just txout -> case transTxOutAddr txout of
-      Just ad -> Just (PV1.TxInInfo (txInfoIn' txin) (PV1.TxOut ad valout dhash))
-      Nothing -> Nothing
+    Nothing -> Left TranslationLogicErrorInput
+    Just txout -> case transTxOutAddr txout ByronInputInContext of
+      Right ad -> Right (PV1.TxInInfo (txInfoIn' txin) (PV1.TxOut ad valout dhash))
+      Left err -> Left err
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs]: I think it would be clearer to leave `transTxOutAddr` function as is and make it return `Nothing`, while at call sites:
```suggestion
    Just txout -> case transTxOutAddr txout of
      Just ad -> Right (PV1.TxInInfo (txInfoIn' txin) (PV1.TxOut ad valout dhash))
      Nothing -> Left ByronInputInContext
```

Reason for this suggestion is `transTxOutAddr` can fail for one reason only, thus supplying an error to it is counterproductive and just adds complexity.

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs [hunk 2]
```diff
@@ -127,15 +147,18 @@ transCred (KeyHashObj (KeyHash kh)) =
 transCred (ScriptHashObj (ScriptHash kh)) =
   PV1.ScriptCredential (PV1.ValidatorHash (PV1.toBuiltin (hashToBytes kh)))
 
-transAddr :: Addr crypto -> Maybe PV1.Address
-transAddr (Addr _net object stake) = Just (PV1.Address (transCred object) (transStakeReference stake))
-transAddr (AddrBootstrap _bootaddr) = Nothing
+transAddr :: Addr crypto -> TranslationError -> Either TranslationError PV1.Address
+transAddr (Addr _net object stake) _ = Right (PV1.Address (transCred object) (transStakeReference stake))
+transAddr (AddrBootstrap _bootaddr) err = Left err
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs]: As suggested in another comment, it is more idiomatic to return `Maybe` instead of passing an error as an argument

```suggestion
transAddr :: Addr crypto -> Maybe PV1.Address
transAddr (Addr _net object stake) = Just (PV1.Address (transCred object) (transStakeReference stake))
transAddr (AddrBootstrap _bootaddr) = Nothing
```

It is always possible to `maybe (Left err) Right . transAddr`

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs [hunk 3]
```diff
@@ -127,15 +147,18 @@ transCred (KeyHashObj (KeyHash kh)) =
...
 
-transTxOutAddr :: Era era => TxOut era -> Maybe PV1.Address
-transTxOutAddr txOut = do
+transTxOutAddr :: Era era => TxOut era -> TranslationError -> Either TranslationError PV1.Address
+transTxOutAddr txOut err = do
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs]:
```suggestion
transTxOutAddr :: Era era => TxOut era -> Maybe PV1.Address
transTxOutAddr txOut = do
```

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs [hunk 4]
```diff
@@ -127,15 +147,18 @@ transCred (KeyHashObj (KeyHash kh)) =
...
   -- filter out Byron addresses without uncompacting them
-  Nothing <- Just (getTxOutBootstrapAddress txOut)
-  transAddr $ getTxOutAddr txOut
+  case getTxOutBootstrapAddress txOut of
+    Just _ -> Left err
+    -- The Nothing case will not actually return Left, since the presence
+    -- of a Byron address is caught above in the Just case
+    Nothing -> transAddr (getTxOutAddr txOut) err
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs]:
```suggestion
  case getTxOutBootstrapAddress txOut of
    Just _ -> Nothing
    -- The presence of a Byron address is caught above in the Just case
    Nothing -> transAddr (getTxOutAddr txOut) err
```

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs [hunk 5]
```diff
@@ -218,13 +241,13 @@ txInfoOut ::
...
+  Either TranslationError PV1.TxOut
 txInfoOut txout =
   let val = getField @"value" txout
       datahash = getField @"datahash" txout
-   in case transTxOutAddr txout of
-        Just ad -> Just (PV1.TxOut ad (transValue @(Crypto era) val) (transDataHash datahash))
-        Nothing -> Nothing
+   in case transTxOutAddr txout ByronOutputInContext of
+        Right ad -> Right (PV1.TxOut ad (transValue @(Crypto era) val) (transDataHash datahash))
+        Left err -> Left err
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs]:
```suggestion
   in case transTxOutAddr txout of
        Just ad -> Right (PV1.TxOut ad (transValue @(Crypto era) val) (transDataHash datahash))
        Nothing -> Left ByronOutputInContext
```

**Review by lehins — CHANGES_REQUESTED** [review]
One recommendation, otherwise looks great.

**Comment by JaredCorduan** [comment]
@lehins your suggestion was great, thanks!

**Review by lehins — APPROVED** [review]
