### PR TITLE
Fix enacted `Set` in `GovInfoEvent`

### LINKED ISSUE #4602: `GovInfoEvent` incorrectly reports removed as enacted
Currently `GovInfoEvent` event reports all the removed siblings of enacted actions also as enacted, instead of just removed from the state.

That could lead to confsuing bugs downstream from ledger and therefore need ot be fixed by adding a new field to the event that records removal of conflicting proposals.

### PR DESCRIPTION
**Pull request by lehins**
# Description

Fix #4602

Besides the fix to `GovInfoEvent` this PR also:
* Reduced duplication by consolidating to one implementation for generating uniform sub-Map and the same for uniform sub-Set. Three alternative implementations have been removed
* Fixes implementation of `uniformSubset`. It had a really dumb bug (CC @neilmayhew see if you can spot this bug that I made in a very similar funciton :smile:)

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Arbitrary.hs [hunk 1]
```diff
@@ -259,22 +265,41 @@ instance
...
   arbitrary = do
     ps <- genProposals @era (2, 50)
+    let gasHasNoLineage gas =
+          case gasAction gas of
+            InfoAction {} -> True
+            TreasuryWithdrawals {} -> True
+            _ -> False
+        hasNoLineage gaId =
+          case proposalsLookupId gaId ps of
+            Nothing -> error $ "Expected " ++ show gaId ++ " in genertaed proposals"
```
Comment (teodanciu) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Arbitrary.hs]:
```suggestion
            Nothing -> error $ "Expected " ++ show gaId ++ " in generated proposals"
```

File: libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs [hunk 2]
```diff
@@ -633,12 +634,33 @@ uniformSubset mSubSetSize inputSet gen = do
       | i <= 0 = pure acc
       | otherwise = do
           ix <- uniformRM (0, Set.size s - 1) gen
-          go (Set.insert (Set.elemAt ix s) acc) (Set.deleteAt ix s) (i - 1)
+          go (Set.deleteAt ix s) (Set.insert (Set.elemAt ix s) acc) (i - 1)
```
Comment (teodanciu) [inline libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs]: Wow!  So was the generated set always empty, because it wasn't accumulating anything?

File: libs/cardano-ledger-core/CHANGELOG.md [hunk 3]
```diff
@@ -5,6 +5,11 @@
 * Add `credKeyHash` to `Credential`
 * Remove `maxMajorPV` from `Globals`
 
+### `testlib`
+
+* Add `uniformSubMap`
```
Comment (teodanciu) [inline libs/cardano-ledger-core/CHANGELOG.md]:
```suggestion
* Add `uniformSubMap` and `uniformSubMapElems`
```

File: libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs [hunk 4]
```diff
@@ -615,30 +617,89 @@ genValidUMapNonEmpty = do
...
+  -- | Size of the subMap. If supplied will be clamped to @[0, Map.size s]@ interval,
+  -- otherwise will be generated randomly.
+  Maybe Int ->
+  Map k v ->
+  g ->
+  m f
+uniformSubMapElems insert mSubMapSize inputMap gen = do
+  subMapSize <- case mSubMapSize of
+    Nothing -> uniformRM (0, Map.size inputMap) gen
+    Just n -> pure $ max 0 $ min (Map.size inputMap) n
```
Comment (teodanciu) [inline libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs]: Would it make sense to extract this logic of determining the size of a the subset/submap, since it appears three times?

```
getSubSize ::StatefulGen g m =>
  Maybe Int ->
  Int ->
  g ->
  m  Int
getSubSize mSubSetSize inputSize gen = do
  case mSubSetSize of
    Nothing -> uniformRM (0, inputSize) gen
    Just n -> pure $ max 0 $ min inputSize n
```

And then this would become: 

```suggestion
subMapSize <- getSubSize mSubMapSize (Map.size inputMap) gen
```

Similar for the other two functions, `uniformSubMap` and `uniformSubSet`

File: libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs [hunk 5]
```diff
@@ -615,30 +617,89 @@ genValidUMapNonEmpty = do
...
+  go inputMap mempty subMapSize
```
Comment (teodanciu) [inline libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs:699]: How come for `uniformSubMap` we don't build the result differently based on the number of elements? Is it because we know that the property (Constructing a new Set is faster when less then a half of original Set will be used)  holds for Set and Map, but we don't know for `f` ?

**Review by teodanciu — APPROVED** [review]
Looks good to me, just some questions and minor suggestions.

File: libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs (hunk 5 above)
Comment (lehins) [reply libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs:699]: > How come for uniformSubMap we don't build the result differently based on the number of elements?

We actually do build them differently for `uniformSubMap`, the same way it is done for `uniformSubSet`. We can't do the same for `uniformSubMapElems`, because we do not know the final data structure. Especially in case of final data structure being an ordered structure like a list, we can no longer use the approach of deleting random elements from a Map, because the resulting list would be sorted by keys. We do need to have a list containing elements in a random order, which is what picking random elements out of a Map provides for us by default.

File: libs/cardano-ledger-core/CHANGELOG.md (hunk 3 above)
Comment (lehins) [reply libs/cardano-ledger-core/CHANGELOG.md]: Thank you!

File: libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs (hunk 5 above)
Comment (teodanciu) [reply libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs:699]: Ah sorry, I meant `uniformSubMapElems`, thank you for answering the question that I meant to ask instead the one i actually asked :grin:

File: libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs (hunk 4 above)
Comment (lehins) [reply libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs]: Very nice. I really like this suggestion. Applied.

File: libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs (hunk 2 above)
Comment (lehins) [reply libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs]: Kind of, half the time at least :smile: 

Depending if the requested size was even or odd it would either produce an empty Set or a the full original Set with a single random element removed from it.
