### PR TITLE
Fail fast when adding a redundant transaction to the mempool

### LINKED ISSUE #1294: Distinguish error cases for same tx vs other tx spent some inputs
This is just an idea for now...

It may be helpful for wallets (and similar clients) that need to re-submit txs for them to be able to get a distinction in the error they get when they submit a duplicate transaction.

Why can this happen? If a wallet notices a tx has been pending for too long, it can try to resubmit it. What outcomes can it expect? It may be that the tx is simply invalid, or that an input was spent by another transaction. It may be that the tx is still in the local mempool or that the tx has in fact made it into the chain. Wallets would like to distinguish the last two cases from the case that an input was spent by another transaction. Currently that is not possible, at least not just from the error reported by the ledger.

Right now, in Byron and Shelley ledgers, if you submit a duplicate tx then the failure you get is that one of the inputs has been spent already. Would it be possible -- without it being too expensive -- to establish if it's not just that some of the inputs were spent, but that all of them were spent and by the same txid as we are validating?

Perhaps this is not possible in general, because the UTxO does not keep that information. But perhaps there are common special cases where it is possible? Assume the special case that the tx being resubmitted is already in the ledger, and that not all of its outputs have themselves yet been spent (typically none yet spent). The UTxO is indexed by the (txid, ix) pair, but since it is an ordered map we can still do a map range lookup for any (txid, _) pair in the utxo, in log time. That lets us test if a specific txid is still in the utxo. If it is, we can confidently say that this is a duplicate, and not merely that some inputs were already spent.

Perhaps it does not want to be in the ledger validation itself, but available as a test that the mempool validation could use, just for the local client case, to more helpfully report distinguished failures.

### LINKED ISSUE #4849: Fast-failure for redundant transactions in the mempool
The design of the TxSub mini protocol would be simplified if it were effectively costless for the mempool to reject redundant transactions.

This task is to ensure that in the MEMPOOL rule.

### PR DESCRIPTION
**Pull request by neilmayhew**
# Description

Closes #1294
Closes #4849

# Checklist

- [x] Commits in meaningful sequence and with useful messages.
- [x] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [x] Self-reviewed the diff.

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs [hunk 1]
```diff
@@ -100,24 +102,42 @@ mempoolTransition ::
...
-    unelectedCommitteeVoters =
-      Map.foldlWithKey' collectUnelectedCommitteeVotes Set.empty $
-        unVotingProcedures (tx ^. bodyTxL . votingProceduresTxBodyL)
-    addPrefix =
-      ("Unelected committee members are not allowed to cast votes: " <>)
-  failOnNonEmpty unelectedCommitteeVoters $
-    ConwayMempoolFailure . addPrefix . T.pack . show . NE.toList
-  trans @(EraRule "LEDGER" era) $ TRC trc
+    inputs = tx ^. bodyTxL . inputsTxBodyL
+    utxo = ledgerState ^. utxoG . to unUTxO
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: This is slightly simpler
```suggestion
    UTxO utxo = ledgerState ^. utxoG
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs [hunk 2]
```diff
@@ -100,24 +102,42 @@ mempoolTransition ::
...
+    unspent = (`Map.member` utxo)
+    msg = "All inputs are spent. Transaction has probably already been included"
+  any unspent inputs ?! ConwayMempoolFailure msg
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: I believe this will be slightly more efficient for any transaction with more than two inputs and a bit more clear, at least in my personal opinion
```suggestion
    allInputsAreUnspent = Map.size (utxo `Map.restrictKeys` inputs) == Set.size inputs
    msg = "All inputs are spent. Transaction has probably already been included"
  allInputsAreUnspent ?! ConwayMempoolFailure msg
```
Also I think you meant to do `all unspent inputs`, instead of `any unspent inputs`.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs [hunk 3]
```diff
@@ -100,24 +102,42 @@ mempoolTransition ::
 mempoolTransition = do
   TRC trc@(_ledgerEnv, ledgerState, tx) <-
     judgmentContext
+
   -- This rule only gets invoked on transactions within the mempool.
   -- Add checks here that sanitize undesired transactions.
+
+  let whenFailureFree' action = ifFailureFree action (pure ledgerState)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: I think it would be nice to add such function to the `small-steps` instead of having just one here locally (also I hate ticks :smile:):
```haskell
whenFailureFreeDefault :: a -> Rule sts rtype a -> Rule sts rtype a
whenFailureFreeDefault defValOnFailure actionOnNoFailure =
  ifFailureFree actionOnNoFailure (pure defValOnFailure)
```

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs [hunk 4]
```diff
@@ -100,24 +102,42 @@ mempoolTransition ::
...
-  trans @(EraRule "LEDGER" era) $ TRC trc
+    inputs = tx ^. bodyTxL . inputsTxBodyL
+    utxo = ledgerState ^. utxoG . to unUTxO
+    unspent = (`Map.member` utxo)
+    msg = "All inputs are spent. Transaction has probably already been included"
+  any unspent inputs ?! ConwayMempoolFailure msg
+
+  -- Skip all other checks if the transaction is probably a duplicate
+  whenFailureFree' $
+    do
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: Please try to avoid this style. I am trying to promote somewhat consistent Haskell style in the codebase, this would be one that is inconsistent.
```suggestion
  whenFailureFreeDefault ledgerState $ do
```
Also this has my other suggestion applied.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs [hunk 5]
```diff
@@ -212,9 +212,30 @@ spec = do
...
+
+    it "Duplicate transactions" $ do
+      inputs <- replicateM 10 $ do
+        addr <- freshKeyAddr_
+        amount <- Coin <$> choose (2_000_000, 8_000_000)
+        sendCoinTo addr amount
+      tx <- submitTx $ mkBasicTx $ mkBasicTxBody & inputsTxBodyL <>~ fromList inputs
+      submitFailingMempoolTx "duplicate transaction" tx $
+        pure . ConwayMempoolFailure $
+          "All inputs are spent. Transaction has probably already been included"
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: Can you also add here a test that submits this transaction:
```haskell
input <- elements inputs
submitFailingTx $ mkBasicTx $ mkBasicTxBody & inputsTxBodyL <>~ Set.singleton input
```

**Review by lehins — CHANGES_REQUESTED** [review]
Few minor changes are still needed, but other than that it looks great. Thank you!

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 2 above)
Comment (neilmayhew) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: The logic is confusing, and I agree that the code doesn't make it any better. It's not helped by the fact that the meaning of the `?!` operator is backwards to the way programmers think (even if it is forward to mathematicians).

We want to fail here if all the inputs are spent, so that the remaining rules are skipped. We therefore want to succeed here if at least one of the inputs is unspent. The condition before `?!` therefore needs to be `any unspent`.

Using `restrictKeys` could be a big performance improvement, as you say, although the condition on the result needs to be `not . null`, meaning that not all the inputs are gone from the UTxO, ie some are unspent.

However, in the most common case, none of the inputs will be spent, so the first `member` of `any unspent` will succeed, which will give an overall cost of $$O\left(\log(n)\right)$$. Using `restrictKeys` involves looking at all the inputs, and the documentation says the cost is $$O\left(m\log\left(\frac{n}{m}+1\right)\right)$$ which is significantly greater when $$m>1$$. Eg, if $$m=2$$, the cost is $$O\left(2\log\left(\frac{n}{2}+1\right)\right) = O\left(\log\left(\frac{n^2}{4}+n+1\right)\right) = O\left(\log\left(n^2\right)\right)$$.

This reasoning probably isn't conclusive, though, because of constant factors, etc., and we'd need to benchmark to be sure. Even so, I'm pretty sure `restrictKeys` has to do a fair bit of memory allocation whereas `member` does none.

I'll try to make the logic clearer by putting the condition in a variable called `notAllSpent = any unspent inputs`

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 3 above)
Comment (neilmayhew) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: Great idea!

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 4 above)
Comment (neilmayhew) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: I did it that way because I thought `fourmolu` would change it, but apparently it's OK with yours. Thanks for catching this. I too prefer it your way.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 5 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I've added that, although another approach would be to make the number of inputs in the first test `choose (1, 10)` (or `choose (1, 5)` if we want to increase the frequency of `1`).

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 2 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: I understand why you are confused, it took me the longest time to think in terms of `!?`. It is essentially akin to `unless` and I also blame those mathematicians for forcing it on us :grin: 
However, your logic is incorrect and the test you added by my suggestion is the proof of it. We shall succeed and, therefore not short-circuit the validation only when *all* of the inputs are still unspent. So, that is the succeeding condition!
If at least one of the inputs (i.e. what you have implemented) is missing, we need to continue with validation and let the UTXO rule do its thing.

With respect to performance. In theory, since we do need to check *all* inputs it should be faster with `restrictWith` due to `O(n*log(n/m + 1)` complexity, instead of `O(n*log(m))` with `member`, especially due to the fact that in our case `n` is very big
I do, however, agree with potential overhead of allocations and benchmarks would be the ultimate truth about performance of this operation. So, curiosity got the better of me and I implemented such benchmarks: https://github.com/lehins/haskell-benchmarks/blob/master/containers-benchmarks/bench/Bench.hs

Spoiler alert `all (\s -> Map.members m)` is always faster than `Map.size (Map.restrictKeys m s) == Set.size s`, regardless of how big the original map is.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 5 above)
Comment (lehins) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: That's fine. One is enough to prove the correctness

File: libs/small-steps/src/Control/State/Transition/Extended.hs [hunk 6]
```diff
@@ -51,6 +51,7 @@ module Control.State.Transition.Extended (
   labeledPredE,
   ifFailureFree,
   whenFailureFree,
+  whenFailureFreeDefault,
```
Comment (lehins) [inline libs/small-steps/src/Control/State/Transition/Extended.hs:54]: This needs a changelog entry and a minor bump in version.
Also `cardano-ledger-conway` will need a lower bound update on `small-steps`, since it now requires this function

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs [hunk 7]
```diff
@@ -212,9 +212,35 @@ spec = do
...
+      input <- elements inputs
+      let tx1 = mkBasicTx $ mkBasicTxBody & inputsTxBodyL <>~ [input]
+      submitFailingMempoolTx "duplicate transaction" tx1 $
+        pure . ConwayMempoolFailure $
+          "All inputs are spent. Transaction has probably already been included"
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: So, this is the proof that your logic in the MEMPOOL rule is incorrect.

This test must produce `BadInputsUTxO (Set.singleton inputs)` predicate failure, not a `ConwayMempoolFailure` failure, because only one input is missing, not all of them.

**Review by lehins — CHANGES_REQUESTED** [review]
Thank you for a good argument, but we still need to fix the mempool rule

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 2 above)
Comment (neilmayhew) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: I'm still not convinced what you're saying is correct. However, I've changed the logic as you've requested, and I've added another test. This one submits a second transaction that has 5 inputs in common with the first one and 5 that are different. I don't think this fits the idea of "duplicate" or "redundant" transaction that the OPs had in mind, but with your logic it returns "Probably already included" rather than `BadInputsUTxO` and a bunch of other failures. (My original logic does the latter.)

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 7 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I agree that it should do that, but with the current strategy of checking the spend status of the inputs there isn't any way to distinguish between a transaction that is trying to spend _some_ of the inputs of a preceding transaction or _all_ of them, since we look only at the inputs of the current transaction, not the inputs of a preceding one. In fact, I'm not sure, given an output that's no longer in the UTxO, there's any way to find out which transaction spent it.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 2 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: You are absolutely right. Those mathematicians as always confused the hell out of me.
The way I had to convince myself that you are right was to focus on what is the failing case, not the successful one.
In other words `Probably already included` failure should be produced when:

* `all (\input -> not (Map.member input utxo)) inputs`

Which means the successful case is the negation of it:

* `not (all (\input -> not (Map.member input utxo)) inputs)`

Which by DeMorgan's law is the same as:

* `any (\input -> Map.member input utxo) inputs)`

Sorry for doubting you.

The thing that really confused me was the test that I suggested:
```haskell
input <- elements inputs
submitFailingTx $ mkBasicTx $ mkBasicTxBody & inputsTxBodyL <>~ Set.singleton input
```
should not have failed with `Probably already included`, because every transaction in ImpSpec gets an extra root input upon fixup, which should have been enough to trigger non-Mempool failure

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 7 above)
Comment (lehins) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: As I mentioned above, your original approach is right. I was confused why in the previous version of your implementation:
```haskell
inputs = tx ^. bodyTxL . inputsTxBodyL
    UTxO utxo = ledgerState ^. utxoG
    notAllSpent = any (`Map.member` utxo) inputs
  notAllSpent
    ?! ConwayMempoolFailure ..
```
this test:
```
 let tx1 = mkBasicTx $ mkBasicTxBody & inputsTxBodyL <>~ [input]
      submitFailingMempoolTx "duplicate transaction" tx1 $
        pure . ConwayMempoolFailure $
```
still resulted in `ConwayMempoolFailure`.

Until I realized that you are not doing the fixup in `submitFailingMempoolTx`, which is wrong in m my opinion

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs [hunk 8]
```diff
@@ -212,9 +212,49 @@ spec = do
...
   describe "Mempool" $ do
+    let
+      submitFailingMempoolTx cause tx expectedFailures = do
+        globals <- use impGlobalsL
+        nes <- use impNESL
+        slotNo <- use impLastTickG
+        let
+          mempoolEnv = mkMempoolEnv nes slotNo
+          ls = nes ^. nesEsL . esLStateL
+        case applyTx globals mempoolEnv ls tx of
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: Make sure you fixup the tx, we need to test transactions that are only invalid for a specific reason, not a whole collection of reasons
```suggestion
        fixedUpTx <- fixupTx tx
        case applyTx globals mempoolEnv ls fixedUpTx of
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs [hunk 9]
```diff
@@ -212,9 +212,49 @@ spec = do
...
+          Left err ->
+            err `shouldBe` ApplyTxError @era (injectFailure <$> expectedFailures)
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: You'll probably need to return it so you can do further testing on the fixed up version when necessary
```suggestion
          Left err -> do
            err `shouldBe` ApplyTxError @era (injectFailure <$> expectedFailures)
            pure fixedUpTx
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs [hunk 10]
```diff
@@ -232,9 +272,6 @@ spec = do
         rewardAccount <- registerRewardAccount
         submitTreasuryWithdrawals [(rewardAccount, Coin 1)]
 
-      nes <- use impNESL
-      let ls = nes ^. nesEsL . esLStateL
-          mempoolEnv = mkMempoolEnv nes slotNo
       tx <-
         fixupTx $
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: This won't be needed with my suggestion above
```suggestion
```

**Review by lehins — CHANGES_REQUESTED** [review]
Your point about the logic in the rule was right. So, reverting my suggestion about it will be the right thing to do. There is one minor thing still need a fix and that is the fixup during transaction submission

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 2 above)
Comment (neilmayhew) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: Ah! I see what you mean about the fixup. I'm using `applyTx` directly so there's no fixup (as you point out in the other thread) but you were expecting this to be an example of an overlapping transaction which it would be if there was a fixup.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 7 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I'll see if I can make it work with fixups. That would reduce the list of predicate failures in the overlapping case.

I was confused by your suggestion of using a single input, because I wasn't thinking about the fixup.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs (hunk 2 above)
Comment (neilmayhew) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Mempool.hs]: I've added a fixup in `submitFailingMempoolTx` but it uses `asks iteFixup` rather than calling `fixupTx` directly, so that the test code can use `withNoFixup` to control whether or not it wants a fixup. The test code ends up needing to do it both ways at different times.

I've also added a more explicit overlapping transaction test, so that it's clearer what's going on, and so that I can more easily produce the list of inputs for the `BadInputsUTxO` failure.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 8 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: As mentioned above, I've added this using `asks iteFixup` so that it can be overridden using `withNoFixup`

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 9 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I couldn't do this because the other case returns `()`. I also found that it wasn't needed.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 10 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I've left this in so I can submit the identical transaction, and because it isn't possible to return it from `submitFailingMempoolTx`

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 7 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I've updated the tests to reflect clearly what we want the two possible outcomes to be. Maybe you can take a final look and check that it matches what you expect.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 9 above)
Comment (neilmayhew) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I'm not sure what I was thinking of when I said that. I've pushed another commit that changes `submitFailingMempoolTx` to return the fixed-up transaction and adjusts the rest of the code accordingly. I don't think I like it quite as much this way, but `submitFailingMempoolTx` is now a better candidate for becoming a shared function in `Test.Cardano.Ledger.Conway.ImpTest`.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs (hunk 10 above)
Comment (lehins) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: It is actually possible. That is the difference between HSpec's [`expectationFailure`](https://hackage.haskell.org/package/hspec-expectations-0.8.4/docs/Test-Hspec-Expectations.html#v:expectationFailure) and HUnit's [`assertFailure`](https://hackage.haskell.org/package/HUnit-1.6.2.0/docs/Test-HUnit-Base.html#v:assertFailure)

Both of them result in bottom, so there is really no reason why it should return `()`. Therefore, whenever you are in the situation like this, use `assertFailure`:
```haskell
case e of
  Left err -> assertFailure err
  Right r -> pure r
```
instead of `expectationFialure`:
```haskell
case e of
  Left err -> expectationFialure err
  Right _ -> pure ()
pure $ fromRight (error "Impossible") e
```

Comment (lehins) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/LedgerSpec.hs]: I see that you already found the `assertFailure` :grin:

**Review by lehins — APPROVED** [review]
Perfect! Thank you!
