### PR TITLE
Check `ppuCoinsPerUTxOBytes` well-formedness

### LINKED ISSUE #4631: Add `ppCoinsPerUTxOByte` to `ppWellFormed`
Looks like there was a mistake in the spec and the wrong parameter was used: https://github.com/IntersectMBO/formal-ledger-specifications/issues/571

We need to add `ppCoinsPerUTxOByte` to `ppWellFormed`, but we have to add it only with the protocol version check, i.e. we can't change this behavior without a hardfork. 
So, despite that guardrails script already checks that `ppCoinsPerUTxOByte` is not equal to `0`, for consistency sake with the spec we need to also implement it on the ledger side.

### PR DESCRIPTION
**Pull request by Lucsanszky**
# Description
Resolves #4631 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/shelley/impl/src/Cardano/Ledger/Shelley/HardForks.hs [hunk 1]
```diff
@@ -71,3 +72,13 @@ bootstrapPhase ::
...
+
+-- | Starting with protocol version 10, we need to check that `ppuCoinsPerUTxOByte` is
+-- non-zero when checking the well-formedness of protocol parameter updates but forgo
+-- this check for earlier versions.
+-- See: https://github.com/IntersectMBO/cardano-ledger/issues/4631
+-- and: https://github.com/IntersectMBO/formal-ledger-specifications/issues/571
+forgoCoinsPerUTxOBytesCheck ::
+  ProtVer ->
+  Bool
+forgoCoinsPerUTxOBytesCheck pv = pvMajor pv < natVersion @10
```
Comment (lehins) [inline eras/shelley/impl/src/Cardano/Ledger/Shelley/HardForks.hs]: Just use `bootstrapPhase` instead of defining a new one
```suggestion
```

Comment (Lucsanszky) [reply eras/shelley/impl/src/Cardano/Ledger/Shelley/HardForks.hs]: Ah, right since we don't have the `ppuWellFormed` check pre-Conway. :+1:

**Review by Soupstraw — APPROVED** [review]
LGTM
