### PR TITLE
Report Plutus `ScriptHash` upon execution failure

### LINKED ISSUE #3731: Report Plutus ScriptHash upon execution failure
Currently we report base64 encoded binary version of the script, but the script hash, which would be useful for debugging.

Add the output of `hashScript` here:
https://github.com/input-output-hk/cardano-ledger/blob/03bad4b6a9522e43257f436d3e0f20b5017328de/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L900

Also improving failure message here
https://github.com/input-output-hk/cardano-ledger/blob/03bad4b6a9522e43257f436d3e0f20b5017328de/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L865
to:
```haskell
firstLines = 
  [ "The " ++ show lang ++ " script failed:"
  , "Base64-encoded script bytes:"
  ]
```

### PR DESCRIPTION
**Pull request by Lucsanszky**
# Description
Resolves #3731 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs [hunk 1]
```diff
@@ -209,17 +211,17 @@ merge f (x : xs) zs = merge f xs (gg x zs)
 
 -- | Evaluate a list of Plutus scripts. All scripts in the list must evaluate to `True`.
 evalPlutusScripts ::
-  EraTx era =>
+  (EraTx era, Crypto c) =>
   Tx era ->
-  [PlutusWithContext] ->
-  ScriptResult
+  [PlutusWithContext c] ->
+  ScriptResult c
```
Comment (lehins) [inline eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs]: `c` and `era` should never appear together, since `EraCrypto era` is always the crypto for the era 
```suggestion
  [PlutusWithContext (EraCrypto era)] ->
  ScriptResult (EraCrypto era)
```

Comment (Lucsanszky) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs]: Ah yes, I was planning to change those since at one point I realised that there is no point in introducing an extra type variable where we already have the `era`, it just seemed redundant. Hence why at certain parts I only used `EraCrypto era` and was about to clean up the rest. But I didn't know that having both is actually discouraged for other reasons than redundancy. Thanks!

By the way, what necessitated the introduction of `EraCrypto` in the first place (given the fact that `Crypto c` already seems extraneous at this point since it is always `Crypto StandardCrypto`)?

Comment (teodanciu) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs]: Not sure if this is what you're asking, but: if you have an `Era era` constraint (or a super class, eg: `EraTx` in this case),  then you have already the `Crypto` type for it, and you reference it with `EraCrypto era`   (https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/conway/impl/src/Cardano/Ledger/Conway/Era.hs#L42)

Comment (teodanciu) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs]: Oh or maybe you're asking why was it necessary to be introduced at all?  Nevermind my comment if so :)

Comment (Lucsanszky) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs]: The latter. :) I was wondering why it was introduced at all. I mean sure, it is more descriptive than the `Crypto c` constraint but still, I was wondering if there were some other reasons.
Regardless, thanks for the clarification regarding the `Era` constraints as well. :)

File: eras/alonzo/test-suite/test/Test/Cardano/Ledger/Alonzo/PlutusScriptExamples.hs [hunk 2]
```diff
@@ -178,6 +179,7 @@ explainTest plutus mode ds =
         PlutusWithContext
           { pwcProtocolVersion = eraProtVerLow @era
           , pwcScript = Left plutus
+          , pwcScriptHash = mkScriptHash @(EraCrypto era) 1
```
Comment (Lucsanszky) [inline eras/alonzo/test-suite/test/Test/Cardano/Ledger/Alonzo/PlutusScriptExamples.hs]: It seems that it might be okay to use a "dummy hash" here. Regardless, I thought that I will point this out and ask if this could cause some issues down the line?

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Examples/AlonzoCollectInputs.hs [hunk 3]
```diff
@@ -105,6 +106,7 @@ collectTwoPhaseScriptInputsOutputOrdering = do
           testSystemStart
           (initUTxO apf)
           (validatingTx apf)
+    scriptHash = ScriptHash "58503a1d89a21fc9fc53d6a7cccef47341175a8f47636f57ccbdca2d"
```
Comment (Lucsanszky) [inline libs/cardano-ledger-test/src/Test/Cardano/Ledger/Examples/AlonzoCollectInputs.hs]: ~Not the most elegant solution and a PITA to maintain if the script changes but I wanted to avoid the `getScriptsNeeded` and `getScriptsHashesNeeded` dance. By the way, is there an easier way to get the hash of the script here? Also, would it make sense to introduce some helpers for hashing the script (if there aren't any already)?~ #4037 :rocket:

**Comment by Lucsanszky** [comment]
I will mark this ready for review once #4037 is merged.

File: libs/cardano-ledger-core/CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,7 @@
 
 ## 1.11.0.0
 
+* Add `pwcScriptHash` field to `PlutusWithContext`
```
Comment (lehins) [inline libs/cardano-ledger-core/CHANGELOG.md:5]:
```suggestion
* Add `pwcScriptHash` field to `PlutusWithContext`
* Parameterize `PlutusWithContext c` on crypto.
```

File: libs/cardano-ledger-core/src/Cardano/Ledger/Plutus/Evaluate.hs [hunk 5]
```diff
@@ -163,34 +162,36 @@ instance EncCBOR PlutusDatums where
...
 
-instance FromCBOR PlutusWithContext where
-  fromCBOR = Plain.decodeRecordNamed "PlutusWithContext" (const 5) $ do
+instance Crypto c => FromCBOR (PlutusWithContext c) where
+  fromCBOR = Plain.decodeRecordNamed "PlutusWithContext" (const 6) $ do
     pwcProtocolVersion <- fromCBOR
     toPlainDecoder pwcProtocolVersion $ decodeWithPlutus $ \plutus -> do
       let lang = plutusLanguage plutus
           pwcScript = Left plutus
+      pwcScriptHash <- decCBOR
```
Comment (lehins) [inline libs/cardano-ledger-core/src/Cardano/Ledger/Plutus/Evaluate.hs:184]: There are two approaches we can take here:
* Either not having script hash in the decoding at all
* or maybe use the encoded one to validate that the hash of the computed one is correct.


This type is only ever encoded for debugging, so we don't need to worry about efficiency here, therefore I think validation is the way to go:
```suggestion
      pwcScriptHash <- decCBOR
      unless (pwcScriptHash == hasPlutusScript plutus) $ 
        fail $ "ScriptHash mismatch. Encoded: " <> show pwcScriptHash <> 
          " doesn't match the actual: " <> show (hasPlutusScript plutus)
```

**Review by lehins — APPROVED** [review]
Perfect!
Thank you!

File: eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs (hunk 1 above)
Comment (lehins) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs]: > I was wondering why it was introduced at all.

We were discussing just that on Wednesday meeting. :smile: 

I suspect there was two reasons:
* Ability to use different crypto algortihms  during testing. Which is sort of helpful for VRF, but not at all for hashes and signing algorithms
* Assumption that it would be more versatile, which proved to be incorrect.

In other words,  this is the decision that was made early on and now we are stuck with it. But, maybe we'll be able to get rid of it in the future. I have a descent plan on how it can be made possible.

Comment (Lucsanszky) [reply eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs]: > I suspect there was two reasons:
> 
>     * Ability to use different crypto algortihms  during testing. Which is sort of helpful for VRF, but not at all for hashes and signing algorithms
> 
>     * Assumption that it would be more versatile, which proved to be incorrect.

~But the above is about the `Crypto` constraint, right? I remember we were discussing that. I was wondering about the history behind `EraCrypto`. Was it introduced for convenience?~ Never mind! I did some more reading and see that `EraCrypto` was just a rename from `Crypto`. All is clear now, thanks!
