### PR TITLE
Change the balance in `InsufficientCollateral` to `DeltaCoin`

### LINKED ISSUE #4198: DeserialiseFailure on resubmitting Conway Tx with invalid plutus script
I'm getting following `DeserialiseFailure` when trying to resubmit a Tx with invalid Plutus script in Conway era:

> cardano-cli: DecoderFailure (LocalTxSubmission (GenTx (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) (HardForkApplyTxErr (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) ServerAgency TokBusy) (DeserialiseFailure 68 "expected word")

I'm testing this with `cardano-node` / `cardano-cli` 8.9.0 release.

UPDATE: It is somehow related to return collateral. If collateral utxos have the precise collateral amount, then no return collateral txout is needed. In such case, resubmitting the tx leads to the expected `BadInputsUTxO`, instead of the unexpected `DecoderFailure`.

Steps to reproduce:

1. build
> cardano-cli conway transaction build --tx-in "745f04573e7429be1404f9b936d208b81159f3fc4b30037b9d630187eec18756#0" --tx-in-script-file cardano_node_tests/tests/data/plutus/v1/always-fails.plutus --tx-in-datum-file cardano_node_tests/tests/data/plutus/typed-42.datum --tx-in-redeemer-file cardano_node_tests/tests/data/plutus/typed-42.redeemer --tx-in-collateral "745f04573e7429be1404f9b936d208b81159f3fc4b30037b9d630187eec18756#1" --tx-in "745f04573e7429be1404f9b936d208b81159f3fc4b30037b9d630187eec18756#2" --tx-out "addr_test1vr7l4ff9r60dyxr22thw5pdvr5ucxnhw7zdnuswuz52h0gqy8q9yn+2000000" --script-invalid --change-address addr_test1vrlfyrycpk7pzyaqrkcp2624g70nhy0kld49r0wqcwpurwgcmxy52 --out-file test_script_invalid_ci0_hmg_step2_tx.body --testnet-magic 42

2. sign
> cardano-cli conway transaction sign --tx-body-file test_script_invalid_ci0_hmg_step2_tx.body --testnet-magic 42 --signing-key-file test_script_invalid_ci0_glp_payment_addr_0.skey --signing-key-file test_script_invalid_ci0_glp_payment_addr_1.skey --out-file test_script_invalid_ci0_hmg_step2_tx.signed

3. submit
> cardano-cli conway transaction submit --testnet-magic 42 --tx-file test_script_invalid_ci0_hmg_step2_tx.signed --cardano-mode

4. resubmit to see if the tx made it to mempool. Expected behavior is to get `BadInputsUTxO`, but this time we get the `DecoderFailure`.

Files used in the test:
[deserialize_failure.tar.gz](https://github.com/IntersectMBO/cardano-ledger/files/14588210/deserialize_failure.tar.gz)

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR fixes a bug with the deserialisation of the `InsufficientCollateral` predicate failure. In a case where the collateral returns are greater than the collateral inputs, the balance in that failure can become negative. This PR changes the type of the balance field in that transaction to `DeltaCoin` so that the failure can still be deserialised in such cases.

fixes  #4198

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxos.hs [hunk 1]
```diff
@@ -288,11 +289,13 @@ babbageEvalScriptsTxInvalid = do
   {- utxoDel  = txBody ^. collateralInputsTxBodyL ◁ utxo -}
   let !(utxoKeep, utxoDel) = extractKeys (unUTxO utxo) (txBody ^. collateralInputsTxBodyL)
       UTxO collouts = collOuts txBody
-      collateralFees = collAdaBalance txBody utxoDel -- NEW to Babbage
+      -- The collateral balance shouldn't be negative at this point, otherwise
+      -- it would have failed in phase 1
```
Comment (lehins) [inline eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxos.hs]: This isn't exactly correct because this is also phase 1 and also we do not short circuit on validation failures. So, it can be negative, but there will be phase 1 validation failure when that is the case. 

I am not quite sure if we should rephrase this comment or just remove it altogether.
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Regression.hs [hunk 2]
```diff
@@ -19,7 +54,7 @@ spec ::
   Spec
 spec = describe "Regression" $ do
   it "DeserialiseFailure on resubmitting Conway Tx with invalid plutus script #4198" $ do
-    expectRightDeep_ $
+    Common.expectRightDeep_ $
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Binary/Regression.hs]: You can do this (or `it "foo" $ io $ do ...`), if you want to avoid importing `Common` as qualified 
```suggestion
    io $ expectRightDeep_ $
```

**Review by lehins — APPROVED** [review]
Looks great. We just need to wait for #4241 to get merged and this one will be good to go.
