### PR TITLE
Fail PParamsUpdate deserialization for invalid costmodels in Conway

### LINKED ISSUE #3772: Prevent CostModels for known languages to be decoded in PParamsUpdate
* For language versions that we know, we prevent invalid ones in PParamUpdates in the governance proposals.
* For the unknown ones we do what is currently implemented

It is important that this behavior is only changed for `PParamsUpdate`, not for `PParams`

So, I suggest we do not change `CostModels` `DecCBOR` instance, which would still allow invalid CostModels for languages that are available, but have a special decoder function that is used for `CostModels` in `PParamsUpdate` that prevents invalid `CostModels` for languages that we already support

I am also contemplating to use different types for those two concepts, but I am not sure yet how hard that would be to implement

### PR DESCRIPTION
**Pull request by teodanciu**
# Description

Closes https://github.com/input-output-hk/cardano-ledger/issues/3772

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs [hunk 1]
```diff
@@ -677,7 +678,7 @@ updateField = \case
   11 -> field (\x up -> up {cppTau = THKD (SJust x)}) From
   16 -> field (\x up -> up {cppMinPoolCost = THKD (SJust x)}) From
   17 -> field (\x up -> up {cppCoinsPerUTxOByte = THKD (SJust x)}) From
-  18 -> field (\x up -> up {cppCostModels = THKD (SJust x)}) From
+  18 -> field (\x up -> up {cppCostModels = THKD (SJust x)}) $ D decodeCostModelsFailingOnError
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs]: This is an incorrect function to use, because `decodeCostModelsFailingOnError` will fail for unknown languages, which is not what we want.

We want PParamsUpdate to fail whenever there is a CostModel for a known language that is invalid, but it should still succeed whenever the CostModel is for a language that we don't know about. 

In particular this is the line that is wrong for this decoder, but it is ok for PParams: https://github.com/input-output-hk/cardano-ledger/blob/c8874b4ae6ef569d28f492dc6d948bfdc607a3ef/libs/cardano-ledger-core/src/Cardano/Ledger/Plutus/CostModels.hs#L341

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 2]
```diff
@@ -0,0 +1,183 @@
...
+
+checkValidCostModelDecoder ::
+  forall era.
+  AlonzoEraPParams era =>
+  Proxy era ->
+  BSL.ByteString ->
+  BSL.ByteString ->
+  IO ()
+checkValidCostModelDecoder _ cmsBytes ppuBytes = do
+  let ver = (eraProtVerHigh @era)
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]:
```suggestion
  let ver = eraProtVerHigh @era
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 3]
```diff
@@ -0,0 +1,183 @@
...
+  let cmDecoded = decodeFull @CostModels ver cmsBytes
+  let ppuDecoded = decodeFull @(PParamsUpdate era) ver ppuBytes
+  -- pre-Conway we are failing when deserializing invalid costmodels
+  if (ver < natVersion @9)
+    then
+      cmDecoded
+        `shouldBeLeftAndSatisfy` ( \case
+                                    DecoderErrorDeserialiseFailure txt _ -> txt == "CostModels"
+                                    _ -> False
+                                 )
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]:
```suggestion
    then do
     res <- expectLeftExpr cmDecoded
     res `shouldSatisfy` \case
       DecoderErrorDeserialiseFailure txt _ -> txt == "CostModels"
       _ -> False
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 4]
```diff
@@ -0,0 +1,183 @@
...
+    else -- post-Conway, we are collecting CostModels deserialization errors
+
+      cmDecoded `shouldBeRightAndSatisfy` invalidCm
+
+  -- in no era are we deserializing invalid costmodels within PParamsUpdate
+  ppuDecoded
+    `shouldBeLeftAndSatisfy` ( \case
+                                DecoderErrorDeserialiseFailure _ _ -> True
+                                _ -> False
+                             )
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]:
```suggestion
  res <- expectLeft ppuDecoded
  res `shouldSatisfy` \case
    DecoderErrorDeserialiseFailure _ _ -> True
    _ -> False
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 5]
```diff
@@ -0,0 +1,183 @@
...
+  forall era.
+  AlonzoEraPParams era =>
+  Proxy era ->
+  BSL.ByteString ->
+  BSL.ByteString ->
+  IO ()
+checkValidCostModelDecoder _ cmsBytes ppuBytes = do
+  let ver = (eraProtVerHigh @era)
+  let cmDecoded = decodeFull @CostModels ver cmsBytes
+  cmDecoded `shouldBeRightAndSatisfy` validCm
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]:
```suggestion
  expectRightExpr cmDecoded >>= (`shouldSatisfy` validCm)
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 6]
```diff
@@ -0,0 +1,183 @@
...
+
+  let ppuDecoded = decodeFull @(PParamsUpdate era) ver ppuBytes
+  ppuDecoded
+    `shouldBeRightAndSatisfy` ( \ppu ->
+                                  (validCm <$> ppu ^. ppuCostModelsL) == SJust True
+                              )
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]:
```suggestion
  res <- expectRight ppuDecoded
  res `shouldSatisfy` \ppu -> (validCm <$> ppu ^. ppuCostModelsL) == SJust True
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 7]
```diff
@@ -0,0 +1,183 @@
...
+genInvalidCostModelsEnc lang = do
+  let validCount = costModelParamsCount lang
+  count <- choose (0, validCount - 1)
+  genCostModelsEncoding lang count
+
+genCostModelsEncoding :: Language -> Int -> Gen Encoding
+genCostModelsEncoding lang count = (fromPlainEncoding . toCBOR) <$> enc
+  where
+    enc :: Gen Enc.Enc
+    enc = do
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Redundant parenthesis and binding
```suggestion
genCostModelsEncoding lang count = fromPlainEncoding . toCBOR <$> do
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 8]
```diff
@@ -0,0 +1,183 @@
...
+      values <- vectorOf count (arbitrary :: Gen Int)
+      pure $
+        mconcat
+          [ Enc.E (TkMapLen 1)
+          , Enc.E (TkInt (fromEnum lang))
+          , Enc.E TkListBegin
+          , Enc.Em (Enc.E . TkInt <$> values)
+          , Enc.E TkBreak
+          ]
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: This is all you really need 
:smile: 
```suggestion
      pure $ toCBOR $ Map.singleton lang values
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 9]
```diff
@@ -0,0 +1,183 @@
...
+
+genInvalidCostModelsEnc ::
+  Language ->
+  Gen Encoding
+genInvalidCostModelsEnc lang = do
+  let validCount = costModelParamsCount lang
+  count <- choose (0, validCount - 1)
+  genCostModelsEncoding lang count
+
+genCostModelsEncoding :: Language -> Int -> Gen Encoding
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: You want to be able to generate unknown languages
```suggestion
genCostModelsEncoding :: Int -> Int -> Gen Encoding
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 10]
```diff
@@ -0,0 +1,183 @@
...
+genValidCostModelsEnc lang =
+  genCostModelsEncoding lang (costModelParamsCount lang)
+
+genInvalidCostModelsEnc ::
+  Language ->
+  Gen Encoding
+genInvalidCostModelsEnc lang = do
+  let validCount = costModelParamsCount lang
+  count <- choose (0, validCount - 1)
+  genCostModelsEncoding lang count
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]:
```suggestion
  genCostModelsEncoding (fromEnum lang) count
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 11]
```diff
@@ -0,0 +1,183 @@
...
+                                _ -> False
+                             )
+  where
+    invalidCm (CostModels valid errors _) =
+      null valid && (not . null) errors
+
+genValidCostModelsEnc ::
+  Language ->
+  Gen Encoding
+genValidCostModelsEnc lang =
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Will other changes I suggested this should be a valid CostModel.
```suggestion
genValidCostModelsEnc :: Gen Encoding
genValidCostModelsEnc = do
  NonNegative lang <- arbitrary
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 12]
```diff
@@ -0,0 +1,183 @@
...
+  Proxy era ->
+  BSL.ByteString ->
+  BSL.ByteString ->
+  IO ()
+checkInvalidCostModelDecoder _ cmsBytes ppuBytes = do
+  let ver = (eraProtVerHigh @era)
+  let cmDecoded = decodeFull @CostModels ver cmsBytes
+  let ppuDecoded = decodeFull @(PParamsUpdate era) ver ppuBytes
+  -- pre-Conway we are failing when deserializing invalid costmodels
+  if (ver < natVersion @9)
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]:
```suggestion
  if ver < natVersion @9
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 13]
```diff
@@ -0,0 +1,183 @@
...
+shouldBeRightAndSatisfy (Right r) p =
+  unless (p r) (expectationFailure ("Expectation failed for: " <> show r))
+shouldBeRightAndSatisfy (Left l) _ =
+  expectationFailure $ "Expected Right, got Left: " <> show l
+
+shouldBeLeftAndSatisfy :: (Show a, Show b) => Either a b -> (a -> Bool) -> IO ()
+shouldBeLeftAndSatisfy (Right r) _ =
+  expectationFailure $ "Expected Left, got Right: " <> show r
+shouldBeLeftAndSatisfy (Left l) p =
+  unless (p l) (expectationFailure ("Expectation failed for: " <> show l))
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: I've recently added similar helpers here: https://github.com/input-output-hk/cardano-ledger/blob/c8874b4ae6ef569d28f492dc6d948bfdc607a3ef/libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Common.hs#L81-L130
```suggestion
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 14]
```diff
@@ -0,0 +1,183 @@
...
+genPParamsUpdateEnc _ cmEnc = (fromPlainEncoding . toCBOR) <$> enc
+  where
+    enc :: Gen Enc.Enc
+    enc = do
+      pure $
+        mconcat
+          [ Enc.E (TkMapLen 1)
+          , Enc.E (TkInt 18)
+          , Enc.E (toPlainEncoding (eraProtVerHigh @era) cmEnc)
+          ]
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: This is not a `Gen`, it has no randomness. Also usage of `E` is unnecessary:
```suggestion
genPParamsUpdateEnc ::
  forall era.
  Era era =>
  Proxy era ->
  Encoding ->
  Encoding
genPParamsUpdateEnc _ = 
  fromPlainEncoding . toCBOR . Map.singleton (18 :: Int) . toPlainEncoding (eraProtVerHigh @era)
```

**Review by lehins — CHANGES_REQUESTED** [review]
Not quite what needed to be done, but close. Test cases are very nice! Thank you for that

File: eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs (hunk 1 above)
Comment (teodanciu) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs]: You're totally right, I completely missed half of the point of the task, sorry about that. 
Writing another function that is a combination of the two,  `decodeCostModelsFailingOnError` and `decodeCostModelsCollectingErrors` - that fails for invalid but collects for unknown.

Comment (teodanciu) [reply eras/conway/impl/src/Cardano/Ledger/Conway/PParams.hs]: "Incidentally", the part I didn't write tests for

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs (hunk 13 above)
Comment (teodanciu) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Code looks much better with these, thanks.

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs (hunk 14 above)
Comment (teodanciu) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: :exploding_head:

**Review by lehins — CHANGES_REQUESTED** [review]
You also need to update what sort of CostModel we generate fro PParamUpdates here: https://github.com/input-output-hk/cardano-ledger/blob/3d207b01dca78b231874ab27a2e016cf22753f86/eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Arbitrary.hs#L507

I suspect that is the reason for CI failures

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Arbitrary.hs [hunk 15]
```diff
@@ -504,7 +504,7 @@ instance Era era => Arbitrary (ConwayPParams StrictMaybe era) where
       <*> pure NoUpdate
       <*> arbitrary
       <*> arbitrary
-      <*> (THKD . fmap unFlexibleCostModels <$> arbitrary)
+      <*> (THKD <$> oneof [SJust <$> genValidAndUnknownCostModels, pure SNothing])
```
Comment (teodanciu) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Arbitrary.hs:507]: Is there a better way to do this?

Comment (lehins) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Arbitrary.hs:507]: That's the right way to go about it.

File: eras/alonzo/impl/cardano-ledger-alonzo.cabal [hunk 16]
```diff
@@ -102,6 +102,7 @@ library testlib
         Test.Cardano.Ledger.Alonzo.Binary.RoundTrip
         Test.Cardano.Ledger.Alonzo.CostModel
         Test.Cardano.Ledger.Alonzo.ImpTest
+        Test.Cardano.Ledger.Alonzo.Binary.CostModelsSpec
```
Comment (lehins) [inline eras/alonzo/impl/cardano-ledger-alonzo.cabal]: Nothing important, just alphabetic grouping.
```suggestion
        Test.Cardano.Ledger.Alonzo.Binary.CostModelsSpec
        Test.Cardano.Ledger.Alonzo.Binary.RoundTrip
        Test.Cardano.Ledger.Alonzo.CostModel
        Test.Cardano.Ledger.Alonzo.ImpTest
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 17]
```diff
@@ -0,0 +1,156 @@
...
+    \(lang :: Language) -> do
+      forAllShow (genValidCostModelsEnc lang) (showEnc pxy) $
+        \validCmEnc -> do
+          encodeAndCheckDecoded @era validCmEnc $
+            \cmDecoded ppuDecoded -> do
+              expectRight cmDecoded >>= (`shouldSatisfy` validCm)
+              ppuRes <- expectRight ppuDecoded
+              ppuRes `shouldSatisfy` \ppu -> (validCm <$> ppu ^. ppuCostModelsL) == SJust True
+  where
+    genValidCostModelsEnc lang = genCostModelsEncForLanguage lang (costModelParamsCount lang)
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Minor nit pick. Each language has one cost model, so it is not plural. The only reason why I am suggesting it, is because it can be confused with generator that produces CostModels for many languages (which even has a separate type `CostModels`) 

```suggestion
    genValidCostModelEnc lang = genCostModelEncForLanguage lang (costModelParamsCount lang)
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 18]
```diff
@@ -0,0 +1,156 @@
...
+    validCm (CostModels valid errors unknown) =
+      (not . null) valid && null errors && null unknown
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Avoiding redundant function composition. 
```suggestion
      not (null valid) && null errors && null unknown
```
Also this style is just ugly `(foo . bar . baz) blah` IMHO.

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 19]
```diff
@@ -0,0 +1,156 @@
...
+genCostModelsEnc :: Word8 -> Int -> Gen Encoding
+genCostModelsEnc lang count = do
+  values <- vectorOf count (arbitrary :: Gen Int)
+  pure $ fromPlainEncoding . toCBOR $ Map.singleton lang values
+
+genCostModelsEncForLanguage :: Language -> Int -> Gen Encoding
+genCostModelsEncForLanguage lang =
+  genCostModelsEnc (fromIntegral (fromEnum lang))
+
+expectDeserialiseFailure :: Show t => Either DecoderError t -> Maybe Text -> IO ()
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Adding a call stack will inform you which usage of the function triggered the expectation failure
```suggestion
expectDeserialiseFailure :: 
  (HasCallStack, Show t) => Either DecoderError t -> Maybe Text -> IO ()
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 20]
```diff
@@ -0,0 +1,156 @@
...
+                ppuRes <- expectRight ppuDecoded
+                ppuRes `shouldSatisfy` \ppu -> (unknownCm <$> ppu ^. ppuCostModelsL) == SJust True
+  where
+    genUnknownCostModelsEnc = do
+      let firstUnknownLang = (fromEnum (maxBound @Language)) + 1
+      lang <- choose (fromIntegral firstUnknownLang, maxBound @Word8)
+      NonNegative count <- arbitrary
+      genCostModelsEnc lang count
+    unknownCm (CostModels valid errors unknown) =
+      null valid && null errors && (not . null) unknown
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Ditto
```suggestion
      null valid && null errors && not (null unknown)
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 21]
```diff
@@ -0,0 +1,156 @@
...
+                expectDeserialiseFailure ppuDecoded Nothing
+              else do
+                -- post-Conway, we are collecting unknown CostModels
+                cmRes <- expectRight cmDecoded
+                cmRes `shouldSatisfy` unknownCm
+                ppuRes <- expectRight ppuDecoded
+                ppuRes `shouldSatisfy` \ppu -> (unknownCm <$> ppu ^. ppuCostModelsL) == SJust True
+  where
+    genUnknownCostModelsEnc = do
+      let firstUnknownLang = (fromEnum (maxBound @Language)) + 1
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Redundant
```suggestion
      let firstUnknownLang = fromEnum (maxBound @Language) + 1
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 22]
```diff
@@ -0,0 +1,156 @@
...
+              -- in no era are we deserializing invalid costmodels within PParamsUpdate
+              expectDeserialiseFailure ppuDecoded Nothing
+  where
+    genInvalidCostModelsEnc lang = do
+      let validCount = costModelParamsCount lang
+      count <- choose (0, validCount - 1)
+      genCostModelsEncForLanguage lang count
+
+    invalidCm (CostModels valid errors _) =
+      null valid && (not . null) errors
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Ditto redundant composition. Also should the unknown be empty here as well?
```suggestion
    invalidCm (CostModels valid errors unknown) =
      null valid && not (null errors) && null unknown
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs [hunk 23]
```diff
@@ -0,0 +1,156 @@
...
+encodeAndCheckDecoded cmEnc check = do
+  let ppuEnc =
+        fromPlainEncoding
+          . toCBOR
+          . Map.singleton (18 :: Int)
+          . toPlainEncoding (eraProtVerHigh @era)
+          $ cmEnc
+  let cmBytes = serialize (eraProtVerHigh @era) cmEnc
+  let ppuBytes = serialize (eraProtVerHigh @era) ppuEnc
+  let ver = eraProtVerHigh @era
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: A little less code:
```suggestion
  let ver = eraProtVerHigh @era
      cmBytes = serialize ver cmEnc
      ppuBytes = serialize ver ppuEnc
```

**Review by lehins — APPROVED** [review]
This is beautiful!

I love the extensive test suite for this functionality!

All of the comments I made are mere suggestions.

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs (hunk 22 above)
Comment (teodanciu) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: I was gonna ask you and I forgot, because in the implementation, we are actually updating the invalid cost models when we encounter an error, look: https://github.com/input-output-hk/cardano-ledger/blob/master/libs/cardano-ledger-core/src/Cardano/Ledger/Plutus/CostModels.hs#L340  
Do you think by accident?  Wasn't sure, so I assumed it's on purpose for completion

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs (hunk 18 above)
Comment (teodanciu) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: I don't have any sensibility about this, and because of that I always struggle to decide.  I'm happy to follow "no redundant composition", it makes my life easier :)

File: eras/alonzo/impl/cardano-ledger-alonzo.cabal (hunk 16 above)
Comment (teodanciu) [reply eras/alonzo/impl/cardano-ledger-alonzo.cabal]: It is important to prevent the descent into chaos :D Thank you for noticing

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs (hunk 22 above)
Comment (lehins) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: This is actually an interesting case. On one hand there is no possibility for an invalid CM for a known language to all of a sudden become valid, so we could discard it. On the other keeping it in memory not only allows us to debug a problem if there is one, but also prevents us from violating roundtrip property.
So, I think it is best to preserve the current behavior, which means you can ignore my suggestion here.

Thank you for bringing this to my attention, since I haven't actually thought about this case before.

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs (hunk 17 above)
Comment (teodanciu) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Yes completely agree.

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs (hunk 23 above)
Comment (teodanciu) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/Binary/CostModelsSpec.hs]: Totally, it's even used one more time above this line.  Thanks
