### PR TITLE
More Benchmark tests and optimizations of Shelley.Spec.Ledger.Core Relation Class

### LINKED ISSUE #1504: Performance micro-benchmarks for Shelley validation
We need to verify that we do not have STS rules that accidentally have the wrong asymptotic complexity. We can do this by writing `criterion` micro-benchmarks where we use large ledger states, and check that tx validation times are broadly as expected and in line with the equivalent times in Byron.

For example, at the time of writing, in the UTxO rule, we check that the transaction inputs are valid in a way that is O(n) in the size of the UTxO, when in fact we could do it O(m*log(n/m + 1))  (m being size of txins, n size of utxo).

So a first task would be to set up a criterion test that demonstrates this. We could then use the same setup to look for similar problems.

@JaredCorduan says:
> We could probably start with our valid trace generation for the LEDGER rule. The `forAllLedgerTrace` function generates a trace for the ledger rule, where signals are transactions and the state has things like the UTxOs. I think maybe we could adjust the constants in `geConstants` to make a large genesis state. The property can be trivial (always true).  To see `forAllLedgerTrace` in action, you can look at all the tests in the same file that `forAllLedgerTrace` is defined in.

### PR DESCRIPTION
**Pull request by JaredCorduan**
This is mostly @TimSheard 's work, but I have been helping.

We now have several benchmark tests which process transactions using the `LEDGER` transition. This includes spending UTxOs, stake key registrations, deregistrations, withdrawals, stake pool registrations, re-registrations, retirements, and delegations. These tests use a variety of environment sizes (how big the UTxO set is, how many registered stake keys and stake pools), with a variety of transaction sizes (such as how many registrations, etc).

In the process, many optimizations were found and applied.

~I tried to clean up the commit history, but had a lot of trouble doing so, and abandoned it. We will soon remove the `BenchmarkCrypto` module in favor of something better, but would like to merge this long running PR fairly soon.~

closes #1504

### CODE REVIEW

File: shelley/chain-and-ledger/executable-spec/bench/Main.hs [hunk 1]
```diff
@@ -1,16 +1,160 @@
 module Main where
 
-import Criterion.Main (bench, bgroup, defaultMain, whnf)
+import Control.DeepSeq (NFData)
+import Criterion.Main -- (bench, bgroup, defaultMain, whnf)
+import Data.Word (Word64)
+-- How to precompute env for the UTxO transactions
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/bench/Main.hs]: Seems an odd place for comments!

File: shelley/chain-and-ledger/executable-spec/bench/Main.hs [hunk 2]
```diff
@@ -1,16 +1,160 @@
...
+
+touchDPState :: DPState crypto -> Int
+touchDPState (DPState _x _y) = 1
+
+touchUTxOState :: Shelley.Spec.Ledger.LedgerState.UTxOState cryto -> Int
+touchUTxOState (UTxOState _utxo _deposited _fees _ppups) = 2
+
+profileCreateRegKeys :: IO ()
+profileCreateRegKeys = do
+  putStrLn "Enter profiling stake key creation"
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/bench/Main.hs:52]: We might want to consider using `traceEventIO` here in place of `putStrLn`. Why? If we do a profiling build, `traceEventIO` adds events into the eventlog, which will allow us to more easily interpret the eventlog results.

File: shelley/chain-and-ledger/executable-spec/bench/Main.hs [hunk 3]
```diff
@@ -1,16 +1,160 @@
...
+-- Some things we might want to profile.
+
+-- main = profileUTxO
+-- main = includes_init_SpendOneUTxO
+-- main = profileCreateRegPools 10000
+-- main = profileCreateRegPools 100000
+
+-- =========================================================
+
+varyState ::
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/bench/Main.hs:80]: Can you add some documentation here? The types give very little!

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs [hunk 4]
```diff
@@ -220,43 +220,48 @@ delegationTransition = do
...
             _ptrs = _ptrs ds ⋫ Set.singleton hk
+            -- TODO make _ptrs a bijection. This operation takes time proportional to (_ptrs ds)
+            -- OR turn _stkCreds into a mapping of stake credentials to pointers
+            -- note that the slot values in _stkCreds is no longer needed (no decay)
+            -- then we could use (lookup hk (_delecations ds)) to get ptr, then use domain removal on (_ptrs ds) rather than range removal
           }
     DCertDeleg (Delegate (Delegation hk dpool)) -> do
       -- note that pattern match is used instead of cwitness and dpool, as in the spec
-      hk ∈ dom (_stkCreds ds) ?! StakeDelegationImpossibleDELEG hk
+      haskey hk (_stkCreds ds) ?! StakeDelegationImpossibleDELEG hk
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs:251]: I would definitely be interested in investigating the use of rewrite rules here... the original syntax is much closer to the spec

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs [hunk 5]
```diff
@@ -220,43 +220,48 @@ delegationTransition = do
...
           }
     DCertGenesis (GenesisDelegCert gkh vkh vrf) -> do
       sp <- liftSTS $ asks stabilityWindow
       -- note that pattern match is used instead of genesisDeleg, as in the spec
       let s' = slot +* Duration sp
           (GenDelegs genDelegs) = _genDelegs ds
 
-      gkh ∈ dom genDelegs ?! GenesisKeyNotInpMappingDELEG gkh
+      -- gkh ∈ dom genDelegs ?! GenesisKeyNotInpMappingDELEG gkh
+      (case Map.lookup gkh genDelegs of Just _ -> True; Nothing -> False) ?! GenesisKeyNotInpMappingDELEG gkh
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs:264]: Why not `haskey` as above?

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxo.hs [hunk 6]
```diff
@@ -215,7 +215,7 @@ utxoInductive = do
   minFee <= txFee ?! FeeTooSmallUTxO minFee txFee
 
   let validInputs = dom utxo
-  txins txb ⊆ validInputs ?! BadInputsUTxO (txins txb `Set.difference` validInputs)
+  all (`Map.member` v) (txins txb) ?! BadInputsUTxO (txins txb `Set.difference` validInputs)
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxo.hs:218]: This is definitely less comprehensible

File: shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/BenchmarkFunctions.hs [hunk 7]
```diff
@@ -1,18 +1,56 @@
+{-# LANGUAGE DataKinds #-}
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/BenchmarkFunctions.hs:1]: Do we want to move this into `bench` rather than `test`?

**Review by uroboros — APPROVED** [review]
this looks great to me, thanks @TimSheard

**Comment by uroboros** [comment]
(some commits still need to be signed)

File: shelley/chain-and-ledger/executable-spec/bench/Main.hs (hunk 1 above)
Comment (JaredCorduan) [reply shelley/chain-and-ledger/executable-spec/bench/Main.hs]: ah, those got rearranged by ormolu, and I didn't notice. They were comments in the import list.

**Comment by JaredCorduan** [comment]
@nc6 Thank you for the great review! We are going to do a follow up PR to address your comments. I wanted to get these changes merged sooner rather than later.

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs (hunk 4 above)
Comment (TimSheard) [reply shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs:251]: I have added some comments to indicate this.
