### PR TITLE
Fix totalDeposits and re-enable generation of Updates in Txs

### LINKED ISSUE #1582: Restore Updates as part of generated Transactions
For the moment we are excluding Protocol Parameter Updates from generated transactions due to `UnexpectedDepositPot` STS predicate failures occurring in the property tests. 

Solve this and restore generation of Updates in transactions, also restore the coverage requirement for updates in transactions to 60%.

### PR DESCRIPTION
**Pull request by uroboros**
Closes #1582 

In the case of multiple RegPool certs for the same poolPubKey, in the same Tx, we were counting deposits for each RegPool.

This lead to the `obligation` (num pools * pool deposit + num keys * key deposits) and the `deposit pot` to become out of sync and ultimately firing the`UnexpectedDepositPot` predicate fail in the NewPP rule at epoch boundary.

### CODE REVIEW

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs [hunk 1]
```diff
@@ -220,19 +220,31 @@ balance (UTxO utxo) = foldr addCoins 0 utxo
...
+-- We rely on the dvalue to get the deposit value for each certificate,
+-- but for a list of certificates we must only count a (RegPool hk)
+-- deposit once for a particular hk.
 totalDeposits ::
   PParams ->
   StakePools crypto ->
   [DCert crypto] ->
   Coin
-totalDeposits pc (StakePools stpools) cs = foldl' f (Coin 0) cs'
+totalDeposits pc (StakePools stpools) cs =
```
Comment (JaredCorduan) [inline shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs]: how about something like this, for better readability:

```
totalDeposits pp (StakePools stpools) cs =
  (_keyDeposit pp) * numKeys + (_poolDeposit pp) * numNewPools
  where             
    numKeys = intToCoin . length $ filter isRegKey cs
    pools = Set.fromList . Maybe.catMaybes $ fmap getKeyHashFromRegPool cs
    numNewPools = intToCoin . length $ (Map.keysSet stpools) `Set.difference` pools
    intToCoin = Coin . toInteger
```
(`isRegKey` is in `Shelley.Spec.Ledger.Delegation.Certificates`.)

and

```
getKeyHashFromRegPool :: DCert crypto -> Maybe (KeyHash 'StakePool crypto)
getKeyHashFromRegPool (DCertPool (RegPool p)) = Just . _poolPubKey $ p
getKeyHashFromRegPool _ = Nothing
```

We could then also simplify to this `ax+by` style in the formal spec.

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs [hunk 2]
```diff
@@ -220,19 +219,25 @@ balance (UTxO utxo) = foldr addCoins 0 utxo
   where
     addCoins (TxOut _ a) b = a + b
 
--- | Determine the total deposit amount needed
+-- | Determine the total deposit amount needed.
+-- Since this list may contain multiple (RegPool hk) certificates for the
```
Comment (nc6) [inline shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs]: Which list?

Comment (nc6) [reply shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs]: I would like to expand on the documentation here. Something like:

The block may (legitimately) contain multiple registration certificates for the same pool, where the first will be treated as a registration and any subsequent ones as re-registration. As such, we must only take a deposit for the first such registration.

Note that this is not an issue for key registrations since subsequent registration certificates would be invalid.

**Review by nc6 — APPROVED** [review]
Approved, but would be good to document in more detail.

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs (hunk 1 above)
Comment (uroboros) [reply shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs]: That's much nicer thanks 👍

File: shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs (hunk 2 above)
Comment (uroboros) [reply shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs]: thanks, I've used the above instead
