### PR TITLE
Fix failing tests in `cardano-ledger-alonzo-test`

### LINKED ISSUE #4538: Consistent test failure in cardano-ledger-alonzo-test
The failure is in `Shelley.Rules.ClassifyTraces`, in _Chain and Ledger traces cover the relevant cases_. (This is a nightly-only test.)

The messages are similar to this:

```
Only 7.5% at least 5 epochs in a trace, 20% of the time, but expected 20.0%
```
The percentage varies, but the problem is always in the same test, with all versions of ghc.

The failure can be reproduced locally using

```
NIGHTLY=true cabal test cardano-ledger-alonzo-test --test-options='-p "/Chain and Ledger/"'
```

### PR DESCRIPTION
**Pull request by neilmayhew**
# Description

A temporary fix until the real cause was found was to constrain the version of `hashable` in `cabal.project`:

```
constraints:
  , hashable == 1.4.4.0
allow-older:
  , aeson:hashable
  , strict:hashable
```

However, the real problem was in the way we generate lists of scripts to test with, which used `hashable` to select the list. When `hashable` started producing different hash values, the list changed slightly and the tests that were passing before by pure luck now broke.

Fixing the list of scripts, however, breaks a number of other tests (including non-nightly ones) that were passing by luck.

Closes #4538

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Review by lehins — CHANGES_REQUESTED** [review]
We can't be restricting **to older** dependencies to fix our tests!

**Comment by neilmayhew** [comment]
> We can't be restricting **to older** dependencies to fix our tests!

Yes, understood. This is just a stopgap to get nightly tests passing while we find the real cause (which I'm already working on).

If you'd prefer not to merge it, that's fine by me. It serves as a placeholder for the results of the investigation I've done so far. I felt that by putting the constraint in `cabal.project` it wouldn't affect any of our client projects.

The problem lies in our generation of traces, and the slot numbers that go into the blocks. I don't know yet why the newer version of `hashable` would break that. Since it's to do with traces, it doesn't affect any of the production code. but it does call into question the validity of our testing since the PR that updated the Hackage snapshot as part of enabling compatibility with ghc 9.10.

File: libs/constrained-generators/test/Constrained/Test.hs [hunk 1]
```diff
@@ -269,25 +266,26 @@ testSpecNoShrink :: HasSpec fn a => String -> Specification fn a -> Spec
 testSpecNoShrink = testSpec' False
 
 testSpec' :: HasSpec fn a => Bool -> String -> Specification fn a -> Spec
-testSpec' withShrink n s =
+testSpec' withShrink n s = do
+  let checkCoverage' = checkCoverageWith stdConfidence {certainty = 1e6}
```
Comment (lehins) [inline libs/constrained-generators/test/Constrained/Test.hs]: This syntax is much clearer for integral types and waaaaay more common. I didn't even know about `NumDecimals` language extension.
```suggestion
  let checkCoverage' = checkCoverageWith stdConfidence {certainty = 1_000_000}
```

**Comment by neilmayhew** [comment]
I also manually triggered a [CI run](https://github.com/IntersectMBO/cardano-ledger/actions/runs/10589849020) with `NIGHTLY` enabled, and it succeeded.

File: libs/constrained-generators/test/Constrained/Test.hs (hunk 1 above)
Comment (neilmayhew) [reply libs/constrained-generators/test/Constrained/Test.hs]: I agree, this is better.

I had it that way because the default QuickCheck value is `1e9`, but most people won't know that so the `NumericUnderscores` approach is better.

I wish `NumericUnderscores` was on by default in ghc.

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Rewrite.hs [hunk 2]
```diff
@@ -50,7 +50,7 @@ import qualified Data.Map.Strict as Map
 import Data.Set (Set)
 import qualified Data.Set as Set
 import Data.Void (Void)
-import Debug.Trace
+import qualified Debug.Trace as Debug
```
Comment (lehins) [inline libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Rewrite.hs]: Looks like an unused import. This module needs to be cleaned up at some point and disables warnings at the top of the module will need to go to.

**Review by lehins — APPROVED** [review]
Very nice improvements and fixes to the old tests! Thank you @neilmayhew!

File: libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Rewrite.hs (hunk 2 above)
Comment (neilmayhew) [reply libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Rewrite.hs]: It was easy to do, so I pushed a couple extra commits for this. I also rebased on `master`.

**Comment by neilmayhew** [comment]
Crap! It looks like one my tests is still flaky. I'll check it out locally using the QC seed.

**Comment by neilmayhew** [comment]
> Crap! It looks like one my tests is still flaky. I'll check it out locally using the QC seed.

The failure looks like it was a 1 in 10,000 chance of hitting an obscure bug in the older version of QuickCheck that we're using. I'm going to let it go, and if the problem comes up again I have some mitigation strategies we can use until we're able to move to the newer version of QC. It's only `constrained-generators` that has a bound on the older version.
