### PR TITLE
Ensure `BabbageNonDisjointRefInputs` is only checked for `PlutusV3` scripts

### LINKED ISSUE #5009: Revert predicate check `BabbageNonDisjointRefInputs` for `PlutusV1/V2`
There was a predicate check introduced in Conway era in #4024 that yielded some DApps unable to run their scripts. This was alluded in the https://github.com/IntersectMBO/cardano-ledger/issues/4007#issuecomment-2832525502

It is a bit confusing that the predicate check was introduced in Babbage era UTXO rule, despite being only enabled in Conway. I believe it was implemented in such a way to avoid introducing a whole new UTXO rule in Conway era.

Regardless of this fact the fix for this is pretty straightforward, but it will require an intra-era hard fork:

1. We need to add an upper bound on the major protocol version 11 in this check:
https://github.com/IntersectMBO/cardano-ledger/blob/0fa85012c380eb60a1774ede6ceee4b9edb7a425/eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxo.hs#L216
```&& pvMajor (pp ^. ppProtocolVersionL) < natVersion @11```
Effectively disabling this check entirely

2. Add the same check into the plutus context script translation functionality starting with PlutusV3: https://github.com/IntersectMBO/cardano-ledger/blob/2e2d20cba9c53bc6c41ee122d333a50a68846dc9/eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs#L451

Such fix, will convert this predicate failure from being a general ledger predicate check to plutus specific predicate check

### LINKED ISSUE #5024: Add an ImpTest error message when running a script that hasn't been added to the environment
At the moment the transaction fixup method can fix transactions containing scripts only if the script has been added to `plutusTestScripts`:
https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs#L380-L402

If the transaction contains a script that hasn't been added to that list, the fixup function will not do anything about the script and the transaction will fail with predicate failures about missing datums and whatnot. I think it'd be better to fail the ImpTest with an error that says which scripts could not be found in `plutusTestScripts` instead so whoever is writing the test can go and add it there.

### PR DESCRIPTION
**Pull request by Soupstraw**
# Description

This PR disables `BabbageNonDisjointRefInputs` starting from protocol version 11. This makes it possible to run PlutusV1/V2 scripts that require the same hash to appear in both the inputs and reference inputs.

close #5009
close #5024

# Checklist

- [ ] Commits in meaningful sequence and with useful messages.
- [ ] Tests added or updated when needed.
- [ ] `CHANGELOG.md` files updated for packages with externally visible changes.  
      **NOTE: _New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd)).
- [ ] Versions updated in `.cabal` and `CHANGELOG.md` files when necessary, according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] Version bounds in `.cabal` files updated when necessary.  
      **NOTE: _If bounds change in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process)).
- [x] Code formatted (use `scripts/fourmolize.sh`).
- [x] Cabal files formatted (use `scripts/cabal-format.sh`).
- [x] CDDL files are up to date (use `scripts/gen-cddl.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) updated (use `scripts/gen-hie.sh`).
- [ ] Self-reviewed the diff.

### CODE REVIEW

File: eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxo.hs [hunk 1]
```diff
@@ -231,7 +232,7 @@ disjointRefInputs ::
   Test (BabbageUtxoPredFailure era)
 disjointRefInputs pp inputs refInputs =
   when
-    (pvMajor (pp ^. ppProtocolVersionL) > eraProtVerHigh @BabbageEra)
+    (pvMajor (pp ^. ppProtocolVersionL) == natVersion @10)
```
Comment (lehins) [inline eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxo.hs]: I thought the description of the ticket #5009 was clear: "We need to add an upper bound on the major protocol version 11 in this check"
```suggestion
    (pvMajor (pp ^. ppProtocolVersionL) > eraProtVerHigh @BabbageEra 
      && pvMajor (pp ^. ppProtocolVersionL) < natVersion @11)
```

Conway is two versions: 9 and 10, so this implementation is very much wrong.

File: eras/babbage/impl/testlib/Test/Cardano/Ledger/Babbage/Imp/UtxoSpec.hs [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+spec :: forall era. (AlonzoEraImp era, BabbageEraTxBody era) => SpecWith (ImpInit (LedgerSpec era))
+spec = describe "UTXO" $ do
+  describe "Reference scripts" $ do
+    it "Reference inputs can overlap with regular inputs in PlutusV2" $ do
+      let
+        txOut =
+          mkBasicTxOut
+            ( mkAddr
+                (ScriptHashObj @'Payment $ hashPlutusScript (inputsOverlapsWithRefInputs SPlutusV2))
```
Comment (lehins) [inline eras/babbage/impl/testlib/Test/Cardano/Ledger/Babbage/Imp/UtxoSpec.hs]: This should also work:
```suggestion
                (hashPlutusScript (inputsOverlapsWithRefInputs SPlutusV2))
```

File: eras/babbage/impl/testlib/Test/Cardano/Ledger/Babbage/Imp/UtxoSpec.hs [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+                StakeRefNull
+            )
+            (inject $ Coin 1_000_000)
+            & datumTxOutL .~ (Datum . dataToBinaryData . Data . PV1.I $ 0)
```
Comment (lehins) [inline eras/babbage/impl/testlib/Test/Cardano/Ledger/Babbage/Imp/UtxoSpec.hs]: Few strategic placements of operators and parenthesis and we have a shorter version :smile: 
```suggestion
            & datumTxOutL .~ Datum (dataToBinaryData . Data $ PV1.I 0)
```
Feel free to ignore this suggestion. I just can't help myself when I see a million of compositions

File: eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs [hunk 4]
```diff
@@ -166,6 +166,7 @@ data ConwayContextError era
   | VotingProceduresFieldNotSupported !(VotingProcedures era)
   | ProposalProceduresFieldNotSupported !(OSet.OSet (ProposalProcedure era))
   | TreasuryDonationFieldNotSupported !Coin
+  | ReferenceInputsNotDisjointFromInputs !(Set.Set TxIn)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/TxInfo.hs]: Let's switch it to NonEmpty. It is much more useful than knowing that there are no duplicates
```suggestion
  | ReferenceInputsNotDisjointFromInputs !(NonEmpty TxIn)
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp.hs [hunk 5]
```diff
@@ -90,6 +90,7 @@ spec ::
   , ToExpr (Event (EraRule "ENACT" era))
   , Eq (Event (EraRule "ENACT" era))
   , Typeable (Event (EraRule "ENACT" era))
+  , ContextError era ~ ConwayContextError era
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp.hs]: This is wrong. This will prevent Imp tests from being used in Dijkstra era.
Here is an example of how to properly test `ContextError`: https://github.com/IntersectMBO/cardano-ledger/blob/25876dc795f6ff5b95cffd6890cbe6d907772635/eras/babbage/test-suite/src/Test/Cardano/Ledger/Babbage/TxInfo.hs#L320
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp.hs [hunk 6]
```diff
@@ -125,6 +126,7 @@ conwaySpec ::
...
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp.hs]: Ditto
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 7]
```diff
@@ -38,11 +51,15 @@ import Test.Cardano.Ledger.Conway.ImpTest
...
-import Test.Cardano.Ledger.Plutus.Examples (alwaysSucceedsNoDatum)
+import Test.Cardano.Ledger.Plutus.Examples (alwaysSucceedsNoDatum, inputsOverlapsWithRefInputs)
 
 spec ::
   forall era.
-  ConwayEraImp era =>
+  ( ConwayEraImp era
+  , InjectRuleFailure "LEDGER" BabbageUtxoPredFailure era
+  , InjectRuleFailure "LEDGER" AlonzoUtxosPredFailure era
+  , ContextError era ~ ConwayContextError era
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: Ditto
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 8]
```diff
@@ -63,6 +80,44 @@ spec =
...
+        $ do
+          txIn <- produceScript $ scriptHash SPlutusV3
+          submitFailingTx @era
+            (tx txIn)
+            [ injectFailure $
+                CollectErrors
+                  [ BadTranslation
+                      ( ReferenceInputsNotDisjointFromInputs
+                          (Set.singleton txIn)
+                      )
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: That is how you resolve ghc asking for this constraint: `ContextError era ~ ConwayContextError era`
```suggestion
                      $ inject (ReferenceInputsNotDisjointFromInputs                        (Set.singleton txIn))
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 9]
```diff
@@ -63,6 +80,44 @@ spec =
...
+          txIn <- produceScript $ scriptHash SPlutusV3
+          submitFailingTx @era
+            (tx txIn)
+            [ injectFailure $
+                BabbageNonDisjointRefInputs
+                  (txIn NE.:| [])
+            ]
+      it "Same script cannot appear in regular and reference inputs in PlutusV3 (PV 11)"
+        . whenMajorVersion @11
+        $ do
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: Ditto

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 10]
```diff
@@ -63,6 +80,44 @@ spec =
...
+            & bodyTxL . referenceInputsTxBodyL .~ Set.singleton txIn
+
+      it "Can run scripts that expect inputs and refInputs to overlap (PV 9)"
+        . whenMajorVersion @9
+        $ do
+          txIn <- produceScript $ scriptHash SPlutusV3
+          submitTx_ @era $ tx txIn
+      it "Same script cannot appear in regular and reference inputs in PlutusV3 (PV 10)"
+        . whenMajorVersion @10
+        $ do
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: Please, avoid this style where there is a `do` on a newline by itself
```suggestion
      it "Same script cannot appear in regular and reference inputs in PlutusV3 (PV 10)" $
        whenMajorVersion @10 $ do
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 11]
```diff
@@ -63,6 +80,44 @@ spec =
...
+        tx txIn =
+          mkBasicTx mkBasicTxBody
+            & bodyTxL . inputsTxBodyL .~ Set.singleton txIn
+            & bodyTxL . referenceInputsTxBodyL .~ Set.singleton txIn
+
+      it "Can run scripts that expect inputs and refInputs to overlap (PV 9)"
+        . whenMajorVersion @9
+        $ do
+          txIn <- produceScript $ scriptHash SPlutusV3
+          submitTx_ @era $ tx txIn
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: why would you expect this predicate not to be raised in PV 9? 
```suggestion
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/ImpTest.hs [hunk 12]
```diff
@@ -1591,15 +1598,35 @@ majorFollow pv@(ProtVer x _) = case succVersion x of
 cantFollow :: ProtVer -> ProtVer
 cantFollow (ProtVer x y) = ProtVer x (y + 3)
 
-whenBootstrap :: EraGov era => ImpTestM era () -> ImpTestM era ()
-whenBootstrap a = do
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/ImpTest.hs:1595]: I would suggest adding `whenMajorVersionAtLeast`/`AtMost`, since you'll needthis for your tests. Also you want to put them into `cardano-ledger-shelley:testlib`, instead of in Conway, since they are reusable for all eras.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/ImpTest.hs [hunk 13]
```diff
@@ -1591,15 +1598,35 @@ majorFollow pv@(ProtVer x _) = case succVersion x of
...
+unlessMajorVersion a = do
   pv <- getProtVer
-  unless (HardForks.bootstrapPhase pv) a
+  unless (pvMajor pv == natVersion @v) a
+
+whenBootstrap :: EraGov era => ImpTestM era () -> ImpTestM era ()
+whenBootstrap = whenMajorVersion @9
+
+whenPostBootstrap :: EraGov era => ImpTestM era () -> ImpTestM era ()
+whenPostBootstrap = unlessMajorVersion @9
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/ImpTest.hs]: This is wrong. postBootstrap means protocol version > 9, not equal.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs [hunk 14]
```diff
@@ -120,11 +121,17 @@ datumAndReferenceInputsSpec = do
...
               ]
           & bodyTxL . referenceInputsTxBodyL .~ Set.singleton (mkTxInPartial producingTx 0)
-    submitFailingTx
-      consumingTx
-      ( pure . injectFailure . BabbageNonDisjointRefInputs $
-          mkTxInPartial producingTx 0 :| []
-      )
+    pv <- getProtVer
+    res <- trySubmitTx consumingTx
+    if pv == ProtVer (natVersion @10) 0
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs]: This case should be true for both PV9 and PV10

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs [hunk 15]
```diff
@@ -120,11 +121,17 @@ datumAndReferenceInputsSpec = do
               , mkTxInPartial producingTx 1
               ]
           & bodyTxL . referenceInputsTxBodyL .~ Set.singleton (mkTxInPartial producingTx 0)
-    submitFailingTx
-      consumingTx
-      ( pure . injectFailure . BabbageNonDisjointRefInputs $
-          mkTxInPartial producingTx 0 :| []
-      )
+    pv <- getProtVer
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs]: This is how I suggest you write this test instead:
```haskell
    let badTxIns = mkTxInPartial producingTx 0 :| []
    whenMajorVersionAtMost (natVersion @10) $
      submitFailingTx
        consumingTx
        (pure . injectFailure $ BabbageNonDisjointRefInputs badTxIns)
    -- consumingTx uses PlutusV1 script, so it should be a success
    whenMajorVersionAtLeast (natVersion @11) $
      submitTx_ consumingTx
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs [hunk 16]
```diff
@@ -150,22 +157,6 @@ datumAndReferenceInputsSpec = do
             CollectErrors
               [BadTranslation . inject . InlineDatumsNotSupported @era $ TxOutFromInput lockedTxIn]
         )
-  it "fails with same txIn in regular inputs and reference inputs" $ do
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxosSpec.hs:153]: I'd suggest bringing this test back, but let `setupRefTx` accept a plutus version as an argument. This way it would become:
```haskell
    producingTx <- setupRefTx SPlutusV3
    let
      consumingTx =
        mkBasicTx mkBasicTxBody
          & bodyTxL . inputsTxBodyL
            .~ Set.fromList
              [ mkTxInPartial producingTx 0
              , mkTxInPartial producingTx 1
              ]
          & bodyTxL . referenceInputsTxBodyL .~ Set.singleton (mkTxInPartial producingTx 0)
    let badTxIns = mkTxInPartial producingTx 0 :| []
    whenMajorVersionAtMost (natVersion @10) $
      submitFailingTx
        consumingTx
        (pure . injectFailure $ BabbageNonDisjointRefInputs badTxIns)
    whenMajorVersionAtLeast (natVersion @11) $
      submitFailingTx
        consumingTx
        (pure . injectFailure $ CollectErrors
                  [ BadTranslation $ inject
                      ReferenceInputsNotDisjointFromInputs badTxIns
                   ]
        )

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 17]
```diff
@@ -63,6 +80,44 @@ spec =
...
+        $ do
+          txIn <- produceScript $ scriptHash SPlutusV3
+          submitFailingTx @era
+            (tx txIn)
+            [ injectFailure $
+                BabbageNonDisjointRefInputs
+                  (txIn NE.:| [])
+            ]
+      it "Same script cannot appear in regular and reference inputs in PlutusV3 (PV 11)"
+        . whenMajorVersion @11
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: This test should run for PV11 onwards, not just PV 11, hence my suggestion of adding `whenMajorVersionAtLeast`

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs [hunk 18]
```diff
@@ -276,13 +278,24 @@ fixupDatums tx = impAnn "fixupDatums" $ do
...
-      pure $ getData =<< txOut
-
-    getData :: TxOut era -> Maybe (Data era)
-    getData txOut = case txOut ^. datumTxOutF of
-      DatumHash _dh -> spendDatum <$> Map.lookup (txOutScriptHash txOut) (scriptTestContexts @era)
-      _ -> Nothing
+      mbyTxOut <- traverse (impGetUTxO @era) txIn
+      case mbyTxOut of
+        Just txOut -> getData txOut
+        Nothing -> pure Nothing
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs:284]:
```suggestion
      traverse getData mbyTxOut
```

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs [hunk 19]
```diff
@@ -276,13 +278,24 @@ fixupDatums tx = impAnn "fixupDatums" $ do
...
+
+    getData :: TxOut era -> ImpTestM era (Maybe (Data era))
+    getData txOut =
+      let sh = txOutScriptHash txOut
+       in case txOut ^. datumTxOutF of
+            DatumHash _dh -> case Map.lookup sh (scriptTestContexts @era) of
+              Just x -> pure . Just $ spendDatum x
```
Comment (lehins) [inline eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs]: We need to ensure that the datum is the expected one before we fix it up:
```suggestion
            DatumHash dh -> case Map.lookup sh (scriptTestContexts @era) of
              Just x | hashData (spendDatum x) == dh -> pure . Just $ spendDatum x
```

**Review by lehins — CHANGES_REQUESTED** [review]
It is mostly correct, but there are some issues with correct protocol version usage.
Other than that it looks great and great job on adding a new plutus test script and solving an issue where some scritps are not applicable for all plutus versions.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs (hunk 10 above)
Comment (Soupstraw) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: I never write it like this, this was `fourmolu`'s decision

Comment (Soupstraw) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: And `fourmolu` will complain if I change it to your suggestion.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/ImpTest.hs (hunk 13 above)
Comment (Soupstraw) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/ImpTest.hs]: It's `unless`, not `when`, but I agree it shouldn't run for versions `< 9`

File: eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs (hunk 18 above)
Comment (Soupstraw) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs:284]: I don't think this is a traversal. It looks like there could be a nicer way to write this, but I couldn't figure it out.

Comment (lehins) [reply eras/alonzo/impl/testlib/Test/Cardano/Ledger/Alonzo/ImpTest.hs:284]: Oh, I see `getData` itself also returns `Maybe`. This means you are just missing a `join`
```suggestion
      join <$> traverse getData mbyTxOut
```
However, feel free to leave the way you have it with the case statement. Version above with `join` isn't necessarily easier to read.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs (hunk 10 above)
Comment (lehins) [reply eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: > And fourmolu will complain if I change it to your suggestion.

That is because you didn't apply my suggestion exactly. Make sure to replace `.` with `$` and it will work. It is the mixture of `.` and `$` that causes `fourmolu` to format it in a weird way, because they have different fixity.

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 20]
```diff
@@ -63,6 +79,38 @@ spec =
         [fromNativeScript spendingScript, fromNativeScript spendingScript]
           ++ extraScripts
           ++ extraScripts
+    describe "disjoint inputs and reference inputs" $ do
+      let
+        scriptHash lang = hashPlutusScript $ inputsOverlapsWithRefInputs lang
+        tx :: TxIn -> Tx era
+        tx txIn =
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: We use `tx` binding in tests extensively for a test transaction. For consistency sake, I'd prefer to name a local function that does not conflict with that pattern and uses a slightly more descriptive name, eg:
```suggestion
        mkTestTx :: TxIn -> Tx era
        mkTestTx txIn =
```

File: eras/babbage/impl/testlib/Test/Cardano/Ledger/Babbage/Imp/UtxoSpec.hs [hunk 21]
```diff
@@ -0,0 +1,68 @@
...
+            )
+            (inject $ Coin 1_000_000)
+            & datumTxOutL .~ Datum (dataToBinaryData . Data $ PV1.I 0)
+      tx <-
+        submitTx $
+          mkBasicTx mkBasicTxBody
+            & bodyTxL . outputsTxBodyL .~ SSeq.singleton txOut
+      let txIn = txInAt (0 :: Integer) tx
+      majorVer <- pvMajor <$> getsPParams ppProtocolVersionL
+      unless (majorVer >= natVersion @9 && majorVer <= natVersion @10) $
```
Comment (lehins) [inline eras/babbage/impl/testlib/Test/Cardano/Ledger/Babbage/Imp/UtxoSpec.hs]: I feel like you are hanging around mathematicians too much :rofl: 
```suggestion
      when (majorVer < natVersion @9 || majorVer > natVersion @10) $
```

File: eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs [hunk 22]
```diff
@@ -63,6 +78,34 @@ spec =
...
+        submitFailingTx @era
+          (mkTestTx txIn)
+          [ injectFailure $ BabbageNonDisjointRefInputs [txIn]
+          ]
+      it "Same script cannot appear in regular and reference inputs in PlutusV3 (PV 10)" $ whenMajorVersion @10 $ do
+        txIn <- produceScript $ scriptHash SPlutusV3
+        submitFailingTx @era
+          (mkTestTx txIn)
+          [ injectFailure $ BabbageNonDisjointRefInputs [txIn]
+          ]
```
Comment (lehins) [inline eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/UtxoSpec.hs]: It is cleaner to combine two identical tests into one
```suggestion
      it "Cannot run scripts that expect inputs and refInputs to overlap (PV 9/10)" $ do 
        whenMajorVersionAtMost @10 $ do
          txIn <- produceScript $ scriptHash SPlutusV3
          submitFailingTx @era
            (mkTestTx txIn)
            [ injectFailure $ BabbageNonDisjointRefInputs [txIn]
            ]
```

FYI. We could add `whenMajorVersionAtLeast @9`, but that would be redundant, since Conway starts with `9` and this test is only valid starting with Conway

**Review by lehins — APPROVED** [review]
Very nice!
Couple of minor suggestions, but nothing critical.
