### PR TITLE
Change how SPO votes are counted

### LINKED ISSUE #4645: Change to how SPO votes are counted
It has been brought up by a number of community members that the way we currently compute SPO votes is not what everyone expected.
Current implementation is such that for `HardForkInitiation` behavior is exactly the same as for DReps, however for the other three governance actions, that SPOs can vote on, behavior is different for SPOs that did not vote. In other words for these three governance action types:
* `NoConfidence`
* `UpdateCommittee`
* `ParameterUpdate` (when it includes updates to parameter belonging to the security group)

the default vote counted for SPOs that didn't vote is `Abstain`, instead of `No`. The default vote of `No` is the behavior for DReps, while for SPOs it is default only when `HardForkInitiation` is proposed.

Current behavior is specified in [this portion of the spec](https://github.com/IntersectMBO/formal-ledger-specifications/blob/762d3f42ef2876f039fafda1eb7f69d651129261/src/Ledger/Ratify.lagda#L378-L380) and the actual implementation lives here: https://github.com/IntersectMBO/cardano-ledger/blob/8d16d698dd499fd171845da16611c7c7026c1754/eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs#L204-L207

This lead to some concerns about inclusion of SPOs into the future of parameter updates, that is why many have suggested that we should mimic the behavior of DReps exactly. However, that defaulting of SPOs to vote `No`, has its own concerns. In particular there is a danger if SPOs aren't active enough that they could inadvertently block sensible proposals. Inactivity could be potentially blamed either on indifference or issues with legality for some SPOs.

In order to solve this conundrum we made it the topic of [Ledger Working Group Meeting #4](https://lu.ma/foop6fuh) and had a very productive discussion with some community members and came up with an ingenious solution:

Everyone agreed right of the bat that if we had a mechanism for SPOs to choose whether they wanted to default to `Abstain` instead of `No`, we would have solved the problem. However making a change to PoolParams at this time is impossible without a new era. Also, whenever this issue of customizing PoolParams has surfaced during Conway development, we knew that making such a change would have been too ambitious of a goal, which would have lead to an extensive delay to the Conway delivery. This has to do with the fact that `PoolParams` is not a type family yet. Therefore, since adding a custom field to the PoolParams with an optional default vote was not a path that we could choose we almost discarded this idea. It was then that Martin Lang of ATADA Stake Pool proposed an interesting and unexpected solution: we can achieve ability of specifying a default vote for SPOs if we choose to mimic the default delegation of [ppRewardAccount](https://github.com/IntersectMBO/cardano-ledger/blob/8d16d698dd499fd171845da16611c7c7026c1754/libs/cardano-ledger-core/src/Cardano/Ledger/PoolParams.hs#L210) that is specified in the PoolParams.

To be more specific the solution to this problem is:

1. To change the default vote for SPOs to `No` from `Abstain` for all of the three proposals in question
2. Check whether SPO's reward address is delegated to the predefined `AlwaysNoConfidence` DRep and count default vote as `Yes` only on `NoConfidence` proposals for that SPO.
3. Check whether SPO's reward address is delegated to predefined `AlwaysAbstain` DRep and count default vote as `Abstain` for that SPO on all three: `NoConfidence`, `UpdateCommitee` and `ParameterUpdate` proposals.

This is not a terribly complicated logic to implement, which means that we can almost certainly take care of in time for the protocol version `10.0`, i.e. the intra-era hard fork, a.k.a Chang+1

### PR DESCRIPTION
**Pull request by Lucsanszky**
# Description
Resolves #4645 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs [hunk 1]
```diff
@@ -201,10 +207,16 @@ spoAcceptedRatio
...
-              Nothing
-                | HardForkInitiation {} <- pProcGovAction -> (yes, abstain)
-                | otherwise -> (yes, abstain + stake)
+              Nothing -> case res of
+                Just DRepAlwaysNoConfidence
+                  | NoConfidence {} <- pProcGovAction -> (yes + stake, abstain)
+                  | otherwise -> (yes, abstain)
+                Just DRepAlwaysAbstain -> (yes, abstain + stake)
+                -- TODO: figure out if other cases need special care
+                _ -> (yes, abstain)
```
Comment (lehins) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs]: We need to make sure that:
* we do not change the behavior of `HardForkInitiation`
* we preserve the bootstrap behavior
* we have access to protocol version, which we probably can also stick into `RatifyEnv`
```suggestion
              Nothing
                | HardForkInitiation {} <- pProcGovAction -> (yes, abstain)
                | bootstrapPhase pv -> (yes, abstain + stake)
                | otherwise -> case res of
                  Just DRepAlwaysNoConfidence
                    | NoConfidence {} <- pProcGovAction -> (yes + stake, abstain)
                  Just DRepAlwaysAbstain -> (yes, abstain + stake)
                  _ -> (yes, abstain)
```

**Review by lehins — COMMENTED** [review]
This is looking good

**Comment by Lucsanszky** [comment]
~I had to disable the ratify conformance test until https://github.com/IntersectMBO/formal-ledger-specifications/issues/578 is resolved, since now the spec and the implementation differs with regards to the SPO vote counts.~ I managed to tweak the SPO votes for conformance tests to make the tests pass until the spec is up-to-date. I'll probably add some more comments why I needed to adjust some of the stake amounts in pools for the tests (`electBasicCommittee` registers a stake pool and with the vote count changes we didn't always reach the threshold post-bootstrap). Other than that, this is ready for review and I'll add some tests in a separate PR.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs [hunk 2]
```diff
@@ -187,24 +193,36 @@ spoAccepted re rs gas =
...
         let CompactCoin stake = individualTotalPoolStake distr
             vote = Map.lookup poolId gasStakePoolVotes
+            drep =
+              Map.lookup poolId rePoolParams >>= \d -> Map.lookup ((raCredential . ppRewardAccount) d) reDelegatees
          in case vote of
               Nothing
                 | HardForkInitiation {} <- pProcGovAction -> (yes, abstain)
-                | otherwise -> (yes, abstain + stake)
+                | bootstrapPhase pv -> (yes, abstain + stake)
+                | otherwise -> case drep of
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs:228]: Would you mind either adding a comment here, explaining the idea - or maybe better yet, updating the haddock above to reflect this case.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs [hunk 3]
```diff
@@ -187,24 +193,36 @@ spoAccepted re rs gas =
...
+  pv
     | totalActiveStake == 0 = 0 -- guard against the degenerate case when active stake is zero.
     | totalActiveStake == abstainStake = 0 -- guard against the degenerate case when all abstain.
     | otherwise = toInteger yesStake % toInteger (totalActiveStake - abstainStake)
     where
       accumStake (!yes, !abstain) poolId distr =
         let CompactCoin stake = individualTotalPoolStake distr
             vote = Map.lookup poolId gasStakePoolVotes
+            drep =
+              Map.lookup poolId rePoolParams >>= \d -> Map.lookup ((raCredential . ppRewardAccount) d) reDelegatees
```
Comment (teodanciu) [inline eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs]: I wonder if  pattern matching would be more efficient, since this will be performed repeatedly - so I mean if something like this would lead to fewer lambda allocations/overhead:
```
drep = case Map.lookup poolId rePoolParams of
  Just d -> Map.lookup (raCredential (ppRewardAccount d)) reDelegatees
  Nothing -> Nothing
``` 
But don't know if it makes any difference at all, so feel free to ignore this.

**Review by teodanciu — COMMENTED** [review]
Looks good  to me, but will let @lehins approve since this is is performance-sensitive Umap stuff.

File: eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs (hunk 3 above)
Comment (lehins) [reply eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs]: They are in fact identical, since this is exactly the implementation of `>>=` for `Maybe` and it will be optimized by the compiler. GHC is really good at this sort of stuff. For that reason I do prefer Daniel's implementation, since it is a bit more concise. Except, for further readability, I would also suggest removing redundant composition and then either splitting the line:
```suggestion
              Map.lookup poolId rePoolParams >>= \d -> 
                Map.lookup (raCredential (ppRewardAccount d)) reDelegatees
```
or switching to `do` syntax:
```suggestion
              d <- Map.lookup poolId rePoolParams
              Map.lookup (raCredential (ppRewardAccount d)) reDelegatees
```
But that's not critical by any means.

**Review by lehins — APPROVED** [review]
This looks great!
We'll definitely need to a few Imp tests for this and re-enable RATIFY conformance test once spec catches up. 
But, it is definitely OK to postpone that work until after this PR is merged.

**Comment by Lucsanszky** [comment]
> This looks great! We'll definitely need to a few Imp tests for this and re-enable RATIFY conformance test once spec catches up. But, it is definitely OK to postpone that work until after this PR is merged.

Sounds good! I managed to tweak the conformance tests to filter for `Abstain` votes for SPOs, which is slightly better than disabling the `RATIFY` conformance tests altogether.
