### PR TITLE
`constrained-generators`: Fix test failure related to narrowing of fold specs

### LINKED ISSUE #4753: constrain-generators CI failure
First occurred at: https://github.com/IntersectMBO/cardano-ledger/actions/runs/11830083195/job/32964893516

Reproducer:

```
Failures:

  test/Constrained/Test.hs:180:9: 
  1) constrained, prop_gen_sound @BaseFn, Map Bool Int
       uncaught exception: ErrorCall
       narrowByFuelAndSize loops:
         fuel = 49
         size = 31
         specs = (MemberSpec [ -1 ],TypeSpec [-9223372036854775807..-50] [])
         narrowFoldSpecs spec = (MemberSpec [ -1 ],TypeSpec [-9223372036854775807..-50] [])
         go (narrowFoldSpecs specs) = Just (MemberSpec [ -1 ],TypeSpec [-9223372036854775807..-50] [])
       
       CallStack (from HasCallStack):
         error, called at src/Constrained/Base.hs:3103:7 in constrained-generators-0.2.0.0-inplace:Constrained.Base
       (after 28 tests and 11 shrinks)
         TypeSpec
           (MapSpec
              hint       = Nothing
              mustKeys   = fromList [False,True]
              mustValues = []
              size       = TrueSpec @(Integer)
              elem       = MemberSpec [ 6 elements ...] @(Bool,Int)
              fold       = FoldSpec
                             fn   = Id
                             spec = TypeSpec [..-22] [])
           []
         
         Simplfied spec:
           TypeSpec
             (MapSpec
                hint       = Nothing
                mustKeys   = fromList [False,True]
                mustValues = []
                size       = TrueSpec @(Integer)
                elem       = MemberSpec [ 6 elements ...] @(Bool,Int)
                fold       = FoldSpec
                               fn   = Id
                               spec = TypeSpec [..-22] [])
             []

  To rerun use: --match "/constrained/prop_gen_sound @BaseFn/Map Bool Int/" --seed 1266869102

Randomized with seed 1266869102

Finished in 483.9121 seconds
701 examples, 1 failure, 1 pending
Test suite constrained: FAIL
```

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
# Description

closes #4753

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

File: libs/constrained-generators/src/Constrained/Base.hs [hunk 1]
```diff
@@ -3097,7 +3097,7 @@ narrowByFuelAndSize ::
   (Specification fn a, Specification fn a) ->
   (Specification fn a, Specification fn a)
 narrowByFuelAndSize fuel size specs =
-  loop (1000 :: Int) (narrowFoldSpecs specs)
+  loop (100 :: Int) (onlyOnce $ narrowFoldSpecs specs)
```
Comment (TimSheard) [inline libs/constrained-generators/src/Constrained/Base.hs]: Perhaps say something about the strategy of only narrowing once?

File: libs/constrained-generators/test/Constrained/Test.hs [hunk 2]
```diff
@@ -370,3 +371,10 @@ hasSizeSet = hasSize (rangeSize 1 3)
 
 hasSizeMap :: Specification BaseFn (Map Int Int)
 hasSizeMap = hasSize (rangeSize 1 3)
+
+------------------------------------------------------------------------
+-- Tests for narrowing
+------------------------------------------------------------------------
+
+prop_noNarrowLoop :: Int -> Int -> Specification BaseFn Int -> Specification BaseFn Int -> Property
+prop_noNarrowLoop f s eSpec fSpec = f >= 0 ==> discardAfter 100_000 $ narrowByFuelAndSize f s (eSpec, fSpec) `seq` property True
```
Comment (TimSheard) [inline libs/constrained-generators/test/Constrained/Test.hs]: Explain what the invariant means. What is it that we don't want to be True?

**Review by TimSheard — APPROVED** [review]
The Narrowing stuff is a bit unexplained. Any thing you can do would be good here.
